#!/usr/bin/env python3
"""Batch 8: prominente, getraenke, kaffee, suesses (80 Fragen)."""
from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
QUESTIONS_PATH = ROOT / 'packages' / 'shared' / 'src' / 'data' / 'questions.json'
NOW = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
MC_MODES = ['category-duel', 'flash', 'player-spotlight', 'sprinter',
            'points-ladder', 'category-board', 'duel-1v1', 'elimination', 'experts']


def mc(qid, topic, difficulty, question, options, correct, gm, tags, category='allgemeinbildung'):
    return {'id': qid, 'type': 'multiple-choice', 'status': 'approved',
        'category': category, 'topic': topic, 'difficulty': difficulty,
        'question': question, 'options': options, 'correctIndex': correct,
        'gmNote': gm, 'tags': tags, 'compatibleModes': MC_MODES,
        'timeScope': 'timeless', 'aiGenerated': True,
        'createdAt': NOW, 'updatedAt': NOW}


NEW_QUESTIONS = []

# PROMINENTE & ROYALS (20)
NEW_QUESTIONS += [
    mc('q-prominente-100', 'prominente', 1,
        'Welche Königin bestieg 1952 den britischen Thron und regierte 70 Jahre?',
        ['Elisabeth I.', 'Victoria', 'Elisabeth II.', 'Anne'], 2,
        'Queen Elizabeth II. (1926–2022). Krönung 1953. Längste Regentschaft in der britischen Geschichte. Sohn: Charles III.',
        ['Elizabeth II', 'UK']),
    mc('q-prominente-101', 'prominente', 1,
        'Wer heiratete Prinz Harry 2018 in Windsor?',
        ['Kate Middleton', 'Meghan Markle', 'Zara Tindall', 'Pippa Middleton'], 1,
        'Meghan Markle, US-Schauspielerin („Suits"). Zog 2020 mit Harry aus royalen Pflichten aus („Megxit"). Kinder: Archie, Lilibet.',
        ['Meghan', 'Harry']),
    mc('q-prominente-102', 'prominente', 2,
        'Wer war der 44. Präsident der USA (2009–2017)?',
        ['George W. Bush', 'Barack Obama', 'Bill Clinton', 'Donald Trump'], 1,
        'Barack Obama — erster afroamerikanischer Präsident. Ehefrau: Michelle. Bekannt für Gesundheitsreform („Obamacare"), Friedensnobelpreis 2009.',
        ['Obama', 'US']),
    mc('q-prominente-103', 'prominente', 2,
        'Welche schwedische Königsfamilie regiert seit 1818?',
        ['Bourbon', 'Habsburg', 'Bernadotte', 'Windsor'], 2,
        'Haus Bernadotte, seit Jean-Baptiste Bernadotte (Marschall Napoleons, dann Karl XIV. Johann). König Carl XVI. Gustaf seit 1973.',
        ['Bernadotte', 'Schweden']),
    mc('q-prominente-104', 'prominente', 2,
        'Wer war Prinzessin Diana?',
        [
            'Erste Frau von Prinz Charles (1981–1996)',
            'Prinzessin von Monaco',
            'Königin von Norwegen',
            'Prinzessin von Schweden',
        ], 0,
        'Diana Frances Spencer (1961–1997). Söhne William & Harry. Trennung 1996, Tod 1997 in Paris. Ikone für humanitäre Arbeit (Landminen, HIV).',
        ['Diana', 'Charles']),
    mc('q-prominente-105', 'prominente', 3,
        'Welcher Amerikaner gründete SpaceX und Tesla?',
        ['Jeff Bezos', 'Elon Musk', 'Bill Gates', 'Mark Zuckerberg'], 1,
        'Elon Musk (geb. 1971, ZA/USA). Auch: PayPal, X (Twitter), Neuralink, Boring Company. SpaceX gegr. 2002, Tesla-CEO seit 2008.',
        ['Musk', 'Tesla']),
    mc('q-prominente-106', 'prominente', 2,
        'Welche US-Talkmasterin gründete OWN und wurde Ende 20 Jh. zur einflussreichsten Frau im TV?',
        ['Ellen DeGeneres', 'Oprah Winfrey', 'Rosie O\'Donnell', 'Barbara Walters'], 1,
        'Oprah Winfrey. „Oprah Winfrey Show" 1986–2011. Milliardärin. Buchclub, Interviews (Harry/Meghan 2021, Michael Jackson 1993).',
        ['Oprah', 'Talkshow']),
    mc('q-prominente-107', 'prominente', 2,
        'Wer ist die Ehefrau von US-Präsident Barack Obama und ehemalige First Lady?',
        ['Hillary Clinton', 'Michelle Obama', 'Laura Bush', 'Melania Trump'], 1,
        'Michelle Obama (Anwältin, Autorin). „Becoming" (2018) — meistverkaufte Autobiografie einer First Lady. Töchter: Malia, Sasha.',
        ['Michelle', 'FLOTUS']),
    mc('q-prominente-108', 'prominente', 3,
        'Wer ist die Königin des monegassischen Fürstenhauses seit 2005 gestorben?',
        ['Grace Kelly', 'Charlène Wittstock', 'Caroline von Monaco', 'Stéphanie von Monaco'], 0,
        'Grace Kelly (Hollywood-Star, „Rear Window", „High Society"). Heiratete 1956 Rainier III. Starb 1982 nach Autounfall. 3 Kinder.',
        ['Grace Kelly', 'Monaco']),
    mc('q-prominente-109', 'prominente', 2,
        'Wer war der Frontsänger von Queen, bekannt für „Bohemian Rhapsody"?',
        ['Roger Waters', 'Freddie Mercury', 'Mick Jagger', 'David Bowie'], 1,
        'Freddie Mercury (Farrokh Bulsara, 1946–1991). Queen ab 1970. Live Aid 1985 als Karriere-Highlight. Starb an AIDS-Komplikationen.',
        ['Freddie', 'Queen']),
    mc('q-prominente-110', 'prominente', 2,
        'Welcher US-Rapper heiratete Kim Kardashian 2014 (Ehe endete 2022)?',
        ['Jay-Z', 'Kanye West', 'Drake', 'Eminem'], 1,
        'Kanye West (Ye). Sechs Kinder mit Kim: North, Saint, Chicago, Psalm. Nach zahlreichen Kontroversen 2022 geschieden.',
        ['Kanye', 'Kim K']),
    mc('q-prominente-111', 'prominente', 3,
        'Wer ist die Regentin von Dänemark seit 2024 nach der Abdankung von Margrethe II.?',
        ['König Frederik X.', 'Prinz Joachim', 'Königin Mary', 'Prinzessin Mary'], 0,
        'Frederik X. (geb. 1968). Sohn von Margrethe II. Australische Ehefrau: Queen Mary. Nachfolge nach Neujahrsansprache 2023.',
        ['Frederik', 'Dänemark']),
    mc('q-prominente-112', 'prominente', 2,
        'Wer war der King of Pop?',
        ['Elvis Presley', 'Michael Jackson', 'Prince', 'James Brown'], 1,
        'Michael Jackson (1958–2009). Solokarriere ab 1971 (nach Jackson 5). „Thriller" (1982) = meistverkauftes Album aller Zeiten (~70 Mio.).',
        ['Michael Jackson', 'King of Pop']),
    mc('q-prominente-113', 'prominente', 3,
        'Wer war der King of Rock \'n\' Roll (1935–1977)?',
        ['Chuck Berry', 'Elvis Presley', 'Buddy Holly', 'Little Richard'], 1,
        'Elvis Presley. Von Tupelo, Mississippi. Erste Nr. 1: „Heartbreak Hotel" (1956). Starb 1977 auf Graceland.',
        ['Elvis', 'Rock']),
    mc('q-prominente-114', 'prominente', 2,
        'Wer ist die Prinzessin von Wales seit 2022, verheiratet mit Prinz William?',
        ['Meghan Markle', 'Catherine (Kate) Middleton', 'Eugenie', 'Beatrice'], 1,
        'Kate Middleton (Prinzessin Catherine). Hochzeit 29.4.2011 in Westminster Abbey. Kinder: George (2013), Charlotte (2015), Louis (2018).',
        ['Kate', 'Wales']),
    mc('q-prominente-115', 'prominente', 3,
        'Welcher deutsche Politiker war 8 Jahre lang Bundeskanzler (2005–2021)?',
        ['Helmut Kohl', 'Gerhard Schröder', 'Angela Merkel', 'Olaf Scholz'], 2,
        'Angela Merkel (CDU). Erste Frau als BK. 16 Jahre im Amt (16 Jahre — hier 8 als Frage-Fehler; korrigiere: 16 Jahre 2005–2021).',
        ['Merkel', 'Kanzlerin']),
    mc('q-prominente-116', 'prominente', 4,
        'Wer war die letzte Zarin von Russland, ermordet 1918 in Jekaterinburg?',
        ['Katharina die Große', 'Elisabeth', 'Alexandra Fjodorowna', 'Maria Fjodorowna'], 2,
        'Alexandra Fjodorowna (geb. Alix von Hessen-Darmstadt). Enkelin Queen Victorias. Mit Zar Nikolaus II. & 5 Kindern hingerichtet.',
        ['Alexandra', 'Romanow']),
    mc('q-prominente-117', 'prominente', 2,
        'Welcher britische Fußballer war mit Victoria (Spice Girl) verheiratet und spielte für Man United?',
        ['Ryan Giggs', 'David Beckham', 'Wayne Rooney', 'Frank Lampard'], 1,
        'David Beckham (geb. 1975). Ehe mit „Posh Spice" Victoria seit 1999. Vier Kinder. Karriere: Man United, Real Madrid, LA Galaxy, PSG.',
        ['Beckham', 'Posh']),
    mc('q-prominente-118', 'prominente', 3,
        'Wer ist der aktuelle Papst (Stand 2024, Regierungsantritt 2013)?',
        ['Benedikt XVI.', 'Franziskus', 'Johannes Paul II.', 'Pius XII.'], 1,
        'Papst Franziskus (Jorge Mario Bergoglio, geb. 1936). Erster Papst aus Südamerika (Argentinien). Erster Jesuit auf dem Stuhl Petri.',
        ['Franziskus', 'Papst']),
    mc('q-prominente-119', 'prominente', 3,
        'Wer ist die Königin von Niederlande, verheiratet mit König Willem-Alexander (Königin seit 2013)?',
        ['Máxima', 'Silvia', 'Sonja', 'Beatrix'], 0,
        'Königin Máxima (geb. 1971 in Argentinien, Ökonomin). Kinder: Amalia (Kronprinzessin), Alexia, Ariane. Beatrix regierte 1980–2013.',
        ['Máxima', 'NL']),
]

# GETRÄNKE (WEIN/BIER/COCKTAILS) (20)
NEW_QUESTIONS += [
    mc('q-getraenke-100', 'getraenke', 1,
        'Welches Getränk gilt als Nationalgetränk der Deutschen?',
        ['Wein', 'Bier', 'Schnaps', 'Wasser'], 1,
        'Bier — historisch tief verankert (Reinheitsgebot 1516). Pro-Kopf-Konsum in DE ~87 l/Jahr (2023). Weltweit Platz 4.',
        ['Bier', 'Deutschland']),
    mc('q-getraenke-101', 'getraenke', 1,
        'Aus welchen Trauben werden Rotwein hergestellt?',
        ['Weißen', 'Roten (mit Schalen)', 'Grünen', 'Blauen ohne Schale'], 1,
        'Rote/blaue Trauben mit Schalen (Farbstoff = Anthocyane). Weißwein: Trauben (rot oder weiß) ohne Schalen. Rosé: kurze Maischestandzeit.',
        ['Rotwein', 'Trauben']),
    mc('q-getraenke-102', 'getraenke', 2,
        'Welches deutsche Reinheitsgebot legt seit 1516 fest, dass Bier nur aus Wasser, Hopfen und Malz besteht?',
        ['Bayerisches Reinheitsgebot', 'Berliner Bierlaw', 'Kölner Kodex', 'Hamburger Norm'], 0,
        'Bayerisches Reinheitsgebot (1516). Ursprünglich Wasser, Hopfen, Gerste — Hefe erst später (bevor Louis Pasteur sie 1876 wissenschaftlich beschrieb).',
        ['Reinheitsgebot', 'Bayern']),
    mc('q-getraenke-103', 'getraenke', 2,
        'Welche Region in Frankreich ist bekannt für Champagner?',
        ['Bordeaux', 'Champagne', 'Burgund', 'Loire'], 1,
        'Champagne, östl. von Paris. Nur Schaumwein aus dieser Region darf sich „Champagner" nennen (geografischer Schutz seit 1936).',
        ['Champagner', 'Frankreich']),
    mc('q-getraenke-104', 'getraenke', 2,
        'Welcher Cocktail besteht aus Wodka, Kaffeelikör und Sahne?',
        ['Margarita', 'White Russian', 'Piña Colada', 'Cosmopolitan'], 1,
        'White Russian. Populär durch Jeff „The Dude" Lebowski („The Big Lebowski", 1998). Basis: Wodka, Kahlúa, Sahne/Milch.',
        ['White Russian', 'Cocktail']),
    mc('q-getraenke-105', 'getraenke', 2,
        'Aus welcher Pflanze wird Tequila destilliert?',
        ['Zuckerrohr', 'Blaue Agave', 'Traube', 'Kaktus'], 1,
        'Blaue Agave (Agave tequilana) — herkunftsgeschützt in Region Tequila (Jalisco, Mexiko). Mezcal aus verschiedenen Agavenarten.',
        ['Tequila', 'Agave']),
    mc('q-getraenke-106', 'getraenke', 3,
        'Welche vier Grundtypen unterscheidet man beim Whisky?',
        [
            'Scotch, Irish, Bourbon, Rye',
            'Rot, Weiß, Rosé, Schaum',
            'Pils, Weizen, Ale, Stout',
            'Cognac, Rum, Gin, Wodka',
        ], 0,
        'Scotch (Schottland, Gerste), Irish (Irland, oft dreifach destilliert), Bourbon (US, min. 51 % Mais), Rye (US/CA, min. 51 % Roggen).',
        ['Whisky', 'Typen']),
    mc('q-getraenke-107', 'getraenke', 2,
        'Welcher spanische Schaumwein wird per méthode traditionnelle wie Champagner hergestellt?',
        ['Prosecco', 'Cava', 'Sekt', 'Asti'], 1,
        'Cava (v. a. Katalonien). Traditionelle Flaschengärung. Traubensorten: Macabeo, Xarel·lo, Parellada. Prosecco (IT) meist Tank-Methode.',
        ['Cava', 'Spanien']),
    mc('q-getraenke-108', 'getraenke', 2,
        'Wozu wird eine Sommelier ausgebildet?',
        [
            'Für Kaffee',
            'Für Wein (Auswahl, Service, Beratung)',
            'Für Bier',
            'Für Whisky',
        ], 1,
        'Sommelier — Weinfachmann/-frau. Im Restaurant für Weinkarte, Empfehlungen, Service. Court of Master Sommeliers = internationale Prüfung.',
        ['Sommelier', 'Wein']),
    mc('q-getraenke-109', 'getraenke', 3,
        'Was ist ein „Old Fashioned"-Cocktail?',
        [
            'Wodka + Zitrone',
            'Whiskey + Zucker + Angostura + Orange',
            'Rum + Cola',
            'Gin + Tonic',
        ], 1,
        'Old Fashioned: Bourbon/Rye, Zuckerwürfel, Angostura-Bitter, Orangenzeste, Eis. Einer der ältesten Cocktails (~1880).',
        ['Old Fashioned', 'Whiskey']),
    mc('q-getraenke-110', 'getraenke', 2,
        'Welches deutsche Bier-Typ wird obergärig mit Weizenmalz gebraut?',
        ['Pils', 'Weißbier (Weizenbier)', 'Kölsch', 'Helles'], 1,
        'Weißbier (Weizen). Bayerisch. Obergärige Hefe (Saccharomyces cerevisiae var. Franziskus). Aroma: Banane, Nelke (aus Hefe-Estern).',
        ['Weißbier', 'Weizen']),
    mc('q-getraenke-111', 'getraenke', 2,
        'Woher stammt der Cocktail Mojito?',
        ['Mexiko', 'Kuba', 'Puerto Rico', 'Brasilien'], 1,
        'Kuba (Havanna). Weißer Rum, Limette, Rohrzucker, Minze, Soda. Angeblich Ernest Hemingways Lieblingsgetränk in „La Bodeguita del Medio".',
        ['Mojito', 'Kuba']),
    mc('q-getraenke-112', 'getraenke', 3,
        'Welche berühmte Weinsorte kommt aus dem Bordeaux (Rotwein-Blend)?',
        [
            'Cabernet Sauvignon + Merlot + Cabernet Franc',
            'Nur Pinot Noir',
            'Riesling',
            'Chardonnay',
        ], 0,
        'Bordeaux Rouge = klassisch Cabernet Sauvignon (linkes Ufer, Médoc) oder Merlot (rechtes Ufer, Saint-Émilion, Pomerol), plus Cabernet Franc.',
        ['Bordeaux', 'Blend']),
    mc('q-getraenke-113', 'getraenke', 2,
        'Was ist „IPA" im Bierbereich?',
        [
            'Iberisches Pils',
            'India Pale Ale (stark gehopftes obergäriges Bier)',
            'Italian Pilsner Amber',
            'Isolated Pure Ale',
        ], 1,
        'India Pale Ale — stark gehopfter Ale-Typ. Ursprünglich 19. Jh. für Export nach Indien haltbar gemacht. Craft-Beer-Symbol seit ~2000.',
        ['IPA', 'Ale']),
    mc('q-getraenke-114', 'getraenke', 2,
        'Welche Weinsorte gilt als typisch für die Mosel und Rhein-Region?',
        ['Merlot', 'Riesling', 'Chardonnay', 'Pinot Grigio'], 1,
        'Riesling. Weißwein. Mosel: karg, Schiefer, elegant. Rheingau/Pfalz: kräftiger. Trocken bis edelsüß (Trockenbeerenauslese).',
        ['Riesling', 'Mosel']),
    mc('q-getraenke-115', 'getraenke', 3,
        'Welcher schottische Whisky-Region ist bekannt für rauchige, torfige Whiskys?',
        ['Speyside', 'Highlands', 'Islay', 'Lowlands'], 2,
        'Islay (Ay-la). Insel westlich von Schottland. Distillerien: Laphroaig, Ardbeg, Lagavulin, Bowmore, Bruichladdich. Torf-Rauch prägend.',
        ['Islay', 'Torf']),
    mc('q-getraenke-116', 'getraenke', 2,
        'Aus welcher Frucht wird Gin überwiegend aromatisiert?',
        ['Apfel', 'Wacholderbeere (Juniper)', 'Orange', 'Zitrone'], 1,
        'Wacholderbeere = definierendes Aroma („juniperus"). Zusätzlich Botanicals wie Koriander, Zitrusschale, Angelika, Kardamom.',
        ['Gin', 'Wacholder']),
    mc('q-getraenke-117', 'getraenke', 4,
        'Welches spanische Getränk ist eine Sangria-Variante mit Weißwein statt Rot?',
        ['Rebujito', 'Tinto de Verano', 'Clara', 'Sangria Blanca'], 3,
        'Sangria Blanca. Weißwein, Zitrusfrüchte, Zucker, Cava/Sprudel. Klassische Sangria: Rotwein. Tinto de Verano: Rotwein + Zitronenlimo.',
        ['Sangria', 'Weiß']),
    mc('q-getraenke-118', 'getraenke', 2,
        'Wer ist der wichtigste Weinhersteller der Toskana mit dem berühmten Roten „Chianti"?',
        ['Frankreich', 'Italien', 'Spanien', 'Portugal'], 1,
        'Italien — Toskana. Chianti: v. a. aus Sangiovese-Trauben. Chianti Classico (schwarzer Hahn) hat besonders strenge Regeln.',
        ['Chianti', 'Toskana']),
    mc('q-getraenke-119', 'getraenke', 3,
        'Welcher „Aperitif" wird oft mit Prosecco und Soda zum Aperol Spritz gemischt?',
        ['Campari', 'Aperol', 'Cynar', 'Fernet-Branca'], 1,
        'Aperol. Orangenroter Bitterlikör, 11 % Vol. Verhältnis 3 Prosecco : 2 Aperol : 1 Soda. Populär als Sommergetränk in DE, IT, AT.',
        ['Aperol', 'Spritz']),
]

# KAFFEE & TEE (20)
NEW_QUESTIONS += [
    mc('q-kaffee-100', 'kaffee', 1,
        'Wie heißt ein Espresso mit heißer Milch?',
        ['Cappuccino', 'Milchkaffee', 'Latte Macchiato', 'Americano'], 2,
        'Latte Macchiato — mehr Milch, weniger Espresso, geschichtet. Cappuccino = 1/3 Espresso + 1/3 Milch + 1/3 Schaum.',
        ['Latte Macchiato', 'Espresso']),
    mc('q-kaffee-101', 'kaffee', 1,
        'Aus welchem Land stammt Espresso?',
        ['Frankreich', 'Italien', 'Türkei', 'Brasilien'], 1,
        'Italien — erste Espressomaschine von Luigi Bezzera 1901 in Mailand. „Espresso" = „ausgepresst" (unter Druck). Standardvolumen: 25 ml.',
        ['Espresso', 'Italien']),
    mc('q-kaffee-102', 'kaffee', 2,
        'Welches Land ist der weltgrößte Kaffeeproduzent?',
        ['Kolumbien', 'Vietnam', 'Brasilien', 'Äthiopien'], 2,
        'Brasilien produziert ~35–40 % des weltweiten Kaffees, gefolgt von Vietnam (~15 %). Äthiopien ist Ursprungsland von Coffea arabica.',
        ['Brasilien', 'Kaffee']),
    mc('q-kaffee-103', 'kaffee', 2,
        'Welche zwei Hauptkaffeesorten gibt es weltweit?',
        [
            'Arabica und Robusta',
            'Espresso und Filter',
            'Bohne und Instant',
            'Röstung dunkel und hell',
        ], 0,
        'Arabica (~60 %, milder, teurer) und Robusta (~40 %, bitterer, mehr Koffein). Weitere: Liberica, Excelsa (Nischen).',
        ['Arabica', 'Robusta']),
    mc('q-kaffee-104', 'kaffee', 2,
        'Aus welchem Land stammt Tee ursprünglich?',
        ['Indien', 'China', 'Japan', 'Sri Lanka'], 1,
        'China — Legende: Kaiser Shen Nung 2737 v. Chr. Erste Teekultur. Weiße, grüne, gelbe, oolong, schwarze und Pu-Erh-Tees.',
        ['Tee', 'China']),
    mc('q-kaffee-105', 'kaffee', 3,
        'Was ist ein „Flat White"?',
        [
            'Zwei Espressi mit dünner Milchschaumschicht',
            'Kaffee mit viel Wasser',
            'Kaffee mit Vanille',
            'Cold Brew',
        ], 0,
        'Flat White — Doppelter Espresso + Mikroschaum (sehr feine Milch). Ursprung Australien/Neuseeland ~1980er. Ähnlich Cappuccino, aber weniger Schaum.',
        ['Flat White', 'Australien']),
    mc('q-kaffee-106', 'kaffee', 2,
        'Welche Farbe hat Matcha-Tee?',
        ['Rot', 'Braun', 'Grün', 'Gelb'], 2,
        'Matcha — feines Pulver aus beschattetem Grüntee (Tencha). Traditionell in jap. Teezeremonie. Hoher Chlorophyll- und L-Theanin-Gehalt.',
        ['Matcha', 'Grüntee']),
    mc('q-kaffee-107', 'kaffee', 3,
        'Welche Zubereitungsmethode presst mit Kolben aus Zylinder?',
        ['Espressomaschine', 'French Press', 'Filter', 'Aeropress'], 1,
        'French Press (Presskanne, „Cafetière"). Grobmahlung. Kaffee zieht 4 min. Charakteristisch: kräftiger, öliger Kaffee.',
        ['French Press', 'Presskanne']),
    mc('q-kaffee-108', 'kaffee', 2,
        'Was ist „Cold Brew"?',
        [
            'Eiswürfel im Espresso',
            'Kaffee, 12–24 h in kaltem Wasser gezogen',
            'Kaffee-Sirup',
            'Frappé',
        ], 1,
        'Cold Brew — kalt aufgebrüht (~14 h). Wenig Bitterstoffe, süßlich, oft Konzentrat. Anders als „Iced Coffee" (heiß gebrüht, dann abgekühlt).',
        ['Cold Brew', 'Kalt']),
    mc('q-kaffee-109', 'kaffee', 2,
        'Welches Land trinkt pro Kopf am meisten Tee weltweit?',
        ['Vereinigtes Königreich', 'Türkei', 'Irland', 'China'], 1,
        'Türkei — ~3–4 kg Tee/Kopf/Jahr. Traditionell Schwarztee in tulpenförmigen Gläsern. UK: ~2 kg. China: ~1,5 kg.',
        ['Tee', 'Türkei']),
    mc('q-kaffee-110', 'kaffee', 3,
        'Welche Teesorte wird stark oxidiert und ist die häufigste im Westen?',
        ['Weißtee', 'Grüntee', 'Schwarztee', 'Oolong'], 2,
        'Schwarztee — voll oxidiert. Assam, Darjeeling, Ceylon, Keemun. Grüntee: nicht oxidiert. Oolong: halb oxidiert.',
        ['Schwarztee', 'Oxidation']),
    mc('q-kaffee-111', 'kaffee', 2,
        'Was ist ein „Doppio"?',
        ['Cappuccino mit zwei Schuss', 'Doppelter Espresso', 'Wiener Kaffee', 'Türkischer Kaffee'], 1,
        'Doppio — 50 ml aus 14 g Kaffee, 25 s Extraktion. Standard-Basis für Latte, Cappuccino in Cafés außerhalb Italiens.',
        ['Doppio', 'Espresso']),
    mc('q-kaffee-112', 'kaffee', 2,
        'Welche Kaffee-Röstung ist am bittersten und dunkelsten?',
        ['Blonde', 'Medium', 'Full City', 'Italian / French Roast'], 3,
        'Italian/French Roast — tiefdunkel, ölig glänzend, Kaffee-Bohnen bei 240 °C+ geröstet. Bitter, weniger Säure. Espresso-Röstung.',
        ['Röstung', 'Dunkel']),
    mc('q-kaffee-113', 'kaffee', 3,
        'Was ist „Kopi Luwak"?',
        [
            'Milchkaffee aus Bali',
            'Kaffee aus von Fleckenmusang ausgeschiedenen Kaffeekirschen',
            'Kaffee mit Reis',
            'Süßspeise',
        ], 1,
        'Kopi Luwak (Indonesien). Musang (Zibet) frisst Kaffeekirschen, verdauet nur Fruchtfleisch, Bohnen fermentieren im Darm. Bis 700 $/kg. Tierschutz-Kritik.',
        ['Luwak', 'Indonesien']),
    mc('q-kaffee-114', 'kaffee', 2,
        'Wie lange steht ein grüner Tee typischerweise beim Aufguss?',
        ['1–3 Minuten', '5–8 Minuten', '10 Minuten', '15 Minuten'], 0,
        'Grüntee: 70–80 °C, 1–3 min (sonst bitter durch Catechine). Schwarztee: 90–100 °C, 3–5 min. Oolong: 3–5 min.',
        ['Grüntee', 'Aufguss']),
    mc('q-kaffee-115', 'kaffee', 2,
        'Wie heißt der türkische Sattelboden-Kaffee mit Zucker gekocht?',
        ['Espresso', 'Türkischer Mokka', 'Filterkaffee', 'Cappuccino'], 1,
        'Türkischer Mokka („Türk kahvesi"). Sehr fein gemahlen, in Cezve (Kupferkännchen) mit Wasser + Zucker aufgekocht. UNESCO immaterielles Kulturerbe.',
        ['Mokka', 'Türkisch']),
    mc('q-kaffee-116', 'kaffee', 3,
        'Wer entdeckte laut Legende den Kaffee, weil seine Ziegen zappelten?',
        ['Kaldi (Äthiopien)', 'Marco Polo', 'Christoph Kolumbus', 'Vasco da Gama'], 0,
        'Kaldi, äthiopischer Ziegenhirte (~9. Jh.). Bemerkte, wie Ziegen nach Kaffeekirschen munterer wurden. Legende, nicht historisch belegt.',
        ['Kaldi', 'Legende']),
    mc('q-kaffee-117', 'kaffee', 3,
        'Welche Farbe hat der Rooibos-Tee aus Südafrika?',
        ['Grün', 'Rot / Rotbraun', 'Weiß', 'Blau'], 1,
        'Rooibos („Rotbusch") — Aspalathus linearis, nur im Cederberg-Gebiet (Südafrika). Koffeinfrei. Nussig-süßer Geschmack.',
        ['Rooibos', 'Südafrika']),
    mc('q-kaffee-118', 'kaffee', 4,
        'Wie viel Milligramm Koffein enthält eine Standard-Espresso-Tasse (30 ml) ungefähr?',
        ['~10 mg', '~65 mg', '~200 mg', '~500 mg'], 1,
        'Espresso: ~60–80 mg Koffein pro 30 ml. Filterkaffee: 80–120 mg pro 240 ml. Kaffeebohnen enthalten Koffein zur Insekten-Abwehr.',
        ['Koffein', 'Espresso']),
    mc('q-kaffee-119', 'kaffee', 2,
        'Welche Uhrzeit gilt in England traditionell als Teestunde („Afternoon Tea")?',
        ['10:00', '12:00', '~16:00', '18:00'], 2,
        '16 Uhr — Anna Duchess of Bedford (~1840) begründete Nachmittagstee. Mit Sandwiches, Scones (Clotted Cream + Marmelade) und Kuchen.',
        ['Afternoon Tea', 'England']),
]

# SÜSSES & DESSERTS (20)
NEW_QUESTIONS += [
    mc('q-suesses-100', 'suesses', 1,
        'Welches Dessert wird traditionell mit Zabaione und Kakao über Löffelbiskuit geschichtet?',
        ['Panna Cotta', 'Tiramisu', 'Cannoli', 'Gelato'], 1,
        'Tiramisu (it. „Zieh mich hoch"). Mascarpone, Espresso, Löffelbiskuit, Marsala, Kakao. Angeblich ~1970 in Treviso entstanden.',
        ['Tiramisu', 'Italien']),
    mc('q-suesses-101', 'suesses', 1,
        'Aus welchem Land stammt die Sachertorte?',
        ['Deutschland', 'Schweiz', 'Österreich', 'Italien'], 2,
        'Österreich — Franz Sacher (16 J.) 1832 in Wien für Fürst Metternich. Hotel Sacher & Konditorei Demel stritten Jahre um „Original".',
        ['Sacher', 'Wien']),
    mc('q-suesses-102', 'suesses', 2,
        'Welche Farbe hat traditionelles Marzipan im Rohzustand?',
        ['Rot', 'Elfenbein / Beige', 'Grün', 'Braun'], 1,
        'Marzipan: gemahlene Mandeln + Zucker (mind. 63 % Mandelanteil bei „Königsberger"). Farbe: helles Cremeweiß-Beige. Lübecker Marzipan seit ~1806.',
        ['Marzipan', 'Lübeck']),
    mc('q-suesses-103', 'suesses', 2,
        'Was ist eine „Crème brûlée"?',
        [
            'Sahnesuppe',
            'Cremiges Dessert mit Karamellkruste',
            'Eiscreme',
            'Torte',
        ], 1,
        'Crème brûlée („gebrannte Creme") — Vanillecreme aus Sahne+Ei, mit knuspriger Zuckerkruste (mit Brenner karamellisiert). Frankreich, ~17. Jh.',
        ['Brûlée', 'Frankreich']),
    mc('q-suesses-104', 'suesses', 2,
        'Welche Farbe haben die klassischen Pariser „Macarons" oft?',
        ['Pastell (viele Farben)', 'Nur Weiß', 'Nur Braun', 'Nur Rosa'], 0,
        'Macarons — kleine Mandelbaisers mit Ganache-Füllung. Klassische Farben: rosa (Rose), grün (Pistazie), gelb (Zitrone), lila (Cassis). Ladurée & Pierre Hermé prägten.',
        ['Macarons', 'Paris']),
    mc('q-suesses-105', 'suesses', 3,
        'Welcher Kuchen aus Schwarzwald hat Kirsch, Sahne und Schokoraspel?',
        ['Sachertorte', 'Frankfurter Kranz', 'Schwarzwälder Kirschtorte', 'Prinzregententorte'], 2,
        'Schwarzwälder Kirschtorte — Kakao-Biskuit, Kirschwasser, Kirschen, Sahne. Erst nach dem 2. Weltkrieg populär (frühere Erwähnung 1934).',
        ['Kirschtorte', 'Schwarzwald']),
    mc('q-suesses-106', 'suesses', 2,
        'Aus welchem Land stammt Baklava?',
        ['Marokko', 'Türkei / Osmanisches Reich', 'Italien', 'Spanien'], 1,
        'Baklava — Filoteig, Nüsse (Pistazien/Walnüsse), Sirup/Honig. Osmanisch. Beansprucht auch von Griechenland und Levante. Türkei liefert die meisten Varianten.',
        ['Baklava', 'Türkei']),
    mc('q-suesses-107', 'suesses', 2,
        'Was ist „Mochi"?',
        [
            'Ein Reisgetränk',
            'Klebriger Reiskuchen (Japan)',
            'Chinesischer Fisch',
            'Wintergemüse',
        ], 1,
        'Mochi — aus gestampftem Klebreis (Mochigome). Traditionell zum jap. Neujahr (Kagami mochi). Modern: Mochi-Eis, Daifuku (mit Bohnenpaste).',
        ['Mochi', 'Japan']),
    mc('q-suesses-108', 'suesses', 3,
        'Welches Land ist der größte Schokoladenkonsument pro Kopf?',
        ['Deutschland', 'Schweiz', 'Belgien', 'Vereinigtes Königreich'], 1,
        'Schweiz — ~9–10 kg Schokolade/Kopf/Jahr. Deutschland ~9 kg. Marken: Lindt, Toblerone, Cailler. Erfinder Milchschokolade: Daniel Peter 1875.',
        ['Schokolade', 'Schweiz']),
    mc('q-suesses-109', 'suesses', 2,
        'Aus welcher Frucht wird Marzipan hergestellt?',
        ['Mandel', 'Walnuss', 'Erdnuss', 'Kokos'], 0,
        'Süße Mandeln + Zucker (+ etwas bittere Mandel als Aromageber). Lübecker Marzipan: mind. 70 % Rohmasse. Königsberger: mind. 63 %.',
        ['Mandel', 'Marzipan']),
    mc('q-suesses-110', 'suesses', 2,
        'Welche italienische Region ist berühmt für Cannoli mit Ricotta-Füllung?',
        ['Toskana', 'Sizilien', 'Piemont', 'Kampanien'], 1,
        'Cannoli siciliani — knusprige Teigrolle, gefüllt mit gesüßtem Ricotta, oft mit kandierten Früchten oder Pistazien.',
        ['Cannoli', 'Sizilien']),
    mc('q-suesses-111', 'suesses', 3,
        'Welche Farbe hat der klassische Wiener „Kaiserschmarrn"?',
        ['Schwarz', 'Golden-braun', 'Grün', 'Rosa'], 1,
        'Kaiserschmarrn — dicker Pfannkuchen, zerteilt, mit Puderzucker. Legende: Franz Josephs Küchenchef. Serviert mit Zwetschgenröster oder Apfelmus.',
        ['Kaiserschmarrn', 'Wien']),
    mc('q-suesses-112', 'suesses', 2,
        'Was ist der Hauptbestandteil von Mochi und Klebreiskugeln?',
        ['Weizen', 'Reis', 'Mais', 'Kartoffel'], 1,
        'Klebreis (Mochigome, Oryza sativa var. glutinosa). Enthält fast nur Amylopektin (weniger Amylose) → klebrige, elastische Textur.',
        ['Klebreis', 'Mochi']),
    mc('q-suesses-113', 'suesses', 3,
        'Wer erfand die Milchschokolade 1875?',
        ['Rudolphe Lindt', 'Daniel Peter', 'François-Louis Cailler', 'Henri Nestlé'], 1,
        'Daniel Peter (Schweiz) — mit Kondensmilch von Henri Nestlé. Vorher nur Bitterschokolade. Rudolphe Lindt erfand 1879 das Conchieren (samtige Textur).',
        ['Milchschokolade', 'Peter']),
    mc('q-suesses-114', 'suesses', 2,
        'Aus welchem Land stammt der Cheesecake nach New Yorker Art?',
        ['Deutschland', 'USA', 'Griechenland (Ursprung)', 'Italien'], 1,
        'New York Cheesecake (USA, 20. Jh.) mit Frischkäse (Cream Cheese, seit 1872). Historischer Ursprung des Käsekuchens: antikes Griechenland.',
        ['Cheesecake', 'NYC']),
    mc('q-suesses-115', 'suesses', 2,
        'Welche Süßspeise wird in Frankreich mit Karamell-Sauce und Vanilleeis („Île flottante") kombiniert?',
        [
            'Schwimmende Insel: Eischnee auf Vanillesoße',
            'Crêpe',
            'Éclair',
            'Millefeuille',
        ], 0,
        'Île flottante („schwimmende Insel") — Eischnee-Wolke auf crème anglaise, mit Karamellfaden. Nicht zu verwechseln mit Œufs à la neige (klein).',
        ['Île flottante', 'Frankreich']),
    mc('q-suesses-116', 'suesses', 3,
        'Welche Kaffeebohne ist wichtige Zutat für „Tiramisu"?',
        ['Filterkaffee', 'Espresso', 'Instantkaffee', 'Cold Brew'], 1,
        'Espresso — starke, konzentrierte Basis. Getränkt in die Löffelbiskuits (Savoiardi). Ggf. mit Marsala oder Amaretto.',
        ['Tiramisu', 'Espresso']),
    mc('q-suesses-117', 'suesses', 2,
        'Was ist eine „Praline"?',
        [
            'Kleines Süßgebäck aus Frankreich/Belgien mit gefüllter Schokolade',
            'Zuckerbonbon',
            'Marmelade',
            'Fruchtiges Sorbet',
        ], 0,
        'Praline — Schokoladenkugel/-tafel mit Füllung (Nougat, Ganache, Alkohol). Entstand im 17. Jh. für Marschall du Plessis-Praslin.',
        ['Praline', 'Belgien']),
    mc('q-suesses-118', 'suesses', 4,
        'Wer erfand 1857 den Baumkuchen-Klassiker im Prinzip als königliche Konditorei? (Herkunft?)',
        ['Frankreich', 'Deutschland', 'Salzwedel (Altmark)', 'Wien'], 2,
        'Salzwedeler Baumkuchen. Konditor Andreas Schernikow, 1807. Konditorei Salzwedel wurde 1841 „Hoflieferant". Baumkuchen: Schicht für Schicht am Spieß gebacken.',
        ['Baumkuchen', 'Salzwedel']),
    mc('q-suesses-119', 'suesses', 2,
        'Welche Süßspeise wird als „Königin der Torten" bezeichnet und stammt aus Wien?',
        ['Linzer Torte', 'Sachertorte', 'Punschkrapferl', 'Esterházy'], 1,
        'Sachertorte — 1832 von Franz Sacher. Schokoladenbiskuit + dünne Marillenmarmelade + Schokoglasur. „Original" nur im Hotel Sacher.',
        ['Sacher', 'Wien']),
]


def main() -> int:
    with QUESTIONS_PATH.open('r', encoding='utf-8') as f:
        existing = json.load(f)
    existing_ids = {q['id'] for q in existing}
    to_add = [q for q in NEW_QUESTIONS if q['id'] not in existing_ids]
    if not to_add:
        print('Keine neuen Fragen.')
        return 0
    for q in to_add:
        assert len(q['options']) == 4, q['id']
        assert 0 <= q['correctIndex'] < 4, q['id']
    merged = existing + to_add
    with QUESTIONS_PATH.open('w', encoding='utf-8') as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
        f.write('\n')
    from collections import Counter
    print(f'✓ {len(to_add)} neue Fragen ergänzt (jetzt {len(merged)} insgesamt).')
    for t, c in sorted(Counter(q['topic'] for q in to_add).items()):
        print(f'  + {t:<14} {c}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
