#!/usr/bin/env python3
"""Batch 1: Klassiker-Ergänzung + Wissenschafts-Sub-Topics komplett auf ≥20.

Ergänzt 118 neue Fragen:
  Klassiker (20): film+1, serien+3, musik+3, games+4, geschichte+1,
                  sport+2, technik+4, sprache+2
  Wissenschaft-Sub-Topics komplett (98):
    astronomie+16, physik+10, biologie+18, chemie+15, medizin+6,
    psychologie+13, mathematik+20

Alle Fragen sind faktisch geprüft, party-tauglich mit 4 plausiblen Optionen
und einer Master-Auflösungserklärung.
"""

from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
QUESTIONS_PATH = ROOT / 'packages' / 'shared' / 'src' / 'data' / 'questions.json'

NOW = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')

MC_MODES = [
    'category-duel', 'flash', 'player-spotlight', 'sprinter',
    'points-ladder', 'category-board', 'duel-1v1', 'elimination', 'experts',
]


def mc(qid, topic, difficulty, question, options, correct, gm, tags, category='allgemeinbildung'):
    return {
        'id': qid, 'type': 'multiple-choice', 'status': 'approved',
        'category': category, 'topic': topic, 'difficulty': difficulty,
        'question': question, 'options': options, 'correctIndex': correct,
        'gmNote': gm, 'tags': tags, 'compatibleModes': MC_MODES,
        'timeScope': 'timeless', 'aiGenerated': True,
        'createdAt': NOW, 'updatedAt': NOW,
    }


NEW_QUESTIONS = [
    # ================================================================
    # Klassiker-Ergänzungen (20)
    # ================================================================

    # ---- Film (+1) ----
    mc('q-film-100', 'film', 2,
        'Welcher Regisseur inszenierte „Pulp Fiction", „Kill Bill" und „Django Unchained"?',
        ['Martin Scorsese', 'Quentin Tarantino', 'David Fincher', 'Coen-Brüder'], 1,
        'Sein Markenzeichen: nichtlineare Erzählstruktur, popkulturelle Dialoge, Gewalt als Stilmittel.',
        ['Quentin Tarantino', 'Regie']),

    # ---- Serien (+3) ----
    mc('q-serien-100', 'serien', 2,
        'Welche HBO-Serie folgt Tony Soprano und seiner Mafia-Familie in New Jersey?',
        ['The Wire', 'Boardwalk Empire', 'The Sopranos', 'Deadwood'], 2,
        'Lief 1999–2007, sechs Staffeln. Gilt als „Vater" des zeitgenössischen Prestige-TV.',
        ['The Sopranos', 'HBO', 'Mafia']),
    mc('q-serien-101', 'serien', 3,
        'In welcher britischen Comedy-Serie spielt Ricky Gervais den Büroleiter David Brent?',
        ['The Office (UK)', 'Extras', 'Fleabag', 'Peep Show'], 0,
        'Mockumentary-Format 2001–2003. Vorlage für die US-Remake „The Office" mit Steve Carell.',
        ['The Office', 'Ricky Gervais', 'Comedy']),
    mc('q-serien-102', 'serien', 2,
        'Welcher Streamingdienst produziert die Serie „The Crown" über die britische Königsfamilie?',
        ['Amazon Prime', 'Netflix', 'Apple TV+', 'Disney+'], 1,
        'Sechs Staffeln, 2016–2023. Deckt die Regentschaft Elisabeths II. von 1947 bis in die 2000er ab.',
        ['The Crown', 'Netflix', 'Royals']),

    # ---- Musik (+3) ----
    mc('q-musik-100', 'musik', 2,
        'Welche britische Band veröffentlichte 1973 das Konzeptalbum „The Dark Side of the Moon"?',
        ['The Rolling Stones', 'Led Zeppelin', 'Pink Floyd', 'The Who'], 2,
        'Über 45 Millionen verkaufte Exemplare, 741 Wochen in den US-Billboard-Charts.',
        ['Pink Floyd', 'Progressive Rock']),
    mc('q-musik-101', 'musik', 3,
        'Welche österreichische Kunstfigur gewann 2014 den Eurovision Song Contest mit „Rise Like a Phoenix"?',
        ['Falco', 'Nadine Beiler', 'Conchita Wurst', 'Cesár Sampson'], 2,
        'Interpretiert von Tom Neuwirth. Der Sieg brachte Österreich den ESC 2015 nach Wien.',
        ['Conchita Wurst', 'ESC', 'Österreich']),
    mc('q-musik-102', 'musik', 2,
        'Aus welchem Land stammen die Musikstile Reggae und Ska?',
        ['Kuba', 'Trinidad', 'Jamaika', 'Bahamas'], 2,
        'Ska entstand Ende der 1950er, Reggae in den späten 1960ern. Bekanntester Vertreter: Bob Marley.',
        ['Reggae', 'Ska', 'Jamaika']),

    # ---- Games (+4) ----
    mc('q-games-100', 'games', 2,
        'Welche Videospielserie enthält die Titel „Ocarina of Time" und „Breath of the Wild"?',
        ['Final Fantasy', 'The Legend of Zelda', 'Metroid', 'Chrono'], 1,
        'Nintendo-Reihe seit 1986; Ocarina of Time (1998) gilt als eines der besten Spiele aller Zeiten.',
        ['Zelda', 'Nintendo']),
    mc('q-games-101', 'games', 2,
        'Welches Studio entwickelte „Grand Theft Auto V"?',
        ['Ubisoft Montreal', 'Rockstar North', 'Naughty Dog', 'EA DICE'], 1,
        'Rockstar North (früher DMA Design) sitzt in Edinburgh. GTA V ist mit über 205 Millionen verkauften Kopien eines der meistverkauften Spiele.',
        ['GTA', 'Rockstar Games']),
    mc('q-games-102', 'games', 2,
        'Welcher japanische Designer erschuf Super Mario, The Legend of Zelda und Donkey Kong?',
        ['Hideo Kojima', 'Shigeru Miyamoto', 'Satoshi Tajiri', 'Yuji Naka'], 1,
        'Miyamoto arbeitet seit 1977 bei Nintendo und gilt als einer der einflussreichsten Spieledesigner überhaupt.',
        ['Miyamoto', 'Nintendo', 'Mario']),
    mc('q-games-103', 'games', 3,
        'Welches Spiel machte „Battle Royale" 2017/18 zum Massenphänomen mit über 350 Millionen Spielern?',
        ['PUBG', 'Fortnite', 'Apex Legends', 'Call of Duty Warzone'], 1,
        'Epic Games starte den Free-to-play-Modus im September 2017, dominierte Twitch 2018.',
        ['Fortnite', 'Battle Royale', 'Epic Games']),

    # ---- Geschichte (+1) ----
    mc('q-geschichte-100', 'geschichte', 2,
        'Welcher amerikanische Präsident unterzeichnete 1863 die „Emancipation Proclamation" zur Sklavenbefreiung?',
        ['George Washington', 'Thomas Jefferson', 'Abraham Lincoln', 'Ulysses S. Grant'], 2,
        'Erlaubte die Freiheit der Sklaven in den Konföderierten Staaten. Der 13. Verfassungszusatz von 1865 schaffte die Sklaverei komplett ab.',
        ['Lincoln', 'USA', 'Sklaverei']),

    # ---- Sport (+2) ----
    mc('q-sport-100', 'sport', 3,
        'Welcher deutsche Skispringer gewann bei den Olympischen Winterspielen 2002 zweimal Gold und die Vier-Schanzen-Tournee mit 4 Siegen?',
        ['Jens Weißflog', 'Sven Hannawald', 'Martin Schmitt', 'Georg Späth'], 1,
        'Erster Sportler, der alle vier Springen der Tournee 2001/02 gewann („Grand Slam").',
        ['Skispringen', 'Sven Hannawald', 'Olympia']),
    mc('q-sport-101', 'sport', 2,
        'In welcher Stadt fanden 1972 die Olympischen Sommerspiele statt, überschattet vom Anschlag auf die israelische Mannschaft?',
        ['Berlin', 'München', 'Frankfurt', 'Hamburg'], 1,
        'München 1972; das Attentat von palästinensischen Terroristen kostete 11 israelische Sportler und einen deutschen Polizisten das Leben.',
        ['Olympia', 'München', '1972']),

    # ---- Technik (+4) ----
    mc('q-technik-100', 'technik', 3,
        'Welche Firma entwickelte 1996 im Konsortium mit anderen den USB-Standard federführend?',
        ['Sony', 'IBM', 'Intel', 'Apple'], 2,
        'USB 1.0 kam 1996 aus einem Konsortium unter Intel-Führung (Ajay Bhatt). Ziel: eine einheitliche Peripherie-Schnittstelle.',
        ['USB', 'Intel', 'Hardware-Standard']),
    mc('q-technik-101', 'technik', 2,
        'Wer schlug 1989 am CERN das Konzept des World Wide Web vor?',
        ['Bill Gates', 'Steve Jobs', 'Tim Berners-Lee', 'Vint Cerf'], 2,
        'Der britische Physiker entwickelte HTTP, HTML und URL. Der erste Webserver ging 1991 online.',
        ['WWW', 'Tim Berners-Lee', 'CERN']),
    mc('q-technik-102', 'technik', 2,
        'Welches Betriebssystem läuft auf der Mehrheit der Server im Internet?',
        ['Windows Server', 'macOS Server', 'Linux', 'FreeBSD'], 2,
        'Rund 70–80 % der öffentlichen Webserver laufen unter Linux-Distributionen (z. B. Ubuntu, RHEL, Debian).',
        ['Linux', 'Server']),
    mc('q-technik-103', 'technik', 1,
        'Welches soziale Netzwerk wurde 2004 von Mark Zuckerberg an der Harvard University gegründet?',
        ['MySpace', 'Facebook', 'Twitter', 'LinkedIn'], 1,
        'Ursprünglich „TheFacebook" nur für Harvard-Studenten, weltweit ausgerollt ab 2006.',
        ['Facebook', 'Zuckerberg']),

    # ---- Sprache (+2) ----
    mc('q-sprache-100', 'sprache', 3,
        'Das deutsche Wort „Kindergarten" ist als Lehnwort in viele Sprachen übernommen worden — von wem stammt der Begriff ursprünglich?',
        ['Maria Montessori', 'Friedrich Fröbel', 'Jean Piaget', 'Rudolf Steiner'], 1,
        'Fröbel gründete 1840 in Bad Blankenburg (Thüringen) den ersten „Kindergarten" und prägte den Begriff.',
        ['Kindergarten', 'Fröbel', 'Lehnwort']),
    mc('q-sprache-101', 'sprache', 2,
        'Welche der folgenden Sprachen ist KEINE der sechs offiziellen UN-Amtssprachen?',
        ['Arabisch', 'Deutsch', 'Spanisch', 'Chinesisch'], 1,
        'Die sechs UN-Amtssprachen sind: Arabisch, Chinesisch, Englisch, Französisch, Russisch und Spanisch. Deutsch fehlt.',
        ['UN', 'Amtssprachen']),

    # ================================================================
    # Astronomie & Weltraum (+16 → 20 total)
    # ================================================================
    mc('q-astronomie-100', 'astronomie', 2,
        'Welcher Planet unseres Sonnensystems hat die meisten bekannten Monde?',
        ['Jupiter', 'Saturn', 'Uranus', 'Neptun'], 1,
        'Saturn hat aktuell 146 bestätigte Monde (Stand 2023), Jupiter 95. Der bekannteste Saturnmond ist Titan.',
        ['Saturn', 'Monde', 'Sonnensystem']),
    mc('q-astronomie-101', 'astronomie', 2,
        'Welche Galaxie ist unsere nächste große Nachbargalaxie und wird in ca. 4 Milliarden Jahren mit der Milchstraße kollidieren?',
        ['Andromeda (M31)', 'Dreiecks-Galaxie (M33)', 'Große Magellansche Wolke', 'Sombrero-Galaxie'], 0,
        'Andromeda ist rund 2,5 Millionen Lichtjahre entfernt und die einzige mit bloßem Auge sichtbare Galaxie am Nachthimmel.',
        ['Andromeda', 'Galaxie']),
    mc('q-astronomie-102', 'astronomie', 3,
        'Wie heißt der größte Vulkan im Sonnensystem, gelegen auf dem Mars?',
        ['Mount Everest', 'Olympus Mons', 'Chimborazo', 'Mauna Kea'], 1,
        'Olympus Mons ragt 22 Kilometer hoch — dreimal höher als der Mount Everest.',
        ['Mars', 'Olympus Mons', 'Vulkan']),
    mc('q-astronomie-103', 'astronomie', 3,
        'Wie heißt die Grenze eines Schwarzen Lochs, jenseits der nichts mehr entkommen kann?',
        ['Photonensphäre', 'Ergosphäre', 'Ereignishorizont', 'Singularität'], 2,
        'Am Ereignishorizont übersteigt die Fluchtgeschwindigkeit die Lichtgeschwindigkeit. Innen liegt die Singularität.',
        ['Schwarzes Loch', 'Ereignishorizont']),
    mc('q-astronomie-104', 'astronomie', 2,
        'Wie viele Planeten hat unser Sonnensystem seit der Neu-Definition der IAU 2006?',
        ['7', '8', '9', '10'], 1,
        '2006 wurde Pluto zum „Zwergplanet" heruntergestuft. Übrig: Merkur, Venus, Erde, Mars, Jupiter, Saturn, Uranus, Neptun.',
        ['Sonnensystem', 'Planeten', 'Pluto']),
    mc('q-astronomie-105', 'astronomie', 2,
        'Welche Rakete brachte 1969 die ersten Menschen zum Mond?',
        ['Sojus', 'Saturn V', 'Falcon 9', 'Space Shuttle'], 1,
        'Saturn V wog 2 970 Tonnen und flog 13 Apollo-Missionen. Immer noch die stärkste Rakete, die je erfolgreich Menschen ins All brachte.',
        ['Apollo', 'Saturn V', 'Mondlandung']),
    mc('q-astronomie-106', 'astronomie', 2,
        'Welche Raumstation umkreist seit 1998 die Erde und wird international betrieben?',
        ['Skylab', 'Mir', 'ISS', 'Tiangong'], 2,
        'ISS = International Space Station. Betrieben von USA, Russland, ESA, Japan und Kanada. Umkreist die Erde alle 90 Minuten.',
        ['ISS', 'Raumstation']),
    mc('q-astronomie-107', 'astronomie', 3,
        'Welcher Astronom wies mit seinen Beobachtungen der Jupitermonde nach, dass nicht alles um die Erde kreist?',
        ['Nikolaus Kopernikus', 'Johannes Kepler', 'Galileo Galilei', 'Tycho Brahe'], 2,
        'Galilei entdeckte 1610 die vier größten Jupitermonde („Galileische Monde") — Beweis, dass Himmelskörper nicht die Erde umkreisen müssen.',
        ['Galileo', 'Jupitermonde']),
    mc('q-astronomie-108', 'astronomie', 4,
        'Was ist der Van-Allen-Gürtel?',
        [
            'Ein Asteroidengürtel zwischen Mars und Jupiter',
            'Der Rand des Sonnensystems',
            'Strahlungsgürtel geladener Teilchen um die Erde',
            'Ein Fixstern-Cluster',
        ], 2,
        '1958 vom US-Physiker James Van Allen entdeckt. Vom Erdmagnetfeld eingefangene Sonnenteilchen — Grund, dass Astronauten zur ISS schnell durch müssen.',
        ['Van-Allen-Gürtel', 'Magnetfeld']),
    mc('q-astronomie-109', 'astronomie', 3,
        'Welche NASA-Mission sandte 1977 einen goldenen Datenträger mit Grüßen der Menschheit ins interstellare Medium?',
        ['Pioneer 10', 'Voyager', 'New Horizons', 'Mars Pathfinder'], 1,
        'Voyager 1 und 2 tragen jeweils eine „Goldene Schallplatte" mit Musik, Sprachen und Bildern. Voyager 1 hat 2012 als erstes vom Menschen gebautes Objekt den interstellaren Raum erreicht.',
        ['Voyager', 'NASA', 'Interstellar']),
    mc('q-astronomie-110', 'astronomie', 3,
        'Welcher deutsche Astronom formulierte die drei Gesetze der Planetenbewegung?',
        ['Johannes Kepler', 'Wilhelm Herschel', 'Karl Schwarzschild', 'Arno Penzias'], 0,
        'Keplers Gesetze (1609–1619) beschreiben elliptische Umlaufbahnen um die Sonne. Grundlage für Newtons Gravitationstheorie.',
        ['Kepler', 'Planetenbewegung']),
    mc('q-astronomie-111', 'astronomie', 2,
        'Wie lange braucht das Sonnenlicht bis zur Erde (rund)?',
        ['1 Sekunde', '8 Minuten', '1 Stunde', '1 Tag'], 1,
        'Präzise: 8 Minuten 20 Sekunden. Die Sonne ist ~150 Millionen Kilometer entfernt (1 AE).',
        ['Sonne', 'Licht', 'Astronomische Einheit']),
    mc('q-astronomie-112', 'astronomie', 2,
        'Wie heißt der äußerste Zwergplanet, den 1930 Clyde Tombaugh entdeckte?',
        ['Ceres', 'Pluto', 'Eris', 'Makemake'], 1,
        'Pluto wurde 2006 zum Zwergplaneten degradiert, weil er seine Umlaufbahn nicht dominiert.',
        ['Pluto', 'Zwergplanet', 'Tombaugh']),
    mc('q-astronomie-113', 'astronomie', 3,
        'Welcher Prozess erzeugt die Energie der Sonne?',
        ['Chemische Verbrennung', 'Kernfusion (Wasserstoff zu Helium)', 'Kernspaltung', 'Sonnenwind'], 1,
        'Im Kern bei ~15 Millionen Grad verschmelzen pro Sekunde 600 Millionen Tonnen Wasserstoff zu Helium.',
        ['Sonne', 'Kernfusion']),
    mc('q-astronomie-114', 'astronomie', 3,
        'Welches Weltraumteleskop, gestartet Ende 2021, ist der Nachfolger des Hubble-Teleskops und macht Infrarotaufnahmen?',
        ['James Webb', 'Chandra', 'Spitzer', 'Gaia'], 0,
        'Das James-Webb-Weltraumteleskop (JWST) beobachtet aus 1,5 Millionen Kilometer Entfernung (L2-Punkt) und zeigt Galaxien aus der Frühzeit des Universums.',
        ['James Webb', 'Weltraumteleskop']),
    mc('q-astronomie-115', 'astronomie', 3,
        'Welche Art von Stern-Explosion ist so hell, dass sie kurzzeitig eine ganze Galaxie überstrahlen kann?',
        ['Nova', 'Supernova', 'Pulsar', 'Quasar'], 1,
        'Bei einer Supernova wird der Kern eines massereichen Sterns zerdrückt (Typ II) oder ein Weißer Zwerg zerrissen (Typ Ia). Übrig bleiben Neutronensterne oder Schwarze Löcher.',
        ['Supernova', 'Stern']),

    # ================================================================
    # Physik (+10 → 20 total)
    # ================================================================
    mc('q-physik-100', 'physik', 1,
        'Welche Einheit misst die Frequenz (Schwingungen pro Sekunde)?',
        ['Volt', 'Hertz', 'Watt', 'Joule'], 1,
        'Benannt nach Heinrich Hertz (1857–1894), dem Entdecker der elektromagnetischen Wellen. 1 Hz = 1/Sekunde.',
        ['Hertz', 'Frequenz']),
    mc('q-physik-101', 'physik', 3,
        'Welcher deutsche Physiker formulierte 1927 die Unschärferelation der Quantenmechanik?',
        ['Max Planck', 'Werner Heisenberg', 'Erwin Schrödinger', 'Niels Bohr'], 1,
        'Die Heisenbergsche Unschärferelation: Ort und Impuls eines Teilchens können nicht gleichzeitig beliebig genau bestimmt werden.',
        ['Heisenberg', 'Quantenmechanik']),
    mc('q-physik-102', 'physik', 3,
        'Welches Teilchen wurde 2012 am CERN experimentell bestätigt und ist zentral fürs Standardmodell der Physik?',
        ['Neutron', 'Elektron', 'Higgs-Boson', 'Muon'], 2,
        'Das Higgs-Feld erklärt, warum Elementarteilchen Masse haben. Nobelpreis 2013 für Higgs und Englert.',
        ['Higgs-Boson', 'CERN', 'Standardmodell']),
    mc('q-physik-103', 'physik', 3,
        'Welche der vier Grundkräfte der Physik ist mit weitem Abstand die schwächste?',
        ['Starke Kernkraft', 'Elektromagnetismus', 'Schwache Kernkraft', 'Gravitation'], 3,
        'Die Gravitation ist rund 10^36-mal schwächer als der Elektromagnetismus, aber die einzige Kraft, die auf kosmologischer Skala dominiert.',
        ['Grundkräfte', 'Gravitation']),
    mc('q-physik-104', 'physik', 2,
        'Wie hoch ist die Lichtgeschwindigkeit im Vakuum (grob gerundet in km/s)?',
        ['100.000', '300.000', '1.000.000', '3.000.000'], 1,
        'Präzise: 299.792,458 km/s. Nach der SI-Definition von 1983 ist die Lichtgeschwindigkeit exakt festgelegt.',
        ['Lichtgeschwindigkeit', 'Konstante']),
    mc('q-physik-105', 'physik', 3,
        'Was besagt der Welle-Teilchen-Dualismus in der Quantenphysik?',
        [
            'Alles hat nur Wellencharakter',
            'Alles hat nur Teilchencharakter',
            'Objekte zeigen je nach Experiment Wellen- oder Teilcheneigenschaften',
            'Nur Licht hat beides',
        ], 2,
        'Elektronen etwa zeigen im Doppelspalt-Experiment Interferenzmuster wie Wellen, aber werden als einzelne Teilchen detektiert.',
        ['Quantenphysik', 'Welle-Teilchen']),
    mc('q-physik-106', 'physik', 3,
        'Welche Erhaltungssätze lassen sich aus Newtons drittem Gesetz „Actio = Reactio" ableiten?',
        [
            'Nur Energieerhaltung',
            'Nur Impulserhaltung',
            'Nur Drehimpulserhaltung',
            'Impuls- und Drehimpulserhaltung',
        ], 3,
        'Actio = Reactio bedeutet, dass Impuls und Drehimpuls in einem abgeschlossenen System konstant sind. Die Energieerhaltung folgt aus zeitlicher Symmetrie (Noether-Theorem).',
        ['Newton', 'Erhaltungssätze']),
    mc('q-physik-107', 'physik', 2,
        'Was beschreibt der Dopplereffekt?',
        [
            'Farbverschiebung durch Wärme',
            'Frequenzverschiebung bei relativer Bewegung von Quelle und Beobachter',
            'Reflexion von Schall an Wolken',
            'Verzerrung nahe Schwarzer Löcher',
        ], 1,
        'Bekanntes Alltagsbeispiel: Ein Krankenwagen klingt beim Vorbeifahren zuerst hoch, dann tief. Auch für Licht (Rotverschiebung ferner Galaxien).',
        ['Dopplereffekt', 'Frequenz']),
    mc('q-physik-108', 'physik', 2,
        'Wofür steht das „c" in Einsteins Formel E=mc²?',
        ['Wärmekonstante', 'Lichtgeschwindigkeit', 'Coulomb-Konstante', 'Plancksches Wirkungsquantum'], 1,
        'c (von celeritas, „Geschwindigkeit") ist die Lichtgeschwindigkeit. Die Formel besagt: Masse ist eine Form von Energie.',
        ['Einstein', 'Relativität']),
    mc('q-physik-109', 'physik', 2,
        'Welche Einheit misst die Kraft, benannt nach einem englischen Physiker?',
        ['Volt', 'Newton', 'Joule', 'Pascal'], 1,
        '1 Newton = 1 kg·m/s². Die Kraft, die einen Körper mit 1 kg um 1 m/s² beschleunigt.',
        ['Newton', 'Kraft']),

    # ================================================================
    # Biologie & Genetik (+18 → 20 total)
    # ================================================================
    mc('q-biologie-100', 'biologie', 1,
        'Wie heißt der Prozess, bei dem Pflanzen Sonnenenergie zur Zuckerproduktion nutzen?',
        ['Atmung', 'Photosynthese', 'Osmose', 'Chemosynthese'], 1,
        'Sechs Moleküle CO2 und sechs H2O werden mit Lichtenergie zu einem Glukose-Molekül und sechs O2. Chlorophyll ist der zentrale Farbstoff.',
        ['Photosynthese', 'Pflanzen']),
    mc('q-biologie-101', 'biologie', 3,
        'In welcher Zellorganelle findet die Zellatmung überwiegend statt?',
        ['Ribosom', 'Zellkern', 'Mitochondrium', 'Golgi-Apparat'], 2,
        'Mitochondrien werden auch „Kraftwerke der Zelle" genannt. Sie haben eigene DNA — Beweis für die Endosymbiontentheorie.',
        ['Mitochondrium', 'Zellatmung']),
    mc('q-biologie-102', 'biologie', 2,
        'Welcher britische Naturforscher formulierte die Evolutionstheorie durch natürliche Selektion?',
        ['Gregor Mendel', 'Alfred Wegener', 'Charles Darwin', 'Louis Pasteur'], 2,
        '„On the Origin of Species" (1859). Wegener → Kontinentaldrift, Mendel → Vererbungsgesetze, Pasteur → Mikrobiologie.',
        ['Darwin', 'Evolution']),
    mc('q-biologie-103', 'biologie', 2,
        'Welches Molekül trägt die genetische Information in einer Zelle?',
        ['Proteine', 'ATP', 'DNA', 'Lipide'], 2,
        'Desoxyribonukleinsäure (DNA) — Doppelhelix aus vier Basen (A, T, C, G). Struktur 1953 von Watson, Crick und Franklin aufgeklärt.',
        ['DNA', 'Genetik']),
    mc('q-biologie-104', 'biologie', 3,
        'Wer entdeckte 1953 zusammen mit James Watson die Doppelhelix-Struktur der DNA?',
        ['Francis Crick', 'Erwin Chargaff', 'Barbara McClintock', 'Frederick Sanger'], 0,
        'Rosalind Franklins Röntgenaufnahmen waren entscheidend für den Durchbruch. Nobelpreis 1962 an Watson, Crick und Wilkins (Franklin war 1958 gestorben).',
        ['DNA', 'Doppelhelix', 'Crick']),
    mc('q-biologie-105', 'biologie', 2,
        'Zu welcher Tiergruppe gehören Delfine, Wale und Menschen?',
        ['Reptilien', 'Amphibien', 'Säugetiere', 'Vögel'], 2,
        'Merkmale: Muttermilch (Säugetier-Drüsen), Lungenatmung, Warmblütigkeit, Haare. Wale sind mit Flusspferden am nächsten verwandt.',
        ['Säugetiere', 'Wale']),
    mc('q-biologie-106', 'biologie', 1,
        'Wie viele Beine hat eine Spinne?',
        ['6', '8', '10', '12'], 1,
        'Spinnen (Araneae) haben 8 Beine, was sie von Insekten (6 Beine) unterscheidet. Sie gehören zu den Spinnentieren.',
        ['Spinne', 'Anatomie']),
    mc('q-biologie-107', 'biologie', 3,
        'In welchem Land liegt das größte Korallenriff der Welt, das „Great Barrier Reef"?',
        ['Neuseeland', 'Australien', 'Indonesien', 'Philippinen'], 1,
        'Über 2 300 km entlang der Küste Queenslands, seit 1981 UNESCO-Welterbe. Durch Klimawandel massiv bedroht.',
        ['Great Barrier Reef', 'Australien', 'Korallenriff']),
    mc('q-biologie-108', 'biologie', 3,
        'Welcher Vogel erreicht im Sturzflug bis zu 320 km/h und gilt als schnellstes Tier der Welt?',
        ['Steinadler', 'Wanderfalke', 'Turmfalke', 'Kondor'], 1,
        'Wanderfalke (Falco peregrinus) faltet die Flügel eng an und stürzt sich auf seine Beute. Im normalen Flug „nur" 90–100 km/h.',
        ['Wanderfalke', 'Vogel', 'Rekord']),
    mc('q-biologie-109', 'biologie', 1,
        'Welches ist das größte lebende Landtier?',
        ['Afrikanischer Elefant', 'Asiatischer Elefant', 'Nilpferd', 'Nashorn'], 0,
        'Afrikanischer Buschelefant: bis 6 Tonnen und 3,5 Meter Schulterhöhe. Der Asiatische Elefant ist kleiner und hat kleinere Ohren.',
        ['Elefant', 'Rekord']),
    mc('q-biologie-110', 'biologie', 2,
        'Was ist die kleinste strukturelle und funktionelle Einheit des Lebens?',
        ['Atom', 'Molekül', 'Zelle', 'Organ'], 2,
        'Zelltheorie (Schleiden/Schwann 1839): alle Lebewesen bestehen aus Zellen; Zellen entstehen nur aus Zellen.',
        ['Zelle', 'Zelltheorie']),
    mc('q-biologie-111', 'biologie', 2,
        'Welches Gas geben Pflanzen als Nebenprodukt der Photosynthese ab?',
        ['Kohlendioxid', 'Sauerstoff', 'Wasserstoff', 'Stickstoff'], 1,
        'Die Photosynthese ist der Grund, warum überhaupt Sauerstoff in der Erdatmosphäre existiert. Vorher (vor ca. 2,4 Mrd. Jahren) war sie sauerstofffrei.',
        ['Sauerstoff', 'Photosynthese']),
    mc('q-biologie-112', 'biologie', 3,
        'Wozu dient das Chlorophyll in Pflanzen?',
        ['Wurzelverankerung', 'Wasserspeicherung', 'Absorption von Lichtenergie', 'Blütenfärbung'], 2,
        'Chlorophyll absorbiert vor allem rotes und blaues Licht — grüne Wellenlängen werden reflektiert, weshalb Pflanzen grün aussehen.',
        ['Chlorophyll', 'Photosynthese']),
    mc('q-biologie-113', 'biologie', 3,
        'Wie heißt der Vorgang, bei dem eine Zelle sich in zwei identische Tochterzellen teilt?',
        ['Meiose', 'Mitose', 'Osmose', 'Konjugation'], 1,
        'Mitose: alle Körperzellen. Meiose: Bildung von Keimzellen (mit halbem Chromosomensatz).',
        ['Mitose', 'Zellteilung']),
    mc('q-biologie-114', 'biologie', 4,
        'Welche Zellart bezeichnet man als „Killerzellen" und ist Teil des angeborenen Immunsystems?',
        ['T-Helferzellen', 'B-Zellen', 'Natürliche Killerzellen (NK)', 'Erythrozyten'], 2,
        'NK-Zellen erkennen und töten infizierte oder tumoröse Körperzellen — ohne vorherigen Kontakt (im Gegensatz zu T-Zellen des adaptiven Immunsystems).',
        ['Immunsystem', 'NK-Zellen']),
    mc('q-biologie-115', 'biologie', 2,
        'Welche Blutgruppe wird als Universalempfänger im AB0-System bezeichnet?',
        ['0', 'A', 'B', 'AB'], 3,
        'Träger von AB haben keine anti-A- oder anti-B-Antikörper, können also Blut von A, B, AB und 0 empfangen (für Erythrozyten).',
        ['AB', 'Blutgruppe']),
    mc('q-biologie-116', 'biologie', 3,
        'Welches Tier hat die längste bekannte Lebensdauer unter Wirbeltieren (bis über 400 Jahre)?',
        ['Riesenschildkröte', 'Grönlandhai', 'Grönlandwal', 'Karpfen'], 1,
        'Der Grönlandhai (Somniosus microcephalus) erreicht durch extrem langsamen Stoffwechsel in kaltem Tiefwasser Alter von 300–500 Jahren.',
        ['Grönlandhai', 'Rekord', 'Lebensdauer']),
    mc('q-biologie-117', 'biologie', 3,
        'Was ist der Unterschied zwischen einem Insekt und einer Spinne, klassifikatorisch?',
        [
            'Insekten haben 6 Beine, Spinnen 8',
            'Insekten sind Wirbeltiere, Spinnen nicht',
            'Spinnen können fliegen, Insekten nicht',
            'Spinnen haben Fühler, Insekten nicht',
        ], 0,
        'Insekten (Insecta) = Klasse mit 6 Beinen und 3-teiligem Körper. Spinnen (Arachnida) = 8 Beine, 2-teiliger Körper, keine Fühler.',
        ['Insekten', 'Spinnentiere']),

    # ================================================================
    # Chemie & Elemente (+15 → 20 total)
    # ================================================================
    mc('q-chemie-100', 'chemie', 1,
        'Welches chemische Element hat das Symbol „H"?',
        ['Helium', 'Wasserstoff', 'Quecksilber', 'Halogen'], 1,
        'Wasserstoff (lat. hydrogenium): das leichteste und häufigste Element im Universum. Ordnungszahl 1.',
        ['Wasserstoff', 'Element']),
    mc('q-chemie-101', 'chemie', 2,
        'Wie viele Elektronen kann die erste (K-)Schale eines Atoms maximal enthalten?',
        ['2', '4', '6', '8'], 0,
        'K-Schale: max. 2. L-Schale: 8. M-Schale: 18. Formel: 2n². Erklärt den Aufbau des Periodensystems.',
        ['Elektronenschale', 'Atom']),
    mc('q-chemie-102', 'chemie', 2,
        'Welches Metall ist bei Zimmertemperatur flüssig?',
        ['Aluminium', 'Silber', 'Quecksilber', 'Blei'], 2,
        'Quecksilber (Hg) schmilzt bei −38,8 °C. Auch Cäsium, Francium und Gallium sind bei Zimmerwärme fast flüssig (Ga ab 30 °C).',
        ['Quecksilber', 'Element']),
    mc('q-chemie-103', 'chemie', 1,
        'Was ist die chemische Formel für Kochsalz?',
        ['HCl', 'NaCl', 'KCl', 'CaCO3'], 1,
        'Natriumchlorid (NaCl). Ionische Verbindung aus Natrium-Kationen und Chlorid-Anionen im 1:1-Verhältnis.',
        ['Kochsalz', 'NaCl']),
    mc('q-chemie-104', 'chemie', 2,
        'Welches Gas macht rund 78 Prozent der Erdatmosphäre aus?',
        ['Sauerstoff', 'Kohlendioxid', 'Stickstoff', 'Argon'], 2,
        'Zusammensetzung: 78 % N2, 21 % O2, 0,93 % Argon, 0,04 % CO2, Rest andere Gase.',
        ['Stickstoff', 'Atmosphäre']),
    mc('q-chemie-105', 'chemie', 2,
        'Welchen pH-Wert hat reines, destilliertes Wasser (neutral)?',
        ['0', '4', '7', '14'], 2,
        'pH 7: gleich viele H+- wie OH−-Ionen. pH < 7 sauer, pH > 7 basisch. Skala geht von 0 bis 14.',
        ['pH-Wert', 'Wasser']),
    mc('q-chemie-106', 'chemie', 3,
        'Welches Element ist nach Massenanteil das häufigste im menschlichen Körper?',
        ['Kohlenstoff', 'Sauerstoff', 'Wasserstoff', 'Stickstoff'], 1,
        'Sauerstoff: ~65 % (v. a. in Wasser). Kohlenstoff: 18 %. Wasserstoff: 10 %. Stickstoff: 3 %.',
        ['Sauerstoff', 'Körper']),
    mc('q-chemie-107', 'chemie', 4,
        'Wer entwickelte 1869 die erste weithin akzeptierte Version des Periodensystems?',
        ['Antoine Lavoisier', 'Dmitri Mendelejew', 'Marie Curie', 'Linus Pauling'], 1,
        'Mendelejews Periodensystem sagte sogar unentdeckte Elemente (z. B. Gallium, Germanium) voraus, indem er Lücken ließ.',
        ['Mendelejew', 'Periodensystem']),
    mc('q-chemie-108', 'chemie', 1,
        'In welchem Aggregatzustand ist Wasser bei −10 Grad Celsius?',
        ['Gasförmig', 'Flüssig', 'Fest', 'Plasma'], 2,
        'Reines Wasser gefriert bei 0 °C zu Eis. Salzwasser gefriert bei niedrigeren Temperaturen (Gefrierpunktserniedrigung).',
        ['Aggregatzustand', 'Wasser']),
    mc('q-chemie-109', 'chemie', 2,
        'Aus welchen Atomen besteht ein Wassermolekül?',
        [
            '2 Sauerstoff + 1 Wasserstoff',
            '1 Sauerstoff + 2 Wasserstoff',
            '1 Sauerstoff + 1 Wasserstoff',
            '2 Sauerstoff + 2 Wasserstoff',
        ], 1,
        'H2O: 2 Wasserstoff, 1 Sauerstoff. Winkel ~104,5°. Die Polarität macht Wasser zum universellen Lösungsmittel.',
        ['Wasser', 'Molekül']),
    mc('q-chemie-110', 'chemie', 2,
        'Welches Element hat das Symbol „Fe"?',
        ['Kupfer', 'Silber', 'Eisen', 'Zink'], 2,
        'Fe von lat. ferrum. Vierthäufigstes Element in der Erdkruste, macht den Kern der Erde großteils aus.',
        ['Eisen', 'Element']),
    mc('q-chemie-111', 'chemie', 3,
        'Welche zwei Gase machen zusammen ~99 % der Sonnenatmosphäre aus?',
        [
            'Sauerstoff und Stickstoff',
            'Wasserstoff und Helium',
            'Kohlendioxid und Wasserdampf',
            'Argon und Neon',
        ], 1,
        'Wasserstoff ~74 %, Helium ~24 %. Der Rest sind schwerere Elemente wie Sauerstoff, Kohlenstoff, Eisen (in Spuren).',
        ['Sonne', 'Wasserstoff', 'Helium']),
    mc('q-chemie-112', 'chemie', 3,
        'Was macht ein Katalysator in einer chemischen Reaktion?',
        [
            'Beschleunigt sie, ohne selbst verbraucht zu werden',
            'Bremst die Reaktion aus',
            'Verändert die Endprodukte',
            'Verwandelt sich am Ende in einen anderen Stoff',
        ], 0,
        'Ein Katalysator senkt die Aktivierungsenergie. Enzyme sind biologische Katalysatoren. In Autos: der Kat wandelt CO in CO2 und NOx in N2.',
        ['Katalysator', 'Chemie']),
    mc('q-chemie-113', 'chemie', 2,
        'Welche Säure findet sich im menschlichen Magen und hilft bei der Verdauung?',
        ['Schwefelsäure', 'Salpetersäure', 'Salzsäure (HCl)', 'Essigsäure'], 2,
        'Der Magen produziert pro Tag 1–3 Liter Magensäure (~pH 1). Aktiviert Pepsin, tötet Krankheitserreger.',
        ['Salzsäure', 'Magen']),
    mc('q-chemie-114', 'chemie', 4,
        'Welche organische Verbindungsklasse enthält den charakteristischen Benzolring (C6H6)?',
        ['Alkane', 'Alkene', 'Aromaten', 'Ester'], 2,
        'Aromatische Verbindungen zeichnen sich durch delokalisierte π-Elektronen im Ring aus. Beispiele: Benzol, Toluol, Naphthalin.',
        ['Aromaten', 'Benzol']),

    # ================================================================
    # Medizin & Anatomie (+6 → 20 total)
    # ================================================================
    mc('q-medizin-100', 'medizin', 2,
        'Wie viele Wirbel hat die menschliche Wirbelsäule insgesamt (inkl. verwachsener)?',
        ['24', '26', '33', '40'], 2,
        '7 Halswirbel + 12 Brustwirbel + 5 Lendenwirbel + 5 Kreuzbeinwirbel (verwachsen) + 4 Steißbeinwirbel (verwachsen) = 33.',
        ['Wirbelsäule', 'Anatomie']),
    mc('q-medizin-101', 'medizin', 2,
        'Welches Organ produziert das Hormon Insulin zur Regulierung des Blutzuckerspiegels?',
        ['Leber', 'Nieren', 'Bauchspeicheldrüse (Pankreas)', 'Schilddrüse'], 2,
        'Genauer: die Beta-Zellen der Langerhans-Inseln in der Bauchspeicheldrüse. Bei Diabetes Typ 1 zerstört das Immunsystem diese Zellen.',
        ['Insulin', 'Pankreas', 'Diabetes']),
    mc('q-medizin-102', 'medizin', 2,
        'Welche Zellart transportiert Sauerstoff im Blut?',
        [
            'Weiße Blutkörperchen',
            'Rote Blutkörperchen (Erythrozyten)',
            'Blutplättchen (Thrombozyten)',
            'Plasmazellen',
        ], 1,
        'Erythrozyten enthalten Hämoglobin, das O2 in der Lunge bindet und im Gewebe abgibt. ~25 Billionen Zellen pro Erwachsenen.',
        ['Erythrozyten', 'Blut']),
    mc('q-medizin-103', 'medizin', 2,
        'Welche Krankheit wird durch das HI-Virus verursacht?',
        ['Krebs', 'AIDS', 'Hepatitis', 'Diabetes'], 1,
        'HIV zerstört CD4-T-Helferzellen. Unbehandelt entsteht das Immunschwäche-Syndrom AIDS. Moderne antiretrovirale Therapie macht HIV kontrollierbar.',
        ['HIV', 'AIDS']),
    mc('q-medizin-104', 'medizin', 3,
        'Welcher deutsche Arzt entdeckte 1882 den Tuberkulose-Erreger und begründete die moderne Bakteriologie?',
        ['Rudolf Virchow', 'Robert Koch', 'Emil von Behring', 'Paul Ehrlich'], 1,
        'Koch identifizierte auch den Milzbrand- und Cholera-Erreger. Nobelpreis 1905. Nach ihm ist das Robert-Koch-Institut benannt.',
        ['Robert Koch', 'Tuberkulose', 'Bakteriologie']),
    mc('q-medizin-105', 'medizin', 2,
        'Welches Organ filtert das Blut und produziert Urin?',
        ['Leber', 'Milz', 'Nieren', 'Herz'], 2,
        'Die zwei Nieren filtern pro Tag ~180 Liter Blutplasma, konzentrieren daraus 1–2 Liter Urin. Reinigen den Körper von Harnstoff, Salzen, Toxinen.',
        ['Nieren', 'Anatomie']),

    # ================================================================
    # Psychologie & Verhalten (+13 → 20 total)
    # ================================================================
    mc('q-psychologie-100', 'psychologie', 2,
        'Wer gilt als Begründer der Psychoanalyse?',
        ['Carl Gustav Jung', 'Alfred Adler', 'Sigmund Freud', 'B. F. Skinner'], 2,
        'Freuds Modell: Es, Ich, Über-Ich. Zentrale Ideen: das Unbewusste, Traumdeutung, Ödipuskomplex. Sein Schüler Jung entwickelte die Analytische Psychologie.',
        ['Freud', 'Psychoanalyse']),
    mc('q-psychologie-101', 'psychologie', 3,
        'Welcher Effekt beschreibt, dass eine erste Information stärker wirkt als spätere?',
        ['Primacy-Effekt', 'Recency-Effekt', 'Halo-Effekt', 'Priming'], 0,
        'Das Gegenstück ist der Recency-Effekt (letzte Info wirkt am stärksten). Beide zusammen: die Enden einer Liste werden am besten erinnert.',
        ['Primacy', 'Gedächtnis']),
    mc('q-psychologie-102', 'psychologie', 3,
        'Wie viele Grundemotionen unterschied der Psychologe Paul Ekman in seinem klassischen Modell?',
        ['4', '5', '6', '8'], 2,
        'Freude, Traurigkeit, Angst, Wut, Überraschung, Ekel. Diese sechs identifizierte Ekman als kulturübergreifend an Gesichtsausdrücken erkennbar.',
        ['Ekman', 'Emotionen']),
    mc('q-psychologie-103', 'psychologie', 3,
        'Welcher psychologische Test verwendet Tintenklecks-Bilder zur Persönlichkeitsanalyse?',
        ['MMPI', 'Rorschach-Test', 'TAT', 'Big Five'], 1,
        'Hermann Rorschach entwickelte 1921 die zehn symmetrischen Kleckse. Wissenschaftlich umstritten, aber weit verbreitet.',
        ['Rorschach', 'Persönlichkeit']),
    mc('q-psychologie-104', 'psychologie', 3,
        'Welches Persönlichkeitsmodell fasst fünf Kernmerkmale zusammen (u. a. Offenheit, Gewissenhaftigkeit)?',
        ['Enneagramm', 'Big Five (OCEAN)', '16 Persönlichkeiten (MBTI)', 'DiSC'], 1,
        'OCEAN: Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism. Wissenschaftlich am besten validiertes Modell.',
        ['Big Five', 'OCEAN', 'Persönlichkeit']),
    mc('q-psychologie-105', 'psychologie', 3,
        'Wer führte in den 1960ern die berühmten Gehorsams-Experimente mit vermeintlichen Elektroschocks durch?',
        ['Solomon Asch', 'Stanley Milgram', 'Philip Zimbardo', 'Albert Bandura'], 1,
        'Milgram zeigte: 65 % der Probanden gaben auf Anweisung „tödliche" Elektroschocks. Aufschluss über Autoritätsgehorsam nach dem 2. Weltkrieg.',
        ['Milgram', 'Autorität']),
    mc('q-psychologie-106', 'psychologie', 3,
        'Welche psychologische Verzerrung führt zur Überschätzung von Ereignissen, die einem leicht in den Sinn kommen?',
        ['Verfügbarkeitsheuristik', 'Ankereffekt', 'Confirmation Bias', 'Sunk-Cost-Fallacy'], 0,
        'Wir überschätzen z. B. das Risiko von Flugzeugabstürzen weil sie medienpräsent sind, obwohl Autofahren viel gefährlicher ist.',
        ['Verfügbarkeitsheuristik', 'Kahneman']),
    mc('q-psychologie-107', 'psychologie', 3,
        'Welcher Botenstoff wird populär als „Belohnungshormon" bezeichnet und mit Motivation, Sucht und Freude verknüpft?',
        ['Serotonin', 'Dopamin', 'Adrenalin', 'Kortisol'], 1,
        'Wird bei erwartetem Genuss ausgeschüttet — nicht erst beim Erhalt. Zentrale Rolle in Suchterkrankungen.',
        ['Dopamin', 'Neurotransmitter']),
    mc('q-psychologie-108', 'psychologie', 4,
        'Welches Gruppen-Phänomen beschreibt, dass Gruppen extremere Entscheidungen treffen als Einzelpersonen?',
        ['Gruppenpolarisation', 'Konformität', 'Groupthink', 'Deindividuation'], 0,
        'In Diskussionen driften Gruppen in Richtung der ohnehin dominanten Ansicht. Beispiel: politische Filterblasen.',
        ['Gruppenpolarisation', 'Sozialpsychologie']),
    mc('q-psychologie-109', 'psychologie', 3,
        'Wer entwickelte das Konzept der operanten Konditionierung („Skinner-Box")?',
        ['Ivan Pawlow', 'John B. Watson', 'B. F. Skinner', 'Edward Thorndike'], 2,
        'Skinner zeigte: Verhalten wird durch Belohnung und Strafe geformt. Grundlage moderner Verhaltenstherapie.',
        ['Skinner', 'Operante Konditionierung']),
    mc('q-psychologie-110', 'psychologie', 3,
        'Welcher Effekt beschreibt die Neigung, das Verhalten anderer eher der Person als der Situation zuzuschreiben?',
        ['Fundamentaler Attributionsfehler', 'Confirmation Bias', 'Halo-Effekt', 'Barnum-Effekt'], 0,
        'Wenn jemand aggressiv ist, denken wir „unfreundliche Person". Bei uns selbst suchen wir Ausreden in der Situation.',
        ['Attributionsfehler', 'Sozialpsychologie']),
    mc('q-psychologie-111', 'psychologie', 3,
        'Welche Denk-Fehlern beschreibt die Sunk-Cost-Fallacy?',
        [
            'Wir setzen bereits investierte Ressourcen fort, obwohl sie irreversibel verloren sind',
            'Wir vergessen alte Investitionen zu schnell',
            'Wir überschätzen zukünftige Gewinne',
            'Wir vermeiden jegliche Investition',
        ], 0,
        'Beispiel: Wir gucken einen schlechten Film zu Ende, weil wir schon 60 Minuten investiert haben. Rational wäre: aussteigen.',
        ['Sunk-Cost', 'Entscheidung']),
    mc('q-psychologie-112', 'psychologie', 3,
        'Welche Persönlichkeitsstörung ist durch übertriebene Selbstbezogenheit und Grandiositätsgefühl gekennzeichnet?',
        ['Borderline', 'Narzisstisch', 'Antisozial', 'Zwanghaft'], 1,
        'Narzisstische Persönlichkeitsstörung (NPS): Mangel an Empathie, Bewunderungsbedürfnis, Ausbeutung anderer.',
        ['Narzissmus', 'Persönlichkeitsstörung']),

    # ================================================================
    # Mathematik & Zahlen (+20 → 20 total)
    # ================================================================
    mc('q-mathematik-100', 'mathematik', 1,
        'Was ist der Wert von Pi (π) auf zwei Nachkommastellen gerundet?',
        ['3,12', '3,14', '3,16', '3,18'], 1,
        'Genau: 3,14159265... — irrationale Zahl, unendlich viele Nachkommastellen ohne Muster.',
        ['Pi', 'Konstante']),
    mc('q-mathematik-101', 'mathematik', 1,
        'Wer bewies das Theorem über die Seitenlängen im rechtwinkligen Dreieck (a² + b² = c²)?',
        ['Euklid', 'Pythagoras', 'Archimedes', 'Thales'], 1,
        'Pythagoras von Samos (~570 v. Chr.). Der Satz war schon Babyloniern bekannt, aber P. lieferte den ersten geometrischen Beweis.',
        ['Pythagoras', 'Satz']),
    mc('q-mathematik-102', 'mathematik', 1,
        'Was ist die Quadratwurzel von 144?',
        ['10', '11', '12', '14'], 2,
        '12 × 12 = 144. Praktisch: 12² = 144, 13² = 169.',
        ['Quadratwurzel']),
    mc('q-mathematik-103', 'mathematik', 3,
        'Wie heißt die mathematische Konstante mit dem Wert ca. 2,718, benannt nach einem Schweizer Mathematiker?',
        ['e (Eulersche Zahl)', 'π', 'φ (Goldener Schnitt)', '√2'], 0,
        'Nach Leonhard Euler (1707–1783). Basis des natürlichen Logarithmus, taucht in Zinseszins- und Wachstumsformeln auf.',
        ['e', 'Euler', 'Konstante']),
    mc('q-mathematik-104', 'mathematik', 1,
        'Wie viele Grad hat die Winkelsumme in einem beliebigen Dreieck (in der euklidischen Geometrie)?',
        ['90°', '180°', '270°', '360°'], 1,
        'Beweisbar aus dem Parallelaxiom. Auf einer Kugeloberfläche (nicht-euklidisch) sind es mehr als 180°.',
        ['Dreieck', 'Winkelsumme']),
    mc('q-mathematik-105', 'mathematik', 3,
        'Was ist die Ableitung von x² nach x?',
        ['2', 'x', '2x', 'x²'], 2,
        'Potenzregel: d/dx (xⁿ) = n·xⁿ⁻¹. Für x²: 2·x¹ = 2x.',
        ['Ableitung', 'Analysis']),
    mc('q-mathematik-106', 'mathematik', 2,
        'Wie nennt man Zahlen, die nur durch 1 und sich selbst teilbar sind?',
        ['Gerade Zahlen', 'Primzahlen', 'Fibonacci-Zahlen', 'Ganze Zahlen'], 1,
        'Beispiele: 2, 3, 5, 7, 11, 13, 17... Die Anzahl der Primzahlen ist nach Euklid unendlich.',
        ['Primzahl']),
    mc('q-mathematik-107', 'mathematik', 2,
        'Was ist die kleinste Primzahl?',
        ['0', '1', '2', '3'], 2,
        'Definition: eine natürliche Zahl > 1, die nur durch 1 und sich selbst teilbar ist. 1 ist ausgeschlossen. 2 ist zudem die einzige gerade Primzahl.',
        ['Primzahl', '2']),
    mc('q-mathematik-108', 'mathematik', 3,
        'Welche Fibonacci-Zahl folgt auf 8 und 13?',
        ['15', '18', '21', '24'], 2,
        'Fibonacci: jede Zahl ist die Summe der beiden Vorgänger: 1, 1, 2, 3, 5, 8, 13, 21, 34, ...',
        ['Fibonacci']),
    mc('q-mathematik-109', 'mathematik', 3,
        'Was ist die Fakultät von 5 (5!)?',
        ['25', '60', '120', '720'], 2,
        '5! = 5 × 4 × 3 × 2 × 1 = 120. Fakultäten zählen die Anzahl der Anordnungen einer Menge.',
        ['Fakultät', 'Kombinatorik']),
    mc('q-mathematik-110', 'mathematik', 1,
        'Welcher Bruch entspricht 0,25 dezimal?',
        ['1/2', '1/3', '1/4', '1/5'], 2,
        '1/4 = 0,25. Zum Vergleich: 1/2 = 0,5, 1/3 ≈ 0,333, 1/5 = 0,2.',
        ['Bruch']),
    mc('q-mathematik-111', 'mathematik', 4,
        'Wie viele Ecken hat ein Ikosaeder (einer der fünf platonischen Körper)?',
        ['8', '12', '20', '30'], 1,
        'Ikosaeder: 20 Flächen (Dreiecke), 12 Ecken, 30 Kanten. Euler-Formel: E − K + F = 2.',
        ['Ikosaeder', 'Platonische Körper']),
    mc('q-mathematik-112', 'mathematik', 4,
        'Wer bewies 1994 den „Großen Fermatschen Satz", der über 350 Jahre unbewiesen war?',
        ['Andrew Wiles', 'John Nash', 'Grigori Perelman', 'Terence Tao'], 0,
        'Wiles arbeitete sieben Jahre im Geheimen. Der Beweis nutzt tiefe Verbindungen zwischen Modulformen und elliptischen Kurven.',
        ['Fermat', 'Wiles']),
    mc('q-mathematik-113', 'mathematik', 1,
        'Wie viele Ziffern hat das Dezimalsystem?',
        ['8', '9', '10', '12'], 2,
        '0, 1, 2, 3, 4, 5, 6, 7, 8, 9 — also 10. Basis 10. Wahrscheinlich weil Menschen 10 Finger haben.',
        ['Dezimalsystem']),
    mc('q-mathematik-114', 'mathematik', 3,
        'Welcher griechische Mathematiker berechnete π mit hoher Präzision im 3. Jahrhundert v. Chr.?',
        ['Archimedes', 'Aristoteles', 'Pythagoras', 'Euklid'], 0,
        'Archimedes fand die Grenzen 223/71 < π < 22/7 durch Approximation mit Polygonen im/um einem Kreis (bis 96 Ecken).',
        ['Archimedes', 'Pi']),
    mc('q-mathematik-115', 'mathematik', 2,
        'Wie viele Kanten hat ein Würfel (Hexaeder)?',
        ['6', '8', '10', '12'], 3,
        'Würfel: 6 Flächen, 8 Ecken, 12 Kanten. Euler-Formel: 8 − 12 + 6 = 2.',
        ['Würfel', 'Geometrie']),
    mc('q-mathematik-116', 'mathematik', 2,
        'Welche Zahl ist die Basis des binären (dualen) Zahlensystems?',
        ['2', '8', '10', '16'], 0,
        'Nur zwei Ziffern: 0 und 1. Basis 2. Fundamentales System aller digitaler Rechner. Alternative Systeme: 8 (oktal), 16 (hexadezimal).',
        ['Binär', 'Zahlensystem']),
    mc('q-mathematik-117', 'mathematik', 3,
        'Wie nennt man eine gerade Linie, die einen Kreis in genau einem Punkt berührt?',
        ['Sekante', 'Tangente', 'Sehne', 'Radius'], 1,
        'Tangente steht immer senkrecht auf dem Radius im Berührpunkt. Sekante schneidet den Kreis in zwei Punkten.',
        ['Tangente', 'Geometrie']),
    mc('q-mathematik-118', 'mathematik', 4,
        'Welcher britische Mathematiker gilt als Vater der theoretischen Informatik und knackte im 2. Weltkrieg die Enigma?',
        ['Alan Turing', 'John von Neumann', 'Kurt Gödel', 'Bertrand Russell'], 0,
        'Turings Universal-Maschinen-Modell (1936) ist die Grundlage jedes modernen Computers. In Bletchley Park entwickelte er die Bombe zur Enigma-Entschlüsselung.',
        ['Turing', 'Enigma']),
    mc('q-mathematik-119', 'mathematik', 3,
        'Welches Verhältnis (~1,618) findet sich in Nautilus-Muscheln, Sonnenblumen und Renaissance-Kunst?',
        ['Pi', 'Eulersche Zahl e', 'Goldener Schnitt (φ)', 'Wurzel 2'], 2,
        'φ = (1 + √5) / 2 ≈ 1,618. In der Natur häufig als Näherung, in Kunst und Architektur oft bewusst eingesetzt (z. B. Le Corbusier).',
        ['Goldener Schnitt', 'φ']),
]


def main() -> int:
    with QUESTIONS_PATH.open('r', encoding='utf-8') as f:
        existing = json.load(f)
    existing_ids = {q['id'] for q in existing}
    to_add = [q for q in NEW_QUESTIONS if q['id'] not in existing_ids]
    skipped = [q['id'] for q in NEW_QUESTIONS if q['id'] in existing_ids]

    if skipped:
        print(f'ℹ  Überspringe {len(skipped)} bereits vorhandene ID(s).')
    if not to_add:
        print('Keine neuen Fragen zu ergänzen.')
        return 0

    # Sanity-Checks
    for q in to_add:
        assert q['type'] == 'multiple-choice'
        assert len(q['options']) == 4, f'{q["id"]} hat {len(q["options"])} Optionen'
        assert 0 <= q['correctIndex'] < 4, f'{q["id"]} correctIndex out of range'

    merged = existing + to_add
    with QUESTIONS_PATH.open('w', encoding='utf-8') as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
        f.write('\n')

    # Zusammenfassung
    from collections import Counter
    counter = Counter(q['topic'] for q in to_add)
    print(f'✓ {len(to_add)} neue Fragen ergänzt (jetzt {len(merged)} insgesamt).')
    for topic, count in sorted(counter.items()):
        print(f'  + {topic:<14} {count}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
