#!/usr/bin/env python3
"""Batch 5: pflanzen, fotografie, kunst, literatur (80 Fragen)."""
from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
QUESTIONS_PATH = ROOT / 'packages' / 'shared' / 'src' / 'data' / 'questions.json'
NOW = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
MC_MODES = ['category-duel', 'flash', 'player-spotlight', 'sprinter',
            'points-ladder', 'category-board', 'duel-1v1', 'elimination', 'experts']


def mc(qid, topic, difficulty, question, options, correct, gm, tags, category='allgemeinbildung'):
    return {'id': qid, 'type': 'multiple-choice', 'status': 'approved',
        'category': category, 'topic': topic, 'difficulty': difficulty,
        'question': question, 'options': options, 'correctIndex': correct,
        'gmNote': gm, 'tags': tags, 'compatibleModes': MC_MODES,
        'timeScope': 'timeless', 'aiGenerated': True,
        'createdAt': NOW, 'updatedAt': NOW}


NEW_QUESTIONS = []

# PFLANZEN & GARTENARBEIT (20)
NEW_QUESTIONS += [
    mc('q-pflanzen-100', 'pflanzen', 1,
        'Wie nennt man den Vorgang, bei dem Pflanzen aus Licht, CO2 und Wasser Zucker herstellen?',
        ['Atmung', 'Photosynthese', 'Verdunstung', 'Osmose'], 1,
        'Photosynthese läuft in den Chloroplasten ab. Blattgrün (Chlorophyll) absorbiert Licht — Nebenprodukt: Sauerstoff.',
        ['Photosynthese', 'Chlorophyll']),
    mc('q-pflanzen-101', 'pflanzen', 1,
        'Welche Farbe hat der Farbstoff Chlorophyll in Blättern?',
        ['Rot', 'Blau', 'Grün', 'Gelb'], 2,
        'Chlorophyll reflektiert grünes Licht, absorbiert rot und blau. Im Herbst wird es abgebaut — Carotinoide (gelb/orange) treten hervor.',
        ['Chlorophyll', 'Blätter']),
    mc('q-pflanzen-102', 'pflanzen', 2,
        'Welche Blume ist das Wahrzeichen der Niederlande und blüht im Frühjahr in riesigen Feldern?',
        ['Rose', 'Tulpe', 'Sonnenblume', 'Lilie'], 1,
        'Tulpe. Im 17. Jh. „Tulpenmanie" — spekulative Blase. Heute exportieren die NL rund 4 Mrd. Tulpenzwiebeln jährlich.',
        ['Tulpe', 'Niederlande']),
    mc('q-pflanzen-103', 'pflanzen', 2,
        'Welche Pflanze wächst in Bambuswäldern und ist die Hauptnahrung des Großen Pandas?',
        ['Farn', 'Bambus', 'Schilf', 'Zuckerrohr'], 1,
        'Bambus ist botanisch ein Gras — kann bis 1 m pro Tag wachsen. Riesenpanda frisst 12–38 kg Bambus/Tag.',
        ['Bambus', 'Panda']),
    mc('q-pflanzen-104', 'pflanzen', 2,
        'Was bezeichnet der Gärtnerbegriff „einjährig" bei Pflanzen?',
        [
            'Pflanze lebt genau ein Kalenderjahr',
            'Pflanze durchläuft Lebenszyklus in einer Vegetationsperiode',
            'Pflanze blüht nur alle 12 Monate',
            'Pflanze wird jedes Jahr neu geschnitten',
        ], 1,
        'Einjährige (annuelle) Pflanzen keimen, blühen, samen und sterben in einer Saison. Bsp.: Ringelblume, Kapuzinerkresse, Zinnie.',
        ['Einjährig', 'Zyklus']),
    mc('q-pflanzen-105', 'pflanzen', 2,
        'Welches Substrat verbessert schweren Lehmboden im Garten?',
        ['Sand oder Kompost', 'Zement', 'Streusalz', 'Tonpulver'], 0,
        'Sand lockert, Kompost/Humus verbessert Struktur und Nährstoffe. Tonpulver würde Boden noch dichter machen.',
        ['Boden', 'Lehm']),
    mc('q-pflanzen-106', 'pflanzen', 3,
        'Wer legte 1735 mit „Systema Naturae" die zweiteilige lateinische Pflanzenbenennung fest?',
        ['Charles Darwin', 'Carl von Linné', 'Gregor Mendel', 'Alexander von Humboldt'], 1,
        'Linné (schwed. Botaniker) — binäre Nomenklatur „Gattung Art" (z. B. Rosa canina). Basis der modernen Taxonomie.',
        ['Linné', 'Taxonomie']),
    mc('q-pflanzen-107', 'pflanzen', 2,
        'Wozu dient Mulchen im Garten?',
        [
            'Boden feucht halten und Unkraut unterdrücken',
            'Pflanzen düngen',
            'Schädlinge anlocken',
            'PH-Wert erhöhen',
        ], 0,
        'Mulch (Rindenschnipsel, Stroh, Laub) speichert Feuchtigkeit, hält Boden kühl, hemmt Unkraut. Verrottet und liefert Nährstoffe.',
        ['Mulch', 'Garten']),
    mc('q-pflanzen-108', 'pflanzen', 3,
        'Welcher Baum kann mehr als 3 000 Jahre alt werden und ist bekannt für rote Rinde in Kalifornien?',
        ['Eiche', 'Küstenmammutbaum (Sequoia)', 'Fichte', 'Ahorn'], 1,
        'Sequoia sempervirens (Küstenmammutbaum). Größter Lebendbaum „General Sherman" (Riesenmammutbaum): ~84 m, ~2 500 t.',
        ['Sequoia', 'Baum']),
    mc('q-pflanzen-109', 'pflanzen', 2,
        'Welche Zimmerpflanze ist eine bekannte fleischfressende Pflanze mit klappenden Blättern?',
        ['Aloe Vera', 'Venusfliegenfalle', 'Efeu', 'Farn'], 1,
        'Dionaea muscipula. Klappe schließt in ~0,1 s, wenn zwei Sinnesborsten in 20 s berührt werden. Verdauung 5–12 Tage.',
        ['Venusfliegenfalle', 'Karnivor']),
    mc('q-pflanzen-110', 'pflanzen', 2,
        'Welche Frucht wächst botanisch als Beere, obwohl sie im Alltag als Gemüse gilt?',
        ['Kartoffel', 'Tomate', 'Karotte', 'Salat'], 1,
        'Tomate ist botanisch eine Beere (Fleischfrucht). Bis 1893 galt in US-Zollstreit „Nix vs. Hedden": im Sinn der Steuer ein Gemüse.',
        ['Tomate', 'Botanik']),
    mc('q-pflanzen-111', 'pflanzen', 2,
        'Welche Pflanze steht im Buddhismus symbolisch für Reinheit und wächst aus Schlamm empor?',
        ['Lotus', 'Bambus', 'Rose', 'Orchidee'], 0,
        'Lotus (Nelumbo nucifera). Blätter sind wachsartig — „Lotoseffekt" (Wasser perlt ab). Symbol in Hinduismus & Buddhismus.',
        ['Lotus', 'Symbol']),
    mc('q-pflanzen-112', 'pflanzen', 3,
        'Was ist „Hydrokultur"?',
        [
            'Pflanzenzucht in Wasser statt Erde',
            'Zucht im Gewächshaus',
            'Wildwuchsende Pflanzen',
            'Zucht auf Vulkanboden',
        ], 0,
        'Pflanzen wachsen in Nährlösung, Wurzeln in Wasser oder Substrat wie Blähton. Weniger Wasserverbrauch, keine Erde.',
        ['Hydrokultur', 'Wasser']),
    mc('q-pflanzen-113', 'pflanzen', 2,
        'Welche Blume gilt als das Wahrzeichen der Liebe und wird zum Valentinstag verschenkt?',
        ['Chrysantheme', 'Nelke', 'Rote Rose', 'Lilie'], 2,
        'Rote Rose (Rosa). Symbol für Leidenschaft. In der viktorianischen Blumensprache: „Ich liebe dich".',
        ['Rose', 'Valentinstag']),
    mc('q-pflanzen-114', 'pflanzen', 3,
        'Wie viele Sonnenblumenkerne enthält im Schnitt ein Sonnenblumenkopf?',
        ['~200', '~1 000-2 000', '~5 000', '~10 000'], 1,
        'Ein typischer Kopf: 1 000–2 000 Kerne, angeordnet in Fibonacci-Spiralen (34, 55, 89). Große Sorten bis 4 000 Kerne.',
        ['Sonnenblume', 'Fibonacci']),
    mc('q-pflanzen-115', 'pflanzen', 2,
        'Welches Nadelgehölz verliert im Herbst als einziges seine Nadeln?',
        ['Fichte', 'Tanne', 'Lärche', 'Kiefer'], 2,
        'Lärche (Larix): Nadeln färben sich gelb und fallen ab. Einziges heimisches Nadelholz mit Laubwechsel.',
        ['Lärche', 'Nadelbaum']),
    mc('q-pflanzen-116', 'pflanzen', 2,
        'Was bezeichnet „Kompost" im Garten?',
        [
            'Chemischer Dünger',
            'Zersetzte organische Abfälle als Humus',
            'Torfmoos',
            'Rindenmulch',
        ], 1,
        'Kompost = zersetzte Küchen- und Gartenabfälle. Nach 6–12 Monaten wird daraus nährstoffreicher Humus („schwarzes Gold").',
        ['Kompost', 'Humus']),
    mc('q-pflanzen-117', 'pflanzen', 2,
        'Welche Pflanze produziert Latex und wird in Malaysia für Naturkautschuk angebaut?',
        ['Palme', 'Kautschukbaum (Hevea)', 'Bambus', 'Zuckerrohr'], 1,
        'Hevea brasiliensis. Milchsaft wird angezapft und zu Naturgummi verarbeitet. Malaysia, Thailand & Indonesien = ~70 % der Weltproduktion.',
        ['Kautschuk', 'Hevea']),
    mc('q-pflanzen-118', 'pflanzen', 3,
        'Welche Efeu-Art wird in England oft als „poison ivy" bezeichnet und verursacht Hautausschläge?',
        [
            'Gemeiner Efeu (Hedera helix)',
            'Giftefeu (Toxicodendron radicans)',
            'Wilder Wein',
            'Waldrebe',
        ], 1,
        'Toxicodendron radicans (nicht mit Hedera verwandt) enthält Urushiol — löst starken juckenden Ausschlag aus. Vor allem in Nordamerika.',
        ['Giftefeu', 'Urushiol']),
    mc('q-pflanzen-119', 'pflanzen', 2,
        'Was ist Bonsai?',
        [
            'Japanische Zwergbaum-Kunst',
            'Chinesische Blumenkunst',
            'Eine Meditationsform',
            'Ein Baumdünger',
        ], 0,
        'Bonsai („Baum in Schale") — jahrelanges Beschneiden und Drahten hält Bäume in Miniaturform. Traditionell chinesisch (Penjing), in Japan verfeinert.',
        ['Bonsai', 'Japan']),
]

# FOTOGRAFIE (20)
NEW_QUESTIONS += [
    mc('q-fotografie-100', 'fotografie', 1,
        'Was steuert bei einer Kamera die Blende („Aperture")?',
        [
            'Belichtungszeit',
            'Größe der Lichtöffnung im Objektiv',
            'ISO-Empfindlichkeit',
            'Farbtemperatur',
        ], 1,
        'Blende (f-Zahl) bestimmt Lichtmenge und Schärfentiefe. Kleine f-Zahl = große Öffnung = geringe Tiefe. Wichtige Größe im Belichtungsdreieck.',
        ['Blende', 'Aperture']),
    mc('q-fotografie-101', 'fotografie', 2,
        'Welche drei Werte bilden das „Belichtungsdreieck"?',
        [
            'ISO, Blende, Verschlusszeit',
            'Weißabgleich, Fokus, Blitz',
            'RAW, JPEG, TIFF',
            'Objektiv, Sensor, Speicherkarte',
        ], 0,
        'ISO (Empfindlichkeit), Blende (Öffnung), Verschlusszeit (Zeit). Die drei bestimmen zusammen die Bildhelligkeit.',
        ['Belichtungsdreieck', 'Basics']),
    mc('q-fotografie-102', 'fotografie', 2,
        'Was gibt der ISO-Wert bei Digitalkameras an?',
        [
            'Bildauflösung',
            'Empfindlichkeit des Sensors gegenüber Licht',
            'Farbgenauigkeit',
            'Zoomfaktor',
        ], 1,
        'ISO 100 = wenig empfindlich (helle Szene, sauberes Bild). ISO 6400+ = für dunkle Szenen, aber mehr Rauschen.',
        ['ISO', 'Sensor']),
    mc('q-fotografie-103', 'fotografie', 2,
        'Welche Regel teilt das Bild in 3×3 Raster und platziert Motive an Kreuzungspunkten?',
        [
            'Goldener Schnitt',
            'Drittel-Regel',
            'Diagonalregel',
            'Symmetrieregel',
        ], 1,
        'Drittel-Regel („Rule of Thirds") — Hilfskomposition, seit ~1797 formuliert. Motiv auf Kreuzungspunkten wirkt spannender als mittig.',
        ['Komposition', 'Drittel']),
    mc('q-fotografie-104', 'fotografie', 2,
        'Was bezeichnet die „goldene Stunde" in der Fotografie?',
        [
            'Mittagszeit mit hohem Sonnenstand',
            'Erste/letzte Stunde des Tageslichts mit warmem, weichem Licht',
            'Stunde der teuersten Aufnahmen',
            'Zeit vor dem Sonnenaufgang',
        ], 1,
        'Kurz nach Sonnenaufgang und vor Sonnenuntergang. Tiefes, warmes Licht — flatterhafte Schatten und goldener Farbton.',
        ['Goldene Stunde', 'Licht']),
    mc('q-fotografie-105', 'fotografie', 3,
        'Welche Firma stellte 1888 die erste einfach zu bedienende Rollfilmkamera her („You press the button, we do the rest")?',
        ['Nikon', 'Canon', 'Kodak', 'Leica'], 2,
        'Eastman Kodak, gegründet von George Eastman. Kamera No. 1 (1888) hatte 100 Aufnahmen, wurde als Ganzes eingeschickt zur Entwicklung.',
        ['Kodak', 'Eastman']),
    mc('q-fotografie-106', 'fotografie', 3,
        'Was steht die Abkürzung „DSLR" für?',
        [
            'Digital Single Lens Reflex',
            'Digital Sensor Light Range',
            'Digital System Lens Recorder',
            'Direct Speed Lens Reader',
        ], 0,
        'DSLR = digitale Spiegelreflex. Spiegel lenkt Licht zum optischen Sucher, klappt bei Auslösung hoch. Wird zunehmend durch spiegellose Kameras ersetzt.',
        ['DSLR', 'Kamera']),
    mc('q-fotografie-107', 'fotografie', 2,
        'Wozu dient ein Polfilter (Polarisationsfilter) bei der Fotografie?',
        [
            'Verstärkt Blitz',
            'Reduziert Reflexionen und intensiviert Himmelblau',
            'Wärmt Farben',
            'Fokussiert automatisch',
        ], 1,
        'Blockiert polarisiertes Licht. Weniger Reflexe auf Wasser/Glas, sattere Farben, dunkleres Himmelblau.',
        ['Polfilter', 'Filter']),
    mc('q-fotografie-108', 'fotografie', 2,
        'Welcher berühmte Fotograf gilt mit „The Decisive Moment" (1952) als Vater der Straßenfotografie?',
        ['Ansel Adams', 'Henri Cartier-Bresson', 'Robert Capa', 'Diane Arbus'], 1,
        'Henri Cartier-Bresson (F, 1908–2004). Mitgründer der Foto-Agentur Magnum. „Decisive moment" = Bruchteilsekunde, in der Form & Emotion zusammenkommen.',
        ['Cartier-Bresson', 'Street']),
    mc('q-fotografie-109', 'fotografie', 3,
        'Welches Dateiformat speichert unkomprimierte Rohdaten des Kamerasensors?',
        ['JPEG', 'RAW', 'PNG', 'GIF'], 1,
        'RAW (z. B. CR3, NEF, ARW) enthält alle Sensordaten. Große Datei, aber volle Kontrolle in Post-Processing (Belichtung, WB, Rauschen).',
        ['RAW', 'Format']),
    mc('q-fotografie-110', 'fotografie', 2,
        'Was passiert bei langer Belichtungszeit (z. B. 5 s) mit fließendem Wasser?',
        [
            'Wird eingefroren gestochen scharf',
            'Wirkt weich verschwommen wie Nebel',
            'Wird schwarz',
            'Verschwindet',
        ], 1,
        'Langzeitbelichtung glättet Wasser zu einem seidigen Flow. Beliebt für Wasserfälle. Braucht Stativ + ND-Filter bei Tag.',
        ['Langzeit', 'Wasserfall']),
    mc('q-fotografie-111', 'fotografie', 2,
        'Wie wird die geringe Schärfentiefe (unscharfer Hintergrund) auf Japanisch genannt?',
        ['Wabi-Sabi', 'Bokeh', 'Umami', 'Sakura'], 1,
        'Bokeh (ぼけ) = „Unschärfe". Beschreibt Qualität der Unschärfe-Kreise. Beeinflusst durch Blende, Brennweite und Objektiv-Design.',
        ['Bokeh', 'Schärfentiefe']),
    mc('q-fotografie-112', 'fotografie', 3,
        'Was bezeichnet der Weißabgleich (White Balance)?',
        [
            'Auto-Belichtung',
            'Farbtemperatur-Korrektur, damit Weiß neutral erscheint',
            'Kontrast-Regelung',
            'Fokussierung',
        ], 1,
        'Passt Kamera an Lichtquelle an (Sonne ~5 500 K, Glühbirne ~2 700 K). Ohne Korrektur werden Bilder gelblich oder bläulich.',
        ['Weißabgleich', 'Kelvin']),
    mc('q-fotografie-113', 'fotografie', 3,
        'Welche Brennweite gilt als „Normalobjektiv" bei Vollformat und entspricht etwa dem menschlichen Sichtwinkel?',
        ['24 mm', '50 mm', '85 mm', '200 mm'], 1,
        '50 mm (KB-Format) — natürlicher Bildwinkel ~46°. Beliebt für Porträt und Reportage. Weit: 24 mm, Tele: 85 mm+.',
        ['Brennweite', 'Normalobjektiv']),
    mc('q-fotografie-114', 'fotografie', 3,
        'Wer schoss 1972 das berühmte Foto „Napalm Girl" während des Vietnamkriegs?',
        ['Robert Capa', 'Nick Út', 'Steve McCurry', 'James Nachtwey'], 1,
        'Nick Út (AP-Fotograf) — Pulitzerpreis 1973. Zeigt die 9-jährige Kim Phúc, fliehend nach Napalm-Angriff. Wandte Weltöffentlichkeit gegen den Krieg.',
        ['Nick Ut', 'Vietnam']),
    mc('q-fotografie-115', 'fotografie', 2,
        'Was ist ein Stativ?',
        [
            'Kamera-Handgurt',
            'Dreibein-Halterung für stabile Aufnahmen',
            'Objektivadapter',
            'Blitzhalterung',
        ], 1,
        'Tripod = 3 Beine, für Landschaft, Langzeit, Astro. Alternativen: Monopod (1 Bein) oder Gorillapod (flexibel).',
        ['Stativ', 'Tripod']),
    mc('q-fotografie-116', 'fotografie', 3,
        'Welche Kameramarke gilt als Kult für Leica-Messsucher und wurde 1913 in Wetzlar gegründet?',
        ['Canon', 'Nikon', 'Leica', 'Hasselblad'], 2,
        'Leica (Ernst Leitz). Oskar Barnack baute 1913 den ersten Prototypen, ab 1925 verkauft. Erste erfolgreiche Kleinbildkamera.',
        ['Leica', 'Wetzlar']),
    mc('q-fotografie-117', 'fotografie', 4,
        'Wie viele Megapixel hatte die erste kommerzielle Digitalkamera „Dycam Model 1" (1990)?',
        ['0,09 MP (376×240)', '1 MP', '3 MP', '5 MP'], 0,
        'Nur 90 000 Pixel Graustufen. Preis 995 $. Erste digitale Consumer-Kamera. Heute enthält jedes Handy 12+ MP.',
        ['Dycam', 'Digital']),
    mc('q-fotografie-118', 'fotografie', 2,
        'Was bezeichnet HDR in der Fotografie?',
        [
            'High Dynamic Range: mehrere Belichtungen kombiniert',
            'Ein Filterschema',
            'Ein Kameramodus für Selfies',
            'Fokus-Stacking',
        ], 0,
        'HDR = Kombiniert dunkle + normale + helle Aufnahmen. Erweitert Kontrastumfang, so dass Himmel und Schatten Zeichnung behalten.',
        ['HDR', 'Belichtung']),
    mc('q-fotografie-119', 'fotografie', 3,
        'Welcher Fotograf ist berühmt für schwarz-weiße Landschaftsfotos des Yosemite Nationalparks und das Zonensystem?',
        ['Ansel Adams', 'Edward Weston', 'Man Ray', 'Sebastião Salgado'], 0,
        'Ansel Adams (US, 1902–1984). Entwickelte mit Fred Archer das Zonensystem (10 Tonwertzonen). Bilder wie „Moonrise, Hernandez" (1941).',
        ['Ansel Adams', 'Yosemite']),
]

# KUNST & MALEREI (20)
NEW_QUESTIONS += [
    mc('q-kunst-100', 'kunst', 1,
        'Wer malte die „Mona Lisa"?',
        ['Michelangelo', 'Raffael', 'Leonardo da Vinci', 'Tizian'], 2,
        'Leonardo da Vinci (~1503–1506). Hängt im Louvre. Lisa Gherardini, Frau eines Florentiner Kaufmanns. Sfumato-Technik.',
        ['Mona Lisa', 'Leonardo']),
    mc('q-kunst-101', 'kunst', 1,
        'Welcher Niederländer malte „Die Sternennacht" mit wirbelnden Sternen?',
        ['Rembrandt', 'Vincent van Gogh', 'Johannes Vermeer', 'Piet Mondrian'], 1,
        'Van Gogh (1889) — gemalt aus dem Fenster einer Nervenheilanstalt in Saint-Rémy. Hängt im MoMA New York.',
        ['Van Gogh', 'Sternennacht']),
    mc('q-kunst-102', 'kunst', 2,
        'Welche Kunstrichtung war Pablo Picasso Mitbegründer, ab ~1907?',
        ['Impressionismus', 'Kubismus', 'Surrealismus', 'Pop Art'], 1,
        'Kubismus (Picasso + Georges Braque). Zerlegte Motive in geometrische Formen, mehrere Perspektiven gleichzeitig. „Les Demoiselles d\'Avignon" (1907).',
        ['Kubismus', 'Picasso']),
    mc('q-kunst-103', 'kunst', 2,
        'Wer schnitt sich 1888 in Arles einen Teil des Ohrs ab?',
        ['Paul Gauguin', 'Vincent van Gogh', 'Edvard Munch', 'Salvador Dalí'], 1,
        'Van Gogh. Nach Streit mit Gauguin. Verband wurde in Selbstporträts festgehalten. Ein Jahr später Nervenklinik, 1890 Selbstmord.',
        ['Van Gogh', 'Ohr']),
    mc('q-kunst-104', 'kunst', 2,
        'Wer malte im Auftrag von Papst Julius II. die Sixtinische Kapelle in Rom?',
        ['Raffael', 'Michelangelo', 'Botticelli', 'Caravaggio'], 1,
        'Michelangelo (1508–1512). Deckenfresko mit „Erschaffung Adams". 20 Jahre später „Das jüngste Gericht" (Altarwand).',
        ['Michelangelo', 'Sixtina']),
    mc('q-kunst-105', 'kunst', 2,
        'Welches Gemälde von Edvard Munch (1893) zeigt eine Figur mit weit aufgerissenem Mund vor rotem Himmel?',
        ['Melancholie', 'Der Schrei', 'Madonna', 'Angst'], 1,
        'Der Schrei („Skrik"). Vier Versionen. Eine wurde 2012 für 119,9 Mio. $ versteigert. Ikone des Expressionismus.',
        ['Munch', 'Schrei']),
    mc('q-kunst-106', 'kunst', 3,
        'Welcher spanische Surrealist ist bekannt für schmelzende Uhren („Die Beständigkeit der Erinnerung", 1931)?',
        ['Joan Miró', 'Salvador Dalí', 'Francisco Goya', 'Antoni Tàpies'], 1,
        'Salvador Dalí. Schmelzende Uhren symbolisieren Relativität der Zeit. Berühmt für Zwirbelschnurrbart und exzentrische Auftritte.',
        ['Dalí', 'Surrealismus']),
    mc('q-kunst-107', 'kunst', 2,
        'Welche Bewegung entstand um 1863 in Paris und legte Wert auf Lichteindrücke im Freien?',
        ['Romantik', 'Impressionismus', 'Barock', 'Realismus'], 1,
        'Impressionismus. Name kam von Monets „Impression, soleil levant" (1872). Vertreter: Monet, Renoir, Degas, Pissarro.',
        ['Impressionismus', 'Monet']),
    mc('q-kunst-108', 'kunst', 3,
        'Wer malte um 1665 „Das Mädchen mit dem Perlenohrring"?',
        ['Rembrandt', 'Rubens', 'Johannes Vermeer', 'Frans Hals'], 2,
        'Vermeer, niederländisches Goldenes Zeitalter. Hängt im Mauritshuis (Den Haag). Wird auch „Mona Lisa des Nordens" genannt.',
        ['Vermeer', 'Perlenohrring']),
    mc('q-kunst-109', 'kunst', 2,
        'Was bezeichnet die „Pop Art"?',
        [
            'Volksmusik-Kunst',
            'Kunstrichtung mit Motiven der Konsum-/Popkultur',
            'Alte religiöse Malerei',
            'Straßenkunst',
        ], 1,
        'Pop Art (~1955–1970) — Andy Warhol, Roy Lichtenstein. Alltagsobjekte (Suppendosen, Comics) als Kunst. Kritik & Feier des Konsums.',
        ['Pop Art', 'Warhol']),
    mc('q-kunst-110', 'kunst', 3,
        'Welcher Maler schuf die vier Versionen von Sonnenblumen-Vasen 1888 in Arles?',
        ['Claude Monet', 'Vincent van Gogh', 'Paul Cézanne', 'Henri Matisse'], 1,
        'Van Gogh — Sonnenblumen sollten Gauguins Zimmer schmücken. Serie in Arles/Saint-Rémy. Chromgelb wird mit der Zeit dunkler.',
        ['Sonnenblumen', 'Van Gogh']),
    mc('q-kunst-111', 'kunst', 3,
        'Wer schuf um 1500 die Bronze-Skulptur „Der Denker" auf einem Felsen sitzend?',
        ['Michelangelo', 'Auguste Rodin', 'Donatello', 'Bernini'], 1,
        'Rodin, ursprünglich Teil des „Höllentors" (nach Dantes Inferno). Erste Version 1880. Rund 25 originale Güsse existieren.',
        ['Rodin', 'Denker']),
    mc('q-kunst-112', 'kunst', 2,
        'Welche mexikanische Malerin ist berühmt für Selbstporträts mit zusammengewachsenen Augenbrauen?',
        ['Frida Kahlo', 'Georgia O\'Keeffe', 'Louise Bourgeois', 'Marina Abramović'], 0,
        'Frida Kahlo (1907–1954). Nach schwerem Busunfall malte sie viel aus dem Bett. Verheiratet mit Diego Rivera. Ikone mexikanischer Kultur.',
        ['Frida Kahlo', 'Selbstporträt']),
    mc('q-kunst-113', 'kunst', 3,
        'Welcher deutsche Maler ist berühmt für „Wanderer über dem Nebelmeer" (1818)?',
        ['Albrecht Dürer', 'Caspar David Friedrich', 'Franz Marc', 'Emil Nolde'], 1,
        'Friedrich. Ikone der deutschen Romantik. Rückenfigur blickt in Nebelmeer der Sächsischen Schweiz. Kunsthalle Hamburg.',
        ['Friedrich', 'Romantik']),
    mc('q-kunst-114', 'kunst', 2,
        'Welche Farbenmischung ergibt die drei Grundfarben der subtraktiven Farbmischung (Druck)?',
        [
            'RGB (Rot, Grün, Blau)',
            'CMY (Cyan, Magenta, Gelb)',
            'RYB (Rot, Gelb, Blau)',
            'Schwarz, Weiß, Grau',
        ], 1,
        'Subtraktiv (Farbe absorbiert Licht) = Cyan, Magenta, Gelb (+ Schwarz = CMYK). Additiv (Licht) = RGB. RYB ist ältere Malerlehre.',
        ['Farben', 'CMYK']),
    mc('q-kunst-115', 'kunst', 3,
        'Wer entwarf die Gothic-Skulpturen der Kathedrale Notre-Dame de Paris? (Verallgemeinernd: welcher Baustil?)',
        ['Barock', 'Gotik', 'Romanik', 'Klassizismus'], 1,
        'Gotik (12.–16. Jh.). Merkmale: Spitzbögen, Kreuzrippengewölbe, hohe Fenster mit Buntglas. Notre-Dame Paris ab 1163 gebaut.',
        ['Gotik', 'Notre-Dame']),
    mc('q-kunst-116', 'kunst', 2,
        'Wer malte „Die Nachtwache" (1642), das berühmteste Werk des niederländischen Barock?',
        ['Rubens', 'Rembrandt', 'Vermeer', 'Frans Hals'], 1,
        'Rembrandt van Rijn. Gruppenporträt einer Amsterdamer Bürgerwehr. Hängt im Rijksmuseum. Ursprünglich am Tag spielend — wurde durch Firnis dunkel.',
        ['Rembrandt', 'Nachtwache']),
    mc('q-kunst-117', 'kunst', 3,
        'Welche Künstlerbewegung entstand 1919 in Weimar (Bauhaus) und verband Design, Handwerk und Kunst?',
        ['Jugendstil', 'Bauhaus', 'Wiener Werkstätten', 'De Stijl'], 1,
        'Bauhaus, gegründet von Walter Gropius. „Form folgt Funktion". 1933 von Nazis geschlossen — Einfluss weltweit auf Design & Architektur.',
        ['Bauhaus', 'Weimar']),
    mc('q-kunst-118', 'kunst', 4,
        'Wer entwarf 1483–1486 das Fresko „Die Erschaffung Adams" in der Sixtinischen Kapelle mit den fast berührenden Fingern?',
        ['Raffael', 'Michelangelo', 'Botticelli', 'Perugino'], 1,
        'Michelangelo, im Deckenfresko (1508–1512, nicht 1483). Zentrales Motiv: Finger Gottes berührt fast Adams Hand — Ikone der Renaissance.',
        ['Michelangelo', 'Adam']),
    mc('q-kunst-119', 'kunst', 3,
        'Welche New Yorker Kunstbewegung der 1940er/50er verhalf Jackson Pollock (Drip Painting) zu Weltruhm?',
        [
            'Cubism',
            'Abstract Expressionism',
            'Minimalism',
            'Dadaism',
        ], 1,
        'Abstrakter Expressionismus (Ab-Ex). Pollock, Rothko, de Kooning. Bewegte Amerika ins Zentrum der Kunstwelt (davor Paris).',
        ['Pollock', 'Abstract Expressionism']),
]

# LITERATUR & BÜCHER (20)
NEW_QUESTIONS += [
    mc('q-literatur-100', 'literatur', 1,
        'Wer schrieb „Romeo und Julia"?',
        ['Charles Dickens', 'William Shakespeare', 'John Milton', 'Oscar Wilde'], 1,
        'Shakespeare (~1595). Tragödie in Verona. Auch bekannt für „Hamlet", „Macbeth", „König Lear". Verfasst zwischen 1590 und 1613.',
        ['Shakespeare', 'Romeo']),
    mc('q-literatur-101', 'literatur', 1,
        'Wer schrieb die „Harry Potter"-Bücher?',
        ['Roald Dahl', 'J. K. Rowling', 'Enid Blyton', 'Astrid Lindgren'], 1,
        'Rowling. 7 Bände 1997–2007. Über 600 Mio. verkauft. Übersetzt in >80 Sprachen. Beginn: „Der Stein der Weisen".',
        ['Rowling', 'Harry Potter']),
    mc('q-literatur-102', 'literatur', 1,
        'Welcher deutsche Dichter schrieb „Faust"?',
        ['Friedrich Schiller', 'Johann Wolfgang von Goethe', 'Heinrich Heine', 'Thomas Mann'], 1,
        'Goethe. Teil I 1808, Teil II 1832. Faust schließt Pakt mit Mephisto. Berühmter Vers: „Was die Welt im Innersten zusammenhält".',
        ['Goethe', 'Faust']),
    mc('q-literatur-103', 'literatur', 2,
        'Welcher Roman von George Orwell (1949) beschreibt einen totalitären Staat mit Big Brother?',
        ['Farm der Tiere', '1984', 'Schöne neue Welt', 'Fahrenheit 451'], 1,
        '„1984". Newspeak, Doublethink, „Big Brother is watching". Dystopie. Orwell schrieb es todkrank auf der Insel Jura.',
        ['Orwell', '1984']),
    mc('q-literatur-104', 'literatur', 2,
        'Wer verfasste den russischen Roman „Krieg und Frieden" (1869)?',
        ['Fjodor Dostojewski', 'Lew Tolstoi', 'Anton Tschechow', 'Iwan Turgenjew'], 1,
        'Tolstoi. 1 200+ Seiten, Napoleon-Feldzug 1805–1812. Über 500 Figuren. Gilt als einer der größten Romane der Weltliteratur.',
        ['Tolstoi', 'Krieg']),
    mc('q-literatur-105', 'literatur', 2,
        'Welcher Roman von Gabriel García Márquez (1967) begründete den magischen Realismus?',
        [
            'Die Liebe in den Zeiten der Cholera',
            'Hundert Jahre Einsamkeit',
            'Der Fremde',
            'Chronik eines angekündigten Todes',
        ], 1,
        '„Hundert Jahre Einsamkeit" — Geschichte der Familie Buendía in Macondo. Kolumbianischer Autor, Nobelpreis 1982.',
        ['García Márquez', 'Nobel']),
    mc('q-literatur-106', 'literatur', 2,
        'Welcher Roman beginnt mit „Man muss sich Sisyphos als glücklichen Menschen vorstellen"? (Autor?)',
        ['Franz Kafka', 'Albert Camus', 'Jean-Paul Sartre', 'Hermann Hesse'], 1,
        'Albert Camus, „Der Mythos von Sisyphos" (1942). Philosophischer Essay. Camus erhielt 1957 den Nobelpreis für Literatur.',
        ['Camus', 'Sisyphos']),
    mc('q-literatur-107', 'literatur', 2,
        'Wer verfasste „Die Verwandlung", in der Gregor Samsa als Käfer erwacht?',
        ['Thomas Mann', 'Hermann Hesse', 'Franz Kafka', 'Robert Musil'], 2,
        'Kafka (1915). Prager Schriftsteller. „Kafkaesk" = bedrohlich-absurd. Weitere Werke: „Der Process", „Das Schloss", „Der Hungerkünstler".',
        ['Kafka', 'Verwandlung']),
    mc('q-literatur-108', 'literatur', 3,
        'Welches englische Epos beschreibt Odysseus\' zehnjährige Heimkehr?',
        ['Ilias', 'Odyssee', 'Aeneis', 'Beowulf'], 1,
        'Homer, „Odyssee" (~8. Jh. v. Chr.). 24 Gesänge. Odysseus, König von Ithaka, kämpft mit Kyklopen, Sirenen, Skylla & Charybdis.',
        ['Homer', 'Odyssee']),
    mc('q-literatur-109', 'literatur', 2,
        'Welcher schwedische Autor schrieb „Pippi Langstrumpf"?',
        ['Selma Lagerlöf', 'Astrid Lindgren', 'Tove Jansson', 'Hans Christian Andersen'], 1,
        'Astrid Lindgren (1907–2002). „Pippi" ab 1945. Weitere: „Michel aus Lönneberga", „Die Kinder von Bullerbü", „Ronja Räubertochter".',
        ['Lindgren', 'Pippi']),
    mc('q-literatur-110', 'literatur', 3,
        'Wer schrieb „Der Herr der Ringe" und schuf Mittelerde?',
        [
            'C. S. Lewis',
            'J. R. R. Tolkien',
            'Terry Pratchett',
            'Ursula K. Le Guin',
        ], 1,
        'Tolkien, britischer Sprachwissenschaftler in Oxford. „LOTR" (1954/55). Vorgeschichte: „Der Hobbit" (1937). Weitere: „Silmarillion".',
        ['Tolkien', 'Mittelerde']),
    mc('q-literatur-111', 'literatur', 3,
        'Welcher Autor gilt als Vater des modernen Kriminalromans („Mordsystem" mit Sherlock Holmes)?',
        ['Edgar Allan Poe', 'Arthur Conan Doyle', 'Agatha Christie', 'Wilkie Collins'], 1,
        'Conan Doyle. Holmes debütiert in „A Study in Scarlet" (1887). 4 Romane, 56 Kurzgeschichten. Watson als Erzähler. Poe wird als Wegbereiter genannt.',
        ['Sherlock Holmes', 'Doyle']),
    mc('q-literatur-112', 'literatur', 2,
        'Welche Autorin schrieb „Stolz und Vorurteil" (1813)?',
        ['Charlotte Brontë', 'Jane Austen', 'Emily Dickinson', 'Virginia Woolf'], 1,
        'Jane Austen (GB, 1775–1817). Weitere: „Sinn und Sinnlichkeit", „Emma". Roman folgt Elizabeth Bennet & Mr. Darcy.',
        ['Austen', 'Pride']),
    mc('q-literatur-113', 'literatur', 3,
        'Welcher Roman von Fjodor Dostojewski (1866) hat einen St. Petersburger Studenten als Mörder im Zentrum?',
        [
            'Die Brüder Karamasow',
            'Schuld und Sühne (Verbrechen und Strafe)',
            'Der Idiot',
            'Der Spieler',
        ], 1,
        '„Schuld und Sühne" (russ. „Prestuplenie i nakazanie"). Raskolnikov ermordet eine Pfandleiherin. Studie über Moral und Schuld.',
        ['Dostojewski', 'Raskolnikov']),
    mc('q-literatur-114', 'literatur', 3,
        'Welcher Autor schrieb „Der große Gatsby" (1925), Sinnbild der Roaring Twenties?',
        ['Ernest Hemingway', 'F. Scott Fitzgerald', 'John Steinbeck', 'William Faulkner'], 1,
        'Fitzgerald. Spiel in Long Island. Zentrales Bild: grünes Licht am Ende der Anlegestelle. Symbol des amerikanischen Traums (& Zerbrechlichkeit).',
        ['Fitzgerald', 'Gatsby']),
    mc('q-literatur-115', 'literatur', 2,
        'Welche Reihe von Isaac Asimov formuliert die drei Robotergesetze?',
        ['Foundation', 'Robot-Zyklus (I, Robot)', 'Nemesis', 'Empire'], 1,
        'Robot-Zyklus (ab 1950). 1. Kein Mensch verletzen; 2. Menschen gehorchen (außer 1); 3. Selbst schützen (außer 1&2). Foundation-Serie ist eigener Zyklus.',
        ['Asimov', 'Roboter']),
    mc('q-literatur-116', 'literatur', 3,
        'Wer verfasste „Die göttliche Komödie" (~1320) mit Inferno, Purgatorio und Paradiso?',
        ['Francesco Petrarca', 'Dante Alighieri', 'Giovanni Boccaccio', 'Torquato Tasso'], 1,
        'Dante Alighieri (1265–1321). Wegweisend für italienische Sprache. Reise durch Hölle, Fegefeuer, Himmel, geführt von Vergil und Beatrice.',
        ['Dante', 'Inferno']),
    mc('q-literatur-117', 'literatur', 3,
        'Wer war die englische Krimi-Autorin, die Hercule Poirot und Miss Marple erfand?',
        ['Dorothy Sayers', 'Agatha Christie', 'Ngaio Marsh', 'P. D. James'], 1,
        'Christie (1890–1976). „Mord im Orient-Express", „Zehn kleine Negerlein" (heute „And Then There Were None"). Meistverkaufte Roman-Autorin aller Zeiten.',
        ['Christie', 'Poirot']),
    mc('q-literatur-118', 'literatur', 4,
        'Welcher deutschsprachige Roman von Thomas Mann (1901) erzählt Verfall der Lübecker Kaufmannsfamilie?',
        ['Der Zauberberg', 'Buddenbrooks', 'Doktor Faustus', 'Der Tod in Venedig'], 1,
        '„Buddenbrooks" — Mann war erst 26. Ein Grund für Nobelpreis 1929. Schilderung des Bürgertums im 19. Jh.',
        ['Thomas Mann', 'Buddenbrooks']),
    mc('q-literatur-119', 'literatur', 3,
        'Welcher amerikanische Autor schrieb „Der alte Mann und das Meer" (1952)?',
        ['William Faulkner', 'Ernest Hemingway', 'John Steinbeck', 'Truman Capote'], 1,
        'Hemingway. Novelle über kubanischen Fischer Santiago. Pulitzer 1953, Nobelpreis 1954. Charakteristisch: knappe, klare Prosa.',
        ['Hemingway', 'Meer']),
]


def main() -> int:
    with QUESTIONS_PATH.open('r', encoding='utf-8') as f:
        existing = json.load(f)
    existing_ids = {q['id'] for q in existing}
    to_add = [q for q in NEW_QUESTIONS if q['id'] not in existing_ids]
    if not to_add:
        print('Keine neuen Fragen.')
        return 0
    for q in to_add:
        assert len(q['options']) == 4, q['id']
        assert 0 <= q['correctIndex'] < 4, q['id']
    merged = existing + to_add
    with QUESTIONS_PATH.open('w', encoding='utf-8') as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
        f.write('\n')
    from collections import Counter
    print(f'✓ {len(to_add)} neue Fragen ergänzt (jetzt {len(merged)} insgesamt).')
    for t, c in sorted(Counter(q['topic'] for q in to_add).items()):
        print(f'  + {t:<14} {c}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
