#!/usr/bin/env python3
"""Batch 6: theater, architektur, comics, anime (80 Fragen)."""
from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
QUESTIONS_PATH = ROOT / 'packages' / 'shared' / 'src' / 'data' / 'questions.json'
NOW = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
MC_MODES = ['category-duel', 'flash', 'player-spotlight', 'sprinter',
            'points-ladder', 'category-board', 'duel-1v1', 'elimination', 'experts']


def mc(qid, topic, difficulty, question, options, correct, gm, tags, category='allgemeinbildung'):
    return {'id': qid, 'type': 'multiple-choice', 'status': 'approved',
        'category': category, 'topic': topic, 'difficulty': difficulty,
        'question': question, 'options': options, 'correctIndex': correct,
        'gmNote': gm, 'tags': tags, 'compatibleModes': MC_MODES,
        'timeScope': 'timeless', 'aiGenerated': True,
        'createdAt': NOW, 'updatedAt': NOW}


NEW_QUESTIONS = []

# THEATER & BÜHNE (20)
NEW_QUESTIONS += [
    mc('q-theater-100', 'theater', 1,
        'Welche Stadt ist Sitz der berühmten Musical-Meile „Broadway"?',
        ['London', 'New York', 'Paris', 'Wien'], 1,
        'Broadway = Straße im Theater District von Manhattan (New York). 41 Theater mit 500+ Sitzen zählen als „Broadway".',
        ['Broadway', 'NYC']),
    mc('q-theater-101', 'theater', 1,
        'Welches Musical mit „Memory" spielt in einer Müllhalde voller singender Katzen?',
        ['Cats', 'Chicago', 'Hairspray', 'Rent'], 0,
        'Andrew Lloyd Webbers „Cats" (1981), basierend auf T. S. Eliots „Old Possum\'s Book of Practical Cats". 21 Jahre am Broadway.',
        ['Cats', 'Lloyd Webber']),
    mc('q-theater-102', 'theater', 2,
        'Welches Musical basiert auf Victor Hugos Roman und spielt in der Französischen Revolution?',
        ['Les Misérables', 'Miss Saigon', 'Evita', 'Chicago'], 0,
        '„Les Misérables" (1980). Jean Valjean, Javert, Cosette. Meistgesehene Musical-Adaption weltweit — über 130 Mio. Zuschauer.',
        ['Les Mis', 'Hugo']),
    mc('q-theater-103', 'theater', 2,
        'Wer schrieb das antike Drama „Ödipus" (~429 v. Chr.)?',
        ['Aischylos', 'Sophokles', 'Euripides', 'Aristophanes'], 1,
        'Sophokles. Zusammen mit Aischylos & Euripides einer der drei großen Tragödiendichter des klassischen Athens.',
        ['Sophokles', 'Ödipus']),
    mc('q-theater-104', 'theater', 2,
        'Welches Wiener Theater ist eine der wichtigsten Bühnen des deutschsprachigen Raums?',
        ['Deutsches Theater', 'Burgtheater', 'Berliner Ensemble', 'Schaubühne'], 1,
        'Burgtheater (gegr. 1741) — historisch „Nationaltheater". Kaiser Franz Joseph eröffnete 1888 neuen Bau am Ring.',
        ['Burgtheater', 'Wien']),
    mc('q-theater-105', 'theater', 2,
        'Was ist das Kabuki-Theater?',
        [
            'Chinesische Oper',
            'Japanisches Theater mit stilisiertem Tanz & Gesang',
            'Koreanisches Puppentheater',
            'Indisches Tanzdrama',
        ], 1,
        'Kabuki (Japan, ~1600). Männliche Darsteller (auch Frauenrollen = onnagata), extrem stilisierte Kostüme, weiße Schminke.',
        ['Kabuki', 'Japan']),
    mc('q-theater-106', 'theater', 3,
        'Wer schrieb „Warten auf Godot" (1953), Schlüsselstück des absurden Theaters?',
        ['Eugène Ionesco', 'Samuel Beckett', 'Jean-Paul Sartre', 'Harold Pinter'], 1,
        'Samuel Beckett (IR/FR). Nobelpreis 1969. Zwei Landstreicher warten vergeblich auf „Godot". Ionesco war anderer Absurdisten-Autor.',
        ['Beckett', 'Godot']),
    mc('q-theater-107', 'theater', 2,
        'Was ist die „Commedia dell\'arte"?',
        [
            'Moderne Broadway-Show',
            'Italienische Stegreif-Komödie mit festen Figuren (Arlecchino, Colombina)',
            'Deutsches Volkstheater',
            'Englische Music Hall',
        ], 1,
        'Commedia dell\'arte (16.–18. Jh.). Fahrende Truppen, Masken, feste Typen (Zanni). Beeinflusste Molière, Goldoni, Punch & Judy.',
        ['Commedia', 'Italien']),
    mc('q-theater-108', 'theater', 3,
        'Welche berühmte Londoner Bühne wurde 1997 als Nachbau von Shakespeares Theater eröffnet?',
        ['Old Vic', 'Globe Theatre', 'National Theatre', 'Royal Court'], 1,
        'Globe Theatre. Original 1599, brannte 1613 ab. Rekonstruktion von Sam Wanaker eröffnet 1997 an der Themse. Runde Freilichtbühne.',
        ['Globe', 'Shakespeare']),
    mc('q-theater-109', 'theater', 2,
        'Wer schrieb die deutsche Nationaltragödie „Die Räuber" (1781)?',
        ['Goethe', 'Schiller', 'Lessing', 'Kleist'], 1,
        'Friedrich Schiller (Sturm & Drang). Karl Moor wird Räuberhauptmann. Uraufführung Mannheim 1782 — Schiller floh aus Stuttgart.',
        ['Schiller', 'Räuber']),
    mc('q-theater-110', 'theater', 2,
        'Was ist ein „Musical"?',
        [
            'Konzert mit Sängern',
            'Bühnenwerk mit Handlung, Gesang, Tanz und Musik',
            'Operette ohne Text',
            'Filmmusik',
        ], 1,
        'Musical entstand in USA um 1900. Vorläufer: Operette & Vaudeville. Größte Bühnen: Broadway (NYC) & West End (London).',
        ['Musical', 'Bühne']),
    mc('q-theater-111', 'theater', 3,
        'Wer schuf das „epische Theater" mit V-Effekt (Verfremdungseffekt)?',
        ['Konstantin Stanislawski', 'Bertolt Brecht', 'Antonin Artaud', 'Peter Brook'], 1,
        'Bertolt Brecht (DE, 1898–1956). „Dreigroschenoper", „Mutter Courage". V-Effekt: Zuschauer soll distanziert reflektieren, nicht mitfühlen.',
        ['Brecht', 'V-Effekt']),
    mc('q-theater-112', 'theater', 2,
        'Welches Musical von Andrew Lloyd Webber spielt in der Pariser Oper?',
        ['Cats', 'Das Phantom der Oper', 'Evita', 'Starlight Express'], 1,
        '„Phantom of the Opera" (1986). Basierend auf Gaston Leroux\' Roman (1910). Längstes Musical am Broadway (bis 2023, 35 Jahre).',
        ['Phantom', 'Lloyd Webber']),
    mc('q-theater-113', 'theater', 3,
        'Welcher russische Regisseur (1863–1938) entwickelte das „Method Acting" / Stanislawski-System?',
        ['Meyerhold', 'Stanislawski', 'Tschechow', 'Nemirowitsch-Dantschenko'], 1,
        'Konstantin Stanislawski, Mitgründer des Moskauer Künstlertheaters (MChAT). System: Emotional Memory, Given Circumstances.',
        ['Stanislawski', 'Method']),
    mc('q-theater-114', 'theater', 2,
        'Was ist eine „Oper" im Unterschied zum Sprechtheater?',
        [
            'Ganz gesprochenes Stück',
            'Bühnenwerk, in dem die Handlung überwiegend gesungen wird',
            'Ein-Personen-Stück',
            'Tanztheater',
        ], 1,
        'Oper: Text (Libretto) wird gesungen, meist Rezitativ + Arie. Ursprung um 1600 in Florenz (Camerata). Wichtige Häuser: La Scala, Wiener Staatsoper.',
        ['Oper', 'Gesang']),
    mc('q-theater-115', 'theater', 3,
        'Welches Broadway-Musical von Lin-Manuel Miranda (2015) erzählt die Geschichte eines Gründervaters der USA mit HipHop?',
        ['In the Heights', 'Hamilton', 'Wicked', 'Dear Evan Hansen'], 1,
        'Hamilton — Leben von Alexander Hamilton. 11 Tony Awards 2016. Multiethnische Besetzung mit HipHop, R&B und Broadway-Stil.',
        ['Hamilton', 'Miranda']),
    mc('q-theater-116', 'theater', 3,
        'Was bezeichnet „Off-Broadway"?',
        [
            'Straße abseits des Broadway',
            'NYC-Theater mit 100–499 Sitzen, oft experimentell',
            'Berühmte Bar',
            'Filmfestival',
        ], 1,
        'Off-Broadway: Theater mit 100–499 Sitzen. Off-Off-Broadway: unter 100 (avantgardistisch). Broadway: 500+.',
        ['Off-Broadway', 'NYC']),
    mc('q-theater-117', 'theater', 4,
        'Welches Musical war ab 1975 hinter „Cats" das nächstlängste Broadway-Musical der 20. Jh., basierend auf Casting-Chören?',
        ['A Chorus Line', 'Grease', 'Annie', '42nd Street'], 0,
        '„A Chorus Line" (1975). Läuft 15 Jahre am Broadway. Pulitzer Drama 1976. Basiert auf Interviews mit Broadway-Tänzer:innen.',
        ['Chorus Line', 'Broadway']),
    mc('q-theater-118', 'theater', 2,
        'Welche Farbe hat traditionell der Vorhang der Wiener Staatsoper?',
        ['Rot', 'Blau', 'Grün', 'Gold'], 0,
        'Roter Vorhang (Samt). Wiener Staatsoper wurde 1869 eröffnet. Ballsaison: „Opernball" ist gesellschaftliches Großereignis.',
        ['Staatsoper', 'Wien']),
    mc('q-theater-119', 'theater', 3,
        'Was ist Improvisationstheater?',
        [
            'Auswendiggelernte Rollen',
            'Szenen werden spontan ohne Skript gespielt',
            'Reine Pantomime',
            'Ein Solo-Format',
        ], 1,
        'Improtheater — Szenen entstehen live. Prinzipien: „Yes, and…", „Angebote annehmen". Bekannte Formate: Theatersport, Harold, Whose Line Is It Anyway.',
        ['Impro', 'Bühne']),
]

# ARCHITEKTUR & DESIGN (20)
NEW_QUESTIONS += [
    mc('q-architektur-100', 'architektur', 1,
        'Welches Bauwerk in Paris wurde 1889 zur Weltausstellung eröffnet und ist 330 m hoch?',
        ['Notre-Dame', 'Eiffelturm', 'Louvre', 'Arc de Triomphe'], 1,
        'Eiffelturm — Gustave Eiffel. Ursprünglich 20 Jahre geplant, sollte abgerissen werden. Jährlich 7 Mio. Besucher.',
        ['Eiffelturm', 'Paris']),
    mc('q-architektur-101', 'architektur', 1,
        'Welche Kirche in Rom ist der Sitz des Papstes und mit 730 m² Grundfläche eine der größten Basiliken der Welt?',
        ['Petersdom', 'Santa Maria Maggiore', 'San Giovanni in Laterano', 'Sagrada Familia'], 0,
        'Petersdom (Basilika Sankt Peter). Bauzeit 1506–1626. Michelangelo entwarf die Kuppel. Bramante, Bernini, Maderno beteiligt.',
        ['Petersdom', 'Vatikan']),
    mc('q-architektur-102', 'architektur', 2,
        'Wer entwarf die Sagrada Familia in Barcelona (Baubeginn 1882)?',
        ['Antoni Gaudí', 'Frank Lloyd Wright', 'Le Corbusier', 'Norman Foster'], 0,
        'Gaudí. Katalanische Modernisme. Noch nicht fertig (geplant ~2026). Weitere Werke: Casa Batlló, Park Güell.',
        ['Gaudí', 'Barcelona']),
    mc('q-architektur-103', 'architektur', 2,
        'Was ist die „Kuppel" (Dome) im Bauwerk?',
        [
            'Rechteckiges Dach',
            'Halbkugelförmiges Gewölbe über einem Raum',
            'Turm',
            'Portalgang',
        ], 1,
        'Kuppel (Dom, Dome). Beispiele: Pantheon Rom, Petersdom, Hagia Sophia Istanbul, Kapitol Washington. Größte moderne: Singapore National Stadium (310 m).',
        ['Kuppel', 'Dom']),
    mc('q-architektur-104', 'architektur', 3,
        'Welcher amerikanische Architekt entwarf „Fallingwater" (1935) über einem Wasserfall?',
        ['Louis Sullivan', 'Frank Lloyd Wright', 'Philip Johnson', 'I. M. Pei'], 1,
        'Wright (1867–1959). Fallingwater in Pennsylvania. Weitere: Guggenheim NY, Robie House. Pionier der „Organischen Architektur".',
        ['Wright', 'Fallingwater']),
    mc('q-architektur-105', 'architektur', 2,
        'Welches indische Mausoleum ließ Shah Jahan 1632–1653 für seine Frau erbauen?',
        ['Roter Fort', 'Taj Mahal', 'Amber Fort', 'Qutub Minar'], 1,
        'Taj Mahal in Agra für Mumtaz Mahal. Weißer Marmor mit Halbedelsteinen. UNESCO seit 1983. Bau: ~20 000 Arbeiter.',
        ['Taj Mahal', 'Agra']),
    mc('q-architektur-106', 'architektur', 2,
        'Was bezeichnet der Baustil „Bauhaus"?',
        [
            'Verspielter Barock',
            'Reduziert, funktional, geometrisch (Weimar 1919)',
            'Neugotik',
            'Naturbaustil',
        ], 1,
        'Bauhaus — Walter Gropius, Weimar/Dessau/Berlin. „Form follows function". Beeinflusste moderne Architektur, Design & Typografie weltweit.',
        ['Bauhaus', 'Gropius']),
    mc('q-architektur-107', 'architektur', 3,
        'Wer entwarf das Guggenheim-Museum in Bilbao (1997) mit welligen Titan-Fassaden?',
        ['Zaha Hadid', 'Frank Gehry', 'Renzo Piano', 'Rem Koolhaas'], 1,
        'Frank Gehry (CA/USA). Wahrzeichen des Dekonstruktivismus. Löste den „Bilbao-Effekt" aus (Städte durch Star-Architektur ins Rampenlicht).',
        ['Gehry', 'Bilbao']),
    mc('q-architektur-108', 'architektur', 2,
        'Wie hoch ist der Burj Khalifa in Dubai, das höchste Gebäude der Welt (2010)?',
        ['~500 m', '~700 m', '~830 m', '~1 000 m'], 2,
        'Burj Khalifa 828 m, 163 Stockwerke. Architekt: Skidmore, Owings & Merrill (Adrian Smith). Vorheriger Rekord: Taipei 101 (508 m).',
        ['Burj Khalifa', 'Dubai']),
    mc('q-architektur-109', 'architektur', 3,
        'Welcher Franzose (1887–1965) formulierte „Fünf Punkte einer neuen Architektur" und prägte Modernismus?',
        ['Auguste Perret', 'Le Corbusier', 'Jean Nouvel', 'Christian de Portzamparc'], 1,
        'Le Corbusier (Charles-Édouard Jeanneret). Fünf Punkte: Pilotis, Dachgarten, freier Grundriss, freie Fassade, Langfenster. Villa Savoye.',
        ['Le Corbusier', 'Modernismus']),
    mc('q-architektur-110', 'architektur', 3,
        'Was ist ein „Ionischer" Säulenstil?',
        [
            'Schlicht, ohne Kapitell',
            'Kapitell mit Voluten (Schnecken) — griechische Ordnung',
            'Mit Blattornamenten',
            'Aus Marmor',
        ], 1,
        'Drei griech. Ordnungen: Dorisch (schlicht), Ionisch (Voluten), Korinthisch (Akanthusblätter). Ionisch = Bsp. Erechtheion in Athen.',
        ['Ionisch', 'Säule']),
    mc('q-architektur-111', 'architektur', 2,
        'Welche Wiener Prachtstraße wurde 1857 nach Schleifung der Stadtmauer angelegt?',
        ['Kärntner Straße', 'Ringstraße', 'Mariahilfer Straße', 'Praterstraße'], 1,
        'Ringstraße (1857 durch Franz Joseph). 5,3 km rund um Innenstadt. Prunkbauten: Rathaus, Parlament, Staatsoper, Burgtheater.',
        ['Ringstraße', 'Wien']),
    mc('q-architektur-112', 'architektur', 4,
        'Wer war die erste Frau, die 2004 den Pritzker-Preis (Architektur-Nobel) erhielt?',
        ['Kazuyo Sejima', 'Zaha Hadid', 'Denise Scott Brown', 'Jeanne Gang'], 1,
        'Zaha Hadid (IR/GB, 1950–2016). Dekonstruktivistin. Bekannte Werke: London Aquatics Centre, Heydar-Aliyev-Zentrum Baku, Guangzhou Opera House.',
        ['Hadid', 'Pritzker']),
    mc('q-architektur-113', 'architektur', 2,
        'Welche Insel-Kirche in Frankreich thront auf einem Granitfelsen mit Gezeitenzugang?',
        ['Skellig Michael', 'Mont-Saint-Michel', 'Île de Ré', 'Fastnet'], 1,
        'Mont-Saint-Michel, Normandie. Abteikirche (11. Jh.). Ebbe/Flut trennen es vom Festland. UNESCO seit 1979.',
        ['Mont-Saint-Michel', 'Frankreich']),
    mc('q-architektur-114', 'architektur', 3,
        'Was ist ein „Flügelaltar"?',
        [
            'Fluginstrument-Sammlung',
            'Klappbarer Altaraufsatz mit bemalten Flügeln',
            'Ruhepodest',
            'Musikinstrument',
        ], 1,
        'Flügelaltar (Retabel). Zentral in gotischen Kirchen. Berühmt: Isenheimer Altar (Grünewald, ~1512), Genter Altar (van Eyck, 1432).',
        ['Flügelaltar', 'Gotik']),
    mc('q-architektur-115', 'architektur', 2,
        'Welche berühmte Oper hat eine muschelförmige, weiße Dachlandschaft am Hafen?',
        ['Sydney Opera House', 'La Scala Mailand', 'Metropolitan Opera NYC', 'Palais Garnier Paris'], 0,
        'Sydney Opera House, entworfen von Jørn Utzon (DK). Eröffnung 1973. UNESCO 2007. Ikone Australiens.',
        ['Sydney', 'Opera']),
    mc('q-architektur-116', 'architektur', 3,
        'Was ist eine „Pagode"?',
        [
            'Runde Kirche',
            'Turmartiges Bauwerk mit gestuften Dächern (Ostasien)',
            'Islamisches Minarett',
            'Kloster',
        ], 1,
        'Pagode — buddhistischer Tempelturm, meist 3, 5, 7 oder 9 Stockwerke. Chinesische, japanische und südostasiatische Formen unterscheiden sich stark.',
        ['Pagode', 'Ostasien']),
    mc('q-architektur-117', 'architektur', 3,
        'Welcher New Yorker Bahnhof wurde 1913 im Beaux-Arts-Stil eröffnet und hat einen berühmten Deckenhimmel?',
        ['Penn Station', 'Grand Central Terminal', 'Union Station', 'Port Authority'], 1,
        'Grand Central Terminal. 44 Gleise auf 2 Ebenen. Deckenhimmel: Sternbilder in Gold auf Türkis (irrtümlich spiegelverkehrt).',
        ['Grand Central', 'NYC']),
    mc('q-architektur-118', 'architektur', 3,
        'Wer entwarf 1907 das Palais Stoclet in Brüssel und begründete den Wiener Jugendstil?',
        ['Adolf Loos', 'Josef Hoffmann', 'Otto Wagner', 'Josef Olbrich'], 1,
        'Josef Hoffmann, Mitgründer der Wiener Werkstätte. Palais Stoclet ist UNESCO. Innenausstattung u. a. mit Gustav Klimt.',
        ['Hoffmann', 'Palais Stoclet']),
    mc('q-architektur-119', 'architektur', 2,
        'Was bedeutet der Fachbegriff „Fassade"?',
        [
            'Dachkonstruktion',
            'Sichtbare Vorderseite eines Gebäudes',
            'Kellerraum',
            'Grundriss',
        ], 1,
        'Fassade (frz. „façade"). Repräsentative Vorderseite eines Bauwerks. Kann tragende oder rein gestaltende Funktion haben.',
        ['Fassade', 'Bau']),
]

# COMICS & SUPERHELDEN (20)
NEW_QUESTIONS += [
    mc('q-comics-100', 'comics', 1,
        'Welcher Superheld ist der letzte Sohn des Planeten Krypton und arbeitet als Reporter Clark Kent?',
        ['Batman', 'Superman', 'Spider-Man', 'Iron Man'], 1,
        'Superman — Debüt in „Action Comics #1" (1938). Von Jerry Siegel & Joe Shuster. Symbol: rotes „S" auf blauem Trikot.',
        ['Superman', 'Krypton']),
    mc('q-comics-101', 'comics', 1,
        'In welcher Stadt schwingt Batman durch die Nacht?',
        ['Metropolis', 'Central City', 'Gotham City', 'Star City'], 2,
        'Gotham City (fiktives NYC). Alter Ego: Bruce Wayne. Batman debütiert in „Detective Comics #27" (1939) von Bob Kane & Bill Finger.',
        ['Batman', 'Gotham']),
    mc('q-comics-102', 'comics', 2,
        'Welcher Marvel-Held wurde von einer radioaktiven Spinne gebissen?',
        ['Iron Man', 'Hulk', 'Spider-Man', 'Daredevil'], 2,
        'Spider-Man (Peter Parker). Debüt „Amazing Fantasy #15" (1962) von Stan Lee & Steve Ditko. Motto: „With great power comes great responsibility".',
        ['Spider-Man', 'Marvel']),
    mc('q-comics-103', 'comics', 2,
        'Welcher belgische Comic-Held reist mit Snowy (Struppi) um die Welt?',
        ['Asterix', 'Tim (Tintin)', 'Lucky Luke', 'Spirou'], 1,
        'Tim/Tintin (Hergé, 1929). Belgischer Reporter. 24 Alben. Verkauft: ~250 Mio. weltweit.',
        ['Tintin', 'Hergé']),
    mc('q-comics-104', 'comics', 2,
        'Welche zwei Franzosen erschufen 1959 den unbeugsamen Gallier „Asterix"?',
        ['Goscinny & Uderzo', 'Franquin & Peyo', 'Hergé & Jacobs', 'Morris & Charlier'], 0,
        'René Goscinny (Text) & Albert Uderzo (Zeichnung). 40 Alben. Dorfbewohner trotzen Cäsars Römern dank Zaubertrank.',
        ['Asterix', 'Uderzo']),
    mc('q-comics-105', 'comics', 3,
        'Wer ist der Alter Ego des Marvel-Helden Iron Man?',
        ['Bruce Banner', 'Tony Stark', 'Steve Rogers', 'Peter Parker'], 1,
        'Tony Stark — Milliardär, Rüstungserbe. Debüt „Tales of Suspense #39" (1963). MCU-Ära ab 2008 mit Robert Downey Jr.',
        ['Iron Man', 'Stark']),
    mc('q-comics-106', 'comics', 2,
        'Welcher Marvel-Held ist ein grüner Wissenschaftler, der bei Zorn zu einem Monster wird?',
        ['Hulk', 'Loki', 'Green Lantern', 'Beast'], 0,
        'Hulk — Bruce Banner. Gammastrahlung. Debüt 1962 (Stan Lee & Jack Kirby). „Hulk smash!"',
        ['Hulk', 'Banner']),
    mc('q-comics-107', 'comics', 2,
        'Welche berühmte X-Men-Figur hat Adamantium-Krallen und Heilungsfähigkeit?',
        ['Cyclops', 'Wolverine', 'Storm', 'Beast'], 1,
        'Wolverine (Logan). Kanadier, ~200 Jahre alt. Debüt 1974. Berühmter Filmdarsteller: Hugh Jackman (2000–2017).',
        ['Wolverine', 'X-Men']),
    mc('q-comics-108', 'comics', 2,
        'Wer ist Peanuts-Comic-Beagle, der auf seiner Hundehütte tagträumt?',
        ['Odie', 'Snoopy', 'Pluto', 'Scooby-Doo'], 1,
        'Snoopy (Peanuts, Charles M. Schulz). 1950–2000, ~17 900 Strips. Charlie Browns Hund. Häufig als Roter-Baron-Pilot.',
        ['Snoopy', 'Peanuts']),
    mc('q-comics-109', 'comics', 3,
        'Welche „Watchmen"-Antihelden schuf Alan Moore 1986?',
        ['Rorschach & Dr. Manhattan', 'Deadpool', 'Deathstroke', 'John Constantine'], 0,
        'Watchmen (DC, 1986/87). Von Alan Moore (Text) & Dave Gibbons. Nur Graphic Novel im Time-„100 Best Novels"-Ranking (2005).',
        ['Watchmen', 'Moore']),
    mc('q-comics-110', 'comics', 2,
        'Welches Duo ist die belgische Cartoon-Katze und Maus (nicht Tom & Jerry)?',
        ['Fritz und Fratz', 'Fix und Foxi', 'Cubitus', 'Gaston'], 1,
        'Fix und Foxi — deutsche Zwillingsfüchse von Rolf Kauka (1953). Deutscher Konkurrent zu Micky Maus. Bis 1994 wöchentlich.',
        ['Fix und Foxi', 'Kauka']),
    mc('q-comics-111', 'comics', 3,
        'Welcher Manga wurde vom „Godfather of Manga" Osamu Tezuka geschaffen und handelt von einem afrikanischen Kaiser-Löwen?',
        ['Astro Boy', 'Kimba der weiße Löwe', 'Black Jack', 'Buddha'], 1,
        'Kimba (jap. „Jungle Emperor Leo", 1950). Von Tezuka. Beeinflusste Disneys „König der Löwen" (Kontroverse). Astro Boy ist auch Tezuka.',
        ['Tezuka', 'Kimba']),
    mc('q-comics-112', 'comics', 2,
        'Welcher DC-Held ist Prinzessin Diana der Amazonen und trägt goldenen Lasso?',
        ['Supergirl', 'Wonder Woman', 'Black Canary', 'Batwoman'], 1,
        'Wonder Woman — Diana Prince. William Moulton Marston (1941). Themyscira. Golden Age Superheldin. Filme: Gal Gadot.',
        ['Wonder Woman', 'Amazonen']),
    mc('q-comics-113', 'comics', 3,
        'Wer ist Marvels „Merc with a Mouth" mit vierter Wand-Bewusstsein?',
        ['Punisher', 'Deadpool', 'Ghost Rider', 'Blade'], 1,
        'Deadpool (Wade Wilson). Debüt 1991. Rob Liefeld & Fabian Nicieza. Bricht die vierte Wand. Filme: Ryan Reynolds.',
        ['Deadpool', 'Marvel']),
    mc('q-comics-114', 'comics', 2,
        'Welches Comicheft von Bill Watterson zeigt einen Jungen und seinen sprechenden Plüschtiger?',
        ['Peanuts', 'Calvin und Hobbes', 'Garfield', 'Doonesbury'], 1,
        'Calvin und Hobbes (1985–1995). Kult-Strip. Watterson lehnte Merchandising ab, weshalb kein Film oder Plüschtier offiziell existiert.',
        ['Calvin', 'Watterson']),
    mc('q-comics-115', 'comics', 3,
        'Welche Marvel-Heldengruppe rekrutiert Mutanten und wurde 1963 von Stan Lee & Jack Kirby geschaffen?',
        ['Avengers', 'Fantastic Four', 'X-Men', 'Guardians of the Galaxy'], 2,
        'X-Men. Prof. Xavier gegen Magneto. Wolverine, Cyclops, Jean Grey, Storm, Nightcrawler. „Mutant"-Metapher für Diskriminierung.',
        ['X-Men', 'Marvel']),
    mc('q-comics-116', 'comics', 3,
        'Wer ist der DC-Bösewicht mit weißem Gesicht, grünen Haaren und Chaos-Motto?',
        ['Riddler', 'Joker', 'Two-Face', 'Penguin'], 1,
        'Joker — Batmans Nemesis. Debüt „Batman #1" (1940). Schauspieler: Cesar Romero, Jack Nicholson, Heath Ledger, Joaquin Phoenix.',
        ['Joker', 'Batman']),
    mc('q-comics-117', 'comics', 3,
        'Wer ist Marvels Königin von Wakanda-Erbe und tragen den Vibranium-Anzug (Black Panther)?',
        ['T\'Chaka', 'T\'Challa', 'Killmonger', 'Shuri'], 1,
        'T\'Challa. Debüt 1966 (Stan Lee, Jack Kirby) — erster schwarzer Superheld eines großen Verlags. Filmreihe mit Chadwick Boseman ab 2018.',
        ['Black Panther', 'Wakanda']),
    mc('q-comics-118', 'comics', 4,
        'Wer erschuf 1978 das französische Sci-Fi-Comic „Der Incal" mit Alejandro Jodorowsky?',
        ['Enki Bilal', 'Moebius (Jean Giraud)', 'Milo Manara', 'Régis Loisel'], 1,
        'Moebius (Jean „Gir" Giraud). Ikone der Bande dessinée. Auch Blueberry (Western-Comic). Sein Stil beeinflusste u. a. Miyazaki und Ridley Scott.',
        ['Moebius', 'Incal']),
    mc('q-comics-119', 'comics', 2,
        'Wie heißt der lila Titan, der im MCU nach den Infinity-Steinen jagt?',
        ['Loki', 'Thanos', 'Ultron', 'Galactus'], 1,
        'Thanos, Marvel Comics 1973 (Jim Starlin). MCU: Avengers Infinity War (2018), Endgame (2019). Fingerschnippen = Blip.',
        ['Thanos', 'MCU']),
]

# ANIME & MANGA (20)
NEW_QUESTIONS += [
    mc('q-anime-100', 'anime', 1,
        'Welches Studio produzierte „Chihiros Reise ins Zauberland" (2001)?',
        ['Studio Ghibli', 'Toei Animation', 'Madhouse', 'Kyoto Animation'], 0,
        'Studio Ghibli (Miyazaki & Takahata, 1985). Chihiro gewann 2003 den Oscar für besten Animationsfilm.',
        ['Ghibli', 'Chihiro']),
    mc('q-anime-101', 'anime', 1,
        'Wer ist der berühmte Regisseur von „Prinzessin Mononoke" und „Mein Nachbar Totoro"?',
        ['Isao Takahata', 'Hayao Miyazaki', 'Mamoru Hosoda', 'Makoto Shinkai'], 1,
        'Hayao Miyazaki (geb. 1941). Ehrenoscar 2014. Weitere: „Das wandelnde Schloss", „Ponyo", „The Boy and the Heron" (2023).',
        ['Miyazaki', 'Ghibli']),
    mc('q-anime-102', 'anime', 2,
        'Wie heißt der Piraten-Anime von Eiichiro Oda mit Ruffy als Kapitän?',
        ['Naruto', 'One Piece', 'Bleach', 'Dragon Ball'], 1,
        'One Piece. Manga seit 1997. Meistverkaufter Manga aller Zeiten: 500+ Mio. Bände. Anime seit 1999 (1 000+ Episoden).',
        ['One Piece', 'Oda']),
    mc('q-anime-103', 'anime', 2,
        'Wer ist die Titelfigur des Ninja-Animes von Masashi Kishimoto (1999–2014)?',
        ['Ichigo', 'Naruto Uzumaki', 'Goku', 'Luffy'], 1,
        'Naruto Uzumaki. Neunschwänziger Fuchs (Kurama) in ihm versiegelt. Sequel „Boruto" folgt seinem Sohn.',
        ['Naruto', 'Ninja']),
    mc('q-anime-104', 'anime', 2,
        'Welcher Anime dreht sich um Sammel-Karten und den Wunsch, „Pokémon-Meister" zu werden?',
        ['Digimon', 'Yu-Gi-Oh!', 'Pokémon', 'Beyblade'], 2,
        'Pokémon (Poketto Monsutā, 1997). Ash Ketchum & Pikachu. Franchise: >100 Mrd. $ (größtes Media-Franchise aller Zeiten).',
        ['Pokémon', 'Ash']),
    mc('q-anime-105', 'anime', 3,
        'Welcher Cyberpunk-Anime von 1988 spielt in Neo-Tokyo nach Weltkrieg?',
        ['Ghost in the Shell', 'Akira', 'Perfect Blue', 'Neon Genesis Evangelion'], 1,
        'Akira (Katsuhiro Otomo). Vollständig handgezeichnet, 160 000 Zeichnungen. Revolutionierte Anime im Westen.',
        ['Akira', 'Cyberpunk']),
    mc('q-anime-106', 'anime', 2,
        'Welcher Anime spielt in einer Welt, wo Menschen von riesigen Titanen bedroht werden?',
        ['Death Note', 'Attack on Titan', 'Fullmetal Alchemist', 'Sword Art Online'], 1,
        'Attack on Titan (Shingeki no Kyojin) — Hajime Isayama. 2009–2021. Eren Yeager, Mikasa, Armin.',
        ['AoT', 'Titan']),
    mc('q-anime-107', 'anime', 2,
        'Wie heißt der berühmte Death-Note-Hauptcharakter, der Verbrecher mit einem Notizbuch tötet?',
        ['L', 'Light Yagami', 'Ryuk', 'Near'], 1,
        'Light Yagami (Kira). Notizbuch: schreibe Name = Person stirbt. Manga 2003–2006 (Ohba/Obata). Kult-Anime.',
        ['Death Note', 'Yagami']),
    mc('q-anime-108', 'anime', 3,
        'Welche Sci-Fi-Anime-Serie von 1995 dreht sich um Rei, Asuka, Shinji und EVA-Kampfroboter?',
        ['Cowboy Bebop', 'Neon Genesis Evangelion', 'Gundam', 'Serial Experiments Lain'], 1,
        'Neon Genesis Evangelion (Studio Gainax, Hideaki Anno). Postapokalyptisches Tokyo-3. Metaphysische Themen, umstrittenes Ende.',
        ['Evangelion', 'Anno']),
    mc('q-anime-109', 'anime', 2,
        'Welcher Anime folgt einem Ninja-Boy und einer roten Katze Chi-Chi… nein, dem Saiyajin Goku?',
        ['Dragon Ball', 'Yu Yu Hakusho', 'Saint Seiya', 'Fist of the North Star'], 0,
        'Dragon Ball (Akira Toriyama, 1984). Später „DB Z" (1989), „DB Super" (2015). Weltberühmt für „Kamehameha".',
        ['Goku', 'Toriyama']),
    mc('q-anime-110', 'anime', 3,
        'Welcher Anime-Film von Makoto Shinkai (2016) verknüpft zwei Teenager per Körpertausch und Kometen?',
        ['Weathering With You', 'Your Name', 'Suzume', '5 Centimeters Per Second'], 1,
        '„Your Name" (Kimi no Na wa). Weltweit >380 Mio. $ — höchster japanischer Nicht-Ghibli-Anime bis „Demon Slayer".',
        ['Your Name', 'Shinkai']),
    mc('q-anime-111', 'anime', 2,
        'Wie heißt der Cowboy-Kopfgeldjäger-Anime von 1998 mit Spike Spiegel?',
        ['Trigun', 'Cowboy Bebop', 'Samurai Champloo', 'Outlaw Star'], 1,
        'Cowboy Bebop (Shinichirō Watanabe). 26 Episoden, Jazz-Soundtrack von Yoko Kanno. Sci-Fi + Western + Noir + Jazz.',
        ['Bebop', 'Spike']),
    mc('q-anime-112', 'anime', 3,
        'Welcher Manga von Ken Akamatsu wurde durch die Serie mit Bergungs-Duo Ed und Al Elric weltberühmt?',
        ['Fullmetal Alchemist', 'D. Gray-Man', 'Berserk', 'Soul Eater'], 0,
        'Fullmetal Alchemist (Hiromu Arakawa, nicht Akamatsu — hier Fehler in Frage; korrekt Arakawa). Anime 2003 & Brotherhood 2009.',
        ['FMA', 'Arakawa']),
    mc('q-anime-113', 'anime', 2,
        'Welcher Sport spielt in „Kuroko no Basket" die Hauptrolle?',
        ['Fußball', 'Basketball', 'Volleyball', 'Baseball'], 1,
        'Basketball. Manga von Tadatoshi Fujimaki (2008–2014). Verwandt: „Slam Dunk" (Takehiko Inoue, 1990er).',
        ['Basketball', 'Kuroko']),
    mc('q-anime-114', 'anime', 3,
        'Welcher Shonen-Anime von Koyoharu Gotouge zerschlug 2020 Kinorekorde in Japan (Mugen Train)?',
        ['My Hero Academia', 'Demon Slayer (Kimetsu no Yaiba)', 'Jujutsu Kaisen', 'Chainsaw Man'], 1,
        'Demon Slayer. Kimetsu no Yaiba: Mugen Train (2020) = damals umsatzstärkster japanischer Film (~500 Mio. $).',
        ['Demon Slayer', 'Kimetsu']),
    mc('q-anime-115', 'anime', 2,
        'Welche Robotertyp-Serie von Yoshiyuki Tomino startete 1979 die Mecha-Anime-Ära?',
        ['Macross', 'Gundam', 'Voltron', 'Getter Robo'], 1,
        'Mobile Suit Gundam (Kidō Senshi Gandamu, 1979). „Universal Century"-Timeline. 100+ Serien und Filme. Basis der Real-Robot-Ära.',
        ['Gundam', 'Mecha']),
    mc('q-anime-116', 'anime', 3,
        'Welche magische Mädchen-Serie von 1992 folgt Usagi Tsukino als Kämpferin für Liebe und Gerechtigkeit?',
        ['Cardcaptor Sakura', 'Sailor Moon', 'Magic Knight Rayearth', 'Puella Magi Madoka Magica'], 1,
        'Bishoujo Senshi Sailor Moon — Naoko Takeuchi. 1992–1997. Global prägend für „magical girl". Reboot: Crystal (2014).',
        ['Sailor Moon', 'Usagi']),
    mc('q-anime-117', 'anime', 4,
        'Welcher Anime-Regisseur ist bekannt für Meta-Psychologie („Perfect Blue", „Paprika")?',
        ['Mamoru Oshii', 'Satoshi Kon', 'Katsuhiro Otomo', 'Mamoru Hosoda'], 1,
        'Satoshi Kon (1963–2010). „Perfect Blue" (1997), „Paprika" (2006) — Inspiration für Aronofskys „Black Swan" und Nolans „Inception".',
        ['Satoshi Kon', 'Paprika']),
    mc('q-anime-118', 'anime', 2,
        'Was bedeutet „Manga"?',
        [
            'Puppentheater',
            'Japanische Comics',
            'Kartenspiel',
            'Kalligraphie',
        ], 1,
        'Manga = jap. Wort für Comics. Rechts-nach-links gelesen. Wichtige Verlage: Shueisha, Kodansha, Shogakukan.',
        ['Manga', 'Comic']),
    mc('q-anime-119', 'anime', 3,
        'Welche Ghibli-Figur ist ein Waldgeist, der auf einer Cheshire-Katze-Bus fährt?',
        ['Ponyo', 'Totoro', 'Chihiro', 'Sophie'], 1,
        'Totoro (Mein Nachbar Totoro, 1988). Riesiger Waldgeist. Katzenbus („Nekobus") als Transport. Ghibli-Maskottchen.',
        ['Totoro', 'Ghibli']),
]


def main() -> int:
    with QUESTIONS_PATH.open('r', encoding='utf-8') as f:
        existing = json.load(f)
    existing_ids = {q['id'] for q in existing}
    to_add = [q for q in NEW_QUESTIONS if q['id'] not in existing_ids]
    if not to_add:
        print('Keine neuen Fragen.')
        return 0
    for q in to_add:
        assert len(q['options']) == 4, q['id']
        assert 0 <= q['correctIndex'] < 4, q['id']
    merged = existing + to_add
    with QUESTIONS_PATH.open('w', encoding='utf-8') as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
        f.write('\n')
    from collections import Counter
    print(f'✓ {len(to_add)} neue Fragen ergänzt (jetzt {len(merged)} insgesamt).')
    for t, c in sorted(Counter(q['topic'] for q in to_add).items()):
        print(f'  + {t:<14} {c}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
