#!/usr/bin/env python3
"""Batch 2: 8 neue Kategorien × 20 Fragen = 160.

Kategorien: religion, politik, wirtschaft, recht, bildung,
            gesundheit, reisen, autos
"""

from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
QUESTIONS_PATH = ROOT / 'packages' / 'shared' / 'src' / 'data' / 'questions.json'
NOW = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')

MC_MODES = ['category-duel', 'flash', 'player-spotlight', 'sprinter',
            'points-ladder', 'category-board', 'duel-1v1', 'elimination', 'experts']


def mc(qid, topic, difficulty, question, options, correct, gm, tags, category='allgemeinbildung'):
    return {
        'id': qid, 'type': 'multiple-choice', 'status': 'approved',
        'category': category, 'topic': topic, 'difficulty': difficulty,
        'question': question, 'options': options, 'correctIndex': correct,
        'gmNote': gm, 'tags': tags, 'compatibleModes': MC_MODES,
        'timeScope': 'timeless', 'aiGenerated': True,
        'createdAt': NOW, 'updatedAt': NOW,
    }


NEW_QUESTIONS = [
    # ================================================================
    # RELIGION & PHILOSOPHIE (20)
    # ================================================================
    mc('q-religion-100', 'religion', 1,
        'Welche Religion ist zahlenmäßig mit rund 2,4 Milliarden Anhängern die größte der Welt?',
        ['Islam', 'Christentum', 'Hinduismus', 'Buddhismus'], 1,
        'Christentum: ~31 % der Weltbevölkerung. Islam Platz 2 (~1,9 Mrd.), Hinduismus (~1,2 Mrd.), Buddhismus (~500 Mio.).',
        ['Christentum', 'Weltreligion']),
    mc('q-religion-101', 'religion', 1,
        'Welcher Prophet gilt im Islam als Gründer der Religion?',
        ['Moses', 'Jesus', 'Mohammed', 'Abraham'], 2,
        'Mohammed (570–632). Für Muslime der letzte Prophet in einer Reihe, die von Adam über Abraham, Moses bis Jesus reicht.',
        ['Islam', 'Mohammed']),
    mc('q-religion-102', 'religion', 2,
        'In welchem biblischen Buch werden die zehn Gebote überliefert?',
        ['Neues Testament', 'Altes Testament (Exodus)', 'Koran', 'Talmud'], 1,
        'Die Zehn Gebote stehen im Buch Exodus (Kapitel 20) im Alten Testament. Auf zwei Steintafeln übergeben an Moses am Berg Sinai.',
        ['Zehn Gebote', 'Bibel']),
    mc('q-religion-103', 'religion', 1,
        'Wie heißt das heilige Buch des Islam?',
        ['Talmud', 'Koran', 'Bibel', 'Bhagavad Gita'], 1,
        '„Al-Qur\'an" = die Lesung. In 114 Suren gegliedert. Für Muslime das direkte Wort Gottes an Mohammed über den Erzengel Gabriel.',
        ['Koran', 'Islam']),
    mc('q-religion-104', 'religion', 3,
        'Welche philosophische Methode, die auf Frage-und-Antwort-Dialoge setzt, geht auf den antiken griechischen Denker zurück?',
        ['Stoische Askese', 'Epikureische Selbstprüfung', 'Sokratische Methode', 'Skeptisches Zweifeln'], 2,
        'Sokrates (~469–399 v. Chr.) hinterließ keine Schriften; überliefert durch Platons Dialoge. Kern: durch geschickte Fragen zur Selbsterkenntnis führen.',
        ['Sokrates', 'Philosophie']),
    mc('q-religion-105', 'religion', 3,
        'Wer schrieb das Werk „Also sprach Zarathustra"?',
        ['Immanuel Kant', 'Friedrich Nietzsche', 'Martin Heidegger', 'Karl Marx'], 1,
        'Nietzsche, 1883–1885. Enthält den berühmten Satz „Gott ist tot" und die Idee des Übermenschen.',
        ['Nietzsche', 'Philosophie']),
    mc('q-religion-106', 'religion', 3,
        'Welcher Philosoph prägte den Satz „Ich denke, also bin ich" („Cogito, ergo sum")?',
        ['René Descartes', 'Immanuel Kant', 'David Hume', 'Voltaire'], 0,
        'Descartes, „Meditationes de prima philosophia" (1641). Zentraler Ausgangspunkt der neuzeitlichen Philosophie.',
        ['Descartes', 'Cogito']),
    mc('q-religion-107', 'religion', 2,
        'In welcher Religion sind die vier edlen Wahrheiten und der achtfache Pfad zentrale Lehren?',
        ['Christentum', 'Buddhismus', 'Hinduismus', 'Judentum'], 1,
        'Kern der Lehre Siddhartha Gautamas („Buddha", ~500 v. Chr.). Das Leiden erkennen, seine Ursache, seine Aufhebung, den Weg dorthin.',
        ['Buddhismus', 'Buddha']),
    mc('q-religion-108', 'religion', 2,
        'Welche religiöse Bewegung wurde 1517 durch Martin Luthers 95 Thesen ausgelöst?',
        ['Katholische Erneuerung', 'Reformation', 'Aufklärung', 'Restauration'], 1,
        'Der Thesenanschlag zu Wittenberg. Führte zur Spaltung der westlichen Kirche in Katholiken und Protestanten.',
        ['Reformation', 'Luther']),
    mc('q-religion-109', 'religion', 2,
        'Wie viele Säulen (Grundpflichten) hat der Islam?',
        ['3', '5', '7', '12'], 1,
        'Glaubensbekenntnis, Gebet (5×/Tag), Almosen (Zakat), Fasten (Ramadan), Pilgerfahrt (Hadsch nach Mekka).',
        ['Islam', 'Fünf Säulen']),
    mc('q-religion-110', 'religion', 1,
        'Welche Stadt gilt Christen, Juden und Muslimen als heilig?',
        ['Rom', 'Mekka', 'Jerusalem', 'Konstantinopel'], 2,
        'Jerusalem: Klagemauer (Judentum), Grabeskirche (Christentum), Felsendom (Islam). Alle drei sind hier auf engem Raum konzentriert.',
        ['Jerusalem']),
    mc('q-religion-111', 'religion', 3,
        'Welcher deutsche Philosoph verfasste die „Kritik der reinen Vernunft"?',
        ['Hegel', 'Kant', 'Schopenhauer', 'Fichte'], 1,
        'Immanuel Kant, 1781. Zentrale Frage: Was können wir überhaupt erkennen? Trennt Erkenntnis a priori (unabhängig von Erfahrung) und a posteriori.',
        ['Kant', 'Aufklärung']),
    mc('q-religion-112', 'religion', 4,
        'Welche philosophische Schule strebt Gleichmut durch Beherrschung der Emotionen an?',
        ['Epikureismus', 'Stoa', 'Skepsis', 'Kynismus'], 1,
        'Stoiker (Zenon, Seneca, Mark Aurel): Tugendhaft leben in Übereinstimmung mit der Natur, sich vom Unbeeinflussbaren nicht aus der Ruhe bringen lassen.',
        ['Stoa', 'Philosophie']),
    mc('q-religion-113', 'religion', 2,
        'Welcher indische Anführer nutzte gewaltlosen Widerstand gegen die britische Kolonialmacht?',
        ['Jawaharlal Nehru', 'Mahatma Gandhi', 'Subhas Chandra Bose', 'B. R. Ambedkar'], 1,
        'Gandhi (1869–1948) prägte den Begriff „Satyagraha" — Wahrheitskraft. Indien wurde 1947 unabhängig.',
        ['Gandhi', 'Indien']),
    mc('q-religion-114', 'religion', 4,
        'Welche philosophische Richtung, populär durch Jean-Paul Sartre, betont die absolute Freiheit und Verantwortung des Individuums?',
        ['Positivismus', 'Existenzialismus', 'Strukturalismus', 'Marxismus'], 1,
        'Sartre: „Der Mensch ist zur Freiheit verurteilt." Zentral auch bei Kierkegaard, Heidegger, Camus.',
        ['Existenzialismus', 'Sartre']),
    mc('q-religion-115', 'religion', 4,
        'Wie heißt der wichtigste hinduistische Text mit dem Dialog zwischen Krishna und Arjuna?',
        ['Veden', 'Upanishaden', 'Bhagavad Gita', 'Ramayana'], 2,
        '„Der Gesang des Erhabenen" — Teil des Mahabharata-Epos. Krishna erklärt Arjuna vor der Schlacht das dharma (die richtige Pflicht).',
        ['Bhagavad Gita', 'Hinduismus']),
    mc('q-religion-116', 'religion', 3,
        'Welche Weltreligion kennt keinen persönlichen Schöpfer-Gott und stellt Reinkarnation, Karma und das Erlöschen des Ich in den Mittelpunkt?',
        ['Islam', 'Judentum', 'Buddhismus', 'Christentum'], 2,
        'Im Buddhismus wird kein göttlicher Schöpfer angenommen. Ziel ist das Nirwana — das Aufhören des Wiedergeburtenzyklus.',
        ['Buddhismus', 'Reinkarnation']),
    mc('q-religion-117', 'religion', 3,
        'Wie heißt das jüdische Neujahrsfest?',
        ['Chanukka', 'Pessach', 'Rosch ha-Schana', 'Jom Kippur'], 2,
        'Rosch ha-Schana („Kopf des Jahres"): Beginn des jüdischen Kalenderjahres. 10 Tage später folgt Jom Kippur, der höchste Feiertag.',
        ['Rosch ha-Schana', 'Judentum']),
    mc('q-religion-118', 'religion', 3,
        'Welcher antike griechische Philosoph war Schüler Platons und Lehrer Alexanders des Großen?',
        ['Sokrates', 'Aristoteles', 'Diogenes', 'Epikur'], 1,
        'Aristoteles (384–322 v. Chr.). Gründer des Lyzeums, systematisierte Logik, Biologie, Ethik, Politik. Alexanders Lehrer 343–340 v. Chr.',
        ['Aristoteles', 'Antike']),
    mc('q-religion-119', 'religion', 1,
        'Wie viele Testamente hat die christliche Bibel klassisch im westlichen Kanon?',
        ['1', '2', '3', '4'], 1,
        'Altes Testament (jüdischer Tanach) + Neues Testament. Der katholische Kanon hat einige Deuterokanonika mehr als der protestantische.',
        ['Bibel', 'Christentum']),

    # ================================================================
    # POLITIK & GESELLSCHAFT (20)
    # ================================================================
    mc('q-politik-100', 'politik', 1,
        'Wie viele Sterne hat die Flagge der Europäischen Union?',
        ['9', '12', '15', '27'], 1,
        '12 goldene Sterne im Kreis auf blauem Grund. Die Zahl 12 steht für Vollkommenheit, unabhängig von der Mitgliederzahl.',
        ['EU', 'Flagge']),
    mc('q-politik-101', 'politik', 1,
        'Wie viele Sitze hat der Sicherheitsrat der Vereinten Nationen aktuell?',
        ['5', '10', '15', '20'], 2,
        '5 ständige Mitglieder mit Vetorecht (USA, UK, Frankreich, Russland, China) + 10 nicht-ständige, alle 2 Jahre gewählt.',
        ['UN', 'Sicherheitsrat']),
    mc('q-politik-102', 'politik', 2,
        'Welche deutsche Partei stellte in der Geschichte der BRD am längsten den Bundeskanzler?',
        ['SPD', 'CDU', 'FDP', 'Grüne'], 1,
        'CDU-Kanzler: Adenauer, Erhard, Kiesinger, Kohl, Merkel. Zusammen rund 51 der 74 Jahre BRD-Kanzlerschaft (Stand 2023).',
        ['CDU', 'Bundeskanzler']),
    mc('q-politik-103', 'politik', 2,
        'Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?',
        ['Willy Brandt', 'Konrad Adenauer', 'Helmut Schmidt', 'Ludwig Erhard'], 1,
        'Adenauer, CDU, 1949–1963. Prägte den Wiederaufbau und die Westintegration.',
        ['Adenauer', 'BRD']),
    mc('q-politik-104', 'politik', 3,
        'In welchem Jahr trat der Vertrag von Maastricht in Kraft und begründete die Europäische Union?',
        ['1989', '1993', '1999', '2004'], 1,
        'Unterzeichnet 1992, in Kraft 1. November 1993. Etablierte die drei EU-Säulen und schuf den Euro als Projekt.',
        ['Maastricht', 'EU']),
    mc('q-politik-105', 'politik', 3,
        'Wie viele Bundesstaaten haben die USA?',
        ['48', '50', '52', '54'], 1,
        'Der letzte war Hawaii (1959). Puerto Rico und Washington D.C. sind keine Bundesstaaten.',
        ['USA', 'Bundesstaaten']),
    mc('q-politik-106', 'politik', 3,
        'Wie heißt das Verfahren, mit dem in den USA ein Präsident wegen schwerer Verfehlungen abgesetzt werden kann?',
        ['Recall', 'Impeachment', 'Filibuster', 'Executive Order'], 1,
        'Repräsentantenhaus klagt an, Senat verhandelt. Bisher (Stand 2023) drei Präsidenten formell angeklagt (Johnson, Clinton, Trump 2x), keiner verurteilt.',
        ['USA', 'Impeachment']),
    mc('q-politik-107', 'politik', 2,
        'Welche politische Ideologie liegt dem „Kapital" von Karl Marx zugrunde?',
        ['Liberalismus', 'Kommunismus', 'Konservatismus', 'Faschismus'], 1,
        'Marx analysiert die kapitalistische Produktion und deren innere Widersprüche. Zusammen mit Engels „Das Manifest der Kommunistischen Partei" (1848).',
        ['Marx', 'Kommunismus']),
    mc('q-politik-108', 'politik', 2,
        'Welche Farbe symbolisiert traditionell den Konservatismus in Deutschland?',
        ['Rot', 'Schwarz', 'Grün', 'Gelb'], 1,
        'CDU/CSU: schwarz. SPD: rot. Grüne: grün. FDP: gelb. Linke: dunkelrot. AfD: hellblau/orange.',
        ['Farben', 'Parteien']),
    mc('q-politik-109', 'politik', 3,
        'Wie viele Abgeordnete hat der Deutsche Bundestag in der Legislaturperiode ab 2021 mindestens?',
        ['499', '598', '736', '900'], 2,
        'Nach der Wahl 2021: 736 Abgeordnete (rekordhoch wegen Überhang- und Ausgleichsmandaten). Mit dem neuen Wahlrecht wird das ab 2025 auf 630 begrenzt.',
        ['Bundestag']),
    mc('q-politik-110', 'politik', 2,
        'Welches politische Amt hatte Angela Merkel von 2005 bis 2021 inne?',
        ['Bundespräsidentin', 'Bundeskanzlerin', 'Außenministerin', 'CDU-Vorsitzende (nur)'], 1,
        'Erste Bundeskanzlerin Deutschlands. 16 Jahre — knapp kürzer als Kohl (16 Jahre + 1 Monat).',
        ['Merkel', 'Bundeskanzler']),
    mc('q-politik-111', 'politik', 3,
        'Welches Land hatte den ersten weiblichen Regierungschef der Welt (1960)?',
        ['Großbritannien', 'Ceylon (Sri Lanka)', 'Israel', 'Indien'], 1,
        'Sirimavo Bandaranaike wurde 1960 in Ceylon Premierministerin. Margaret Thatcher folgte erst 1979.',
        ['Bandaranaike', 'Sri Lanka']),
    mc('q-politik-112', 'politik', 2,
        'Welche internationale Organisation wurde 1949 als militärisches Bündnis westlicher Staaten gegründet?',
        ['UNO', 'NATO', 'EU', 'G7'], 1,
        'North Atlantic Treaty Organization, Gründungsvertrag 4. April 1949 in Washington. 12 Gründungsmitglieder, heute 32.',
        ['NATO']),
    mc('q-politik-113', 'politik', 3,
        'Welcher US-Präsident hat den Bürgerrechtsakt 1964 unterzeichnet?',
        ['John F. Kennedy', 'Lyndon B. Johnson', 'Richard Nixon', 'Ronald Reagan'], 1,
        'Der Civil Rights Act verbot Rassentrennung in öffentlichen Einrichtungen. Kennedy hatte ihn initiiert, wurde aber 1963 ermordet.',
        ['USA', 'Civil Rights']),
    mc('q-politik-114', 'politik', 3,
        'Welche Regierungsform verbindet die Ideen von Volkssouveränität mit direkter Bürgerbeteiligung an Entscheidungen?',
        ['Repräsentative Demokratie', 'Direkte Demokratie', 'Aristokratie', 'Timokratie'], 1,
        'Musterbeispiel: die Schweiz mit ihren Volksabstimmungen und Referenden. Athen ~500 v. Chr. gilt als historisches Ur-Beispiel.',
        ['Demokratie', 'Schweiz']),
    mc('q-politik-115', 'politik', 3,
        'In welchem Jahr wurde die deutsche Wiedervereinigung offiziell vollzogen?',
        ['1989', '1990', '1991', '1992'], 1,
        '3. Oktober 1990: Tag der Deutschen Einheit. Die Berliner Mauer war seit dem 9. November 1989 offen.',
        ['Wiedervereinigung', '1990']),
    mc('q-politik-116', 'politik', 4,
        'Welcher britische Premier prägte 1946 den Begriff „Eiserner Vorhang" für die Trennung Europas?',
        ['Clement Attlee', 'Winston Churchill', 'Harold Wilson', 'Anthony Eden'], 1,
        'In Churchills Rede in Fulton, Missouri (5. März 1946): „Ein Eiserner Vorhang ist quer durch Europa niedergegangen."',
        ['Churchill', 'Kalter Krieg']),
    mc('q-politik-117', 'politik', 3,
        'Welches Grundprinzip der Gewaltenteilung geht auf Charles de Montesquieu zurück?',
        ['Legislative, Exekutive, Judikative', 'Königtum, Adel, Volk', 'Kirche, Staat, Bürger', 'Nord, Mitte, Süd'], 0,
        'Montesquieu (1748, „De l\'esprit des lois"). Gesetzgebende, ausführende und richterliche Gewalt sollen sich gegenseitig kontrollieren.',
        ['Montesquieu', 'Gewaltenteilung']),
    mc('q-politik-118', 'politik', 4,
        'Welche politische Ideologie liegt der Regierung des heutigen Chinas offiziell zugrunde?',
        ['Kapitalismus', 'Sozialismus chinesischer Prägung', 'Liberalismus', 'Konservatismus'], 1,
        'Die KP Chinas nennt es „Sozialismus chinesischer Prägung" — Marktwirtschaft unter Ein-Parteien-Herrschaft.',
        ['China', 'Sozialismus']),
    mc('q-politik-119', 'politik', 3,
        'Welche Institution beschließt in Deutschland Bundesgesetze zusammen mit dem Bundestag?',
        ['Bundeskanzleramt', 'Bundesrat', 'Bundesverfassungsgericht', 'Bundespräsidialamt'], 1,
        'Der Bundesrat vertritt die 16 Bundesländer. Bei Gesetzen, die Länder betreffen, hat er ein Veto- oder Zustimmungsrecht.',
        ['Bundesrat', 'Föderalismus']),

    # ================================================================
    # WIRTSCHAFT & FINANZEN (20)
    # ================================================================
    mc('q-wirtschaft-100', 'wirtschaft', 1,
        'Welche Aktie ist an der US-Börse Nasdaq notiert und war 2023 das erste Unternehmen mit über 3 Billionen Dollar Marktwert?',
        ['Microsoft', 'Apple', 'Amazon', 'Alphabet (Google)'], 1,
        'Apple erreichte Anfang 2022 als erstes Unternehmen 3 Billionen Dollar. Microsoft folgte 2023. Beide alternierend Weltrang 1.',
        ['Apple', 'Aktien']),
    mc('q-wirtschaft-101', 'wirtschaft', 2,
        'Welche Institution steuert seit 1999 die Geldpolitik im Euro-Raum?',
        ['Deutsche Bundesbank', 'Europäische Zentralbank (EZB)', 'Weltbank', 'IWF'], 1,
        'EZB, Sitz Frankfurt am Main. Aktuelle Präsidentin: Christine Lagarde (seit 2019).',
        ['EZB', 'Euro']),
    mc('q-wirtschaft-102', 'wirtschaft', 2,
        'Wie viele Länder verwenden aktuell den Euro als offizielles Zahlungsmittel (Stand 2023)?',
        ['15', '19', '20', '27'], 2,
        'Kroatien kam 2023 als 20. Land dazu. Nicht dabei: unter EU-Mitgliedern Dänemark, Schweden, Polen, Tschechien u. a.',
        ['Euro', 'Eurozone']),
    mc('q-wirtschaft-103', 'wirtschaft', 3,
        'Welche deutsche Börse ist die größte des Landes?',
        ['Berliner Börse', 'Börse München', 'Frankfurter Wertpapierbörse', 'Börse Stuttgart'], 2,
        'Frankfurt wickelt ~90 % des deutschen Aktienhandels ab. Betreiber: die Deutsche Börse AG.',
        ['Frankfurt', 'Börse']),
    mc('q-wirtschaft-104', 'wirtschaft', 2,
        'Wie viele Unternehmen sind aktuell im deutschen Leitindex DAX (Deutscher Aktienindex) gelistet?',
        ['20', '30', '40', '50'], 2,
        'Seit September 2021 40 Titel (vorher 30 seit 1988). Umfasst die 40 größten börsennotierten deutschen Firmen.',
        ['DAX', 'Aktien']),
    mc('q-wirtschaft-105', 'wirtschaft', 3,
        'Wer schrieb 1776 „Der Wohlstand der Nationen", das Gründungswerk der modernen Wirtschaftswissenschaft?',
        ['Adam Smith', 'John Maynard Keynes', 'Karl Marx', 'David Ricardo'], 0,
        'Adam Smith prägte den Begriff der „unsichtbaren Hand" des Marktes.',
        ['Adam Smith', 'Ökonomie']),
    mc('q-wirtschaft-106', 'wirtschaft', 3,
        'Wie heißt das Wirtschaftssystem, das durch Marktmechanismen und Privatkapital gekennzeichnet ist?',
        ['Sozialismus', 'Kapitalismus', 'Feudalismus', 'Merkantilismus'], 1,
        'Kapitalismus: freie Preisbildung, Privatbesitz an Produktionsmitteln, Gewinnmaximierung. Wichtiger Denker: Adam Smith.',
        ['Kapitalismus', 'Wirtschaftssystem']),
    mc('q-wirtschaft-107', 'wirtschaft', 4,
        'Welche Kryptowährung wurde 2009 als erste dezentrale digitale Währung eingeführt?',
        ['Ethereum', 'Bitcoin', 'Litecoin', 'Ripple'], 1,
        'Bitcoin (BTC): Whitepaper 2008 von „Satoshi Nakamoto" (Pseudonym), Netzwerk-Start 3. Januar 2009 mit dem „Genesis Block".',
        ['Bitcoin', 'Kryptowährung']),
    mc('q-wirtschaft-108', 'wirtschaft', 2,
        'Welches Land war 2023 die drittgrößte Volkswirtschaft der Welt nach BIP (nominal)?',
        ['China', 'Deutschland', 'Japan', 'Indien'], 1,
        'Deutschland überholte 2023 Japan wegen Yen-Schwäche. Ranking: USA, China, Deutschland, Japan, Indien.',
        ['BIP', 'Deutschland']),
    mc('q-wirtschaft-109', 'wirtschaft', 3,
        'Wer entwickelte die makroökonomische Theorie, die staatliche Ausgaben in Rezessionen befürwortet?',
        ['Milton Friedman', 'John Maynard Keynes', 'Friedrich Hayek', 'Karl Marx'], 1,
        'Keynes: „In the long run we are all dead." Grundlage der Wirtschaftspolitik nach 1945 im Westen.',
        ['Keynes', 'Ökonomie']),
    mc('q-wirtschaft-110', 'wirtschaft', 3,
        'Wie heißt der amerikanische Aktienindex, der die 30 größten Industrie-Unternehmen enthält?',
        ['S&P 500', 'Dow Jones Industrial Average', 'Nasdaq 100', 'Russell 2000'], 1,
        'Dow Jones seit 1896. Trotz „Industrial" heute überwiegend Finanz-, Tech- und Konsumtitel. Preisgewichtet — Kurshöhe zählt, nicht Marktkap.',
        ['Dow Jones', 'USA']),
    mc('q-wirtschaft-111', 'wirtschaft', 2,
        'Welche Firma gründete Bill Gates 1975 zusammen mit Paul Allen?',
        ['Apple', 'IBM', 'Microsoft', 'Oracle'], 2,
        'Startete in Albuquerque, New Mexico. Erstes Produkt: Altair BASIC. Der Windows-Durchbruch kam mit Version 3.0 (1990).',
        ['Microsoft', 'Bill Gates']),
    mc('q-wirtschaft-112', 'wirtschaft', 4,
        'Was misst der Gini-Koeffizient?',
        ['Inflation', 'Ungleichheit der Einkommensverteilung', 'Arbeitslosenquote', 'Wirtschaftswachstum'], 1,
        'Skala 0 (alle gleich) bis 1 (einer hat alles). Deutschland ~0,30, USA ~0,41, Skandinavien ~0,25.',
        ['Gini', 'Ungleichheit']),
    mc('q-wirtschaft-113', 'wirtschaft', 3,
        'Welcher US-Milliardär gründete Amazon 1994?',
        ['Bill Gates', 'Elon Musk', 'Jeff Bezos', 'Larry Ellison'], 2,
        'Bezos startete Amazon aus einer Garage als Online-Buchhandel. Trat 2021 als CEO zurück; sein Nachfolger ist Andy Jassy.',
        ['Bezos', 'Amazon']),
    mc('q-wirtschaft-114', 'wirtschaft', 3,
        'Wie heißt die Zentralbank der USA?',
        ['Bank of America', 'Federal Reserve', 'US Treasury', 'World Bank'], 1,
        'Federal Reserve System („Fed"), 1913 gegründet. Kein staatliches Amt im engeren Sinne, sondern quasi-öffentliche Struktur mit 12 regionalen Feds.',
        ['Federal Reserve', 'USA']),
    mc('q-wirtschaft-115', 'wirtschaft', 3,
        'In welchem Jahr begann die globale Finanzkrise mit dem Zusammenbruch von Lehman Brothers?',
        ['2001', '2005', '2008', '2011'], 2,
        '15. September 2008: Lehman-Insolvenz. Auslöser: US-Subprime-Immobilienkrise. Bis 2009 tiefste Weltrezession seit 1929.',
        ['Lehman', 'Finanzkrise']),
    mc('q-wirtschaft-116', 'wirtschaft', 4,
        'Welche wirtschaftliche Kennzahl misst den Wert aller produzierten Güter und Dienstleistungen eines Landes in einem Jahr?',
        ['Inflationsrate', 'Bruttoinlandsprodukt (BIP)', 'Handelsbilanz', 'Sparquote'], 1,
        'BIP kann nominal (aktuelle Preise) oder real (inflationsbereinigt) angegeben werden. Deutschland ~4 Billionen Euro BIP (2023).',
        ['BIP', 'Ökonomie']),
    mc('q-wirtschaft-117', 'wirtschaft', 4,
        'Wer war 2023 laut Forbes der reichste Mensch der Welt (großteils dank LVMH-Aktien)?',
        ['Elon Musk', 'Jeff Bezos', 'Bernard Arnault', 'Bill Gates'], 2,
        'Bernard Arnault, CEO von LVMH (Louis Vuitton, Dior, Moët). Musk und Arnault alternierten 2023 an der Spitze.',
        ['Arnault', 'LVMH']),
    mc('q-wirtschaft-118', 'wirtschaft', 2,
        'Was ist eine „Inflation"?',
        [
            'Sinken der Preise über die Zeit',
            'Anstieg der Preise über die Zeit',
            'Stabile Preise',
            'Wechselkursschwankung',
        ], 1,
        'Gemessen als jährliche Veränderung des Verbraucherpreisindex. Deutschlands EZB-Ziel: 2 % mittelfristig.',
        ['Inflation']),
    mc('q-wirtschaft-119', 'wirtschaft', 3,
        'Welches Unternehmen gilt seit den 2010ern als weltweit größter Öl-Produzent (staatlich gehalten)?',
        ['ExxonMobil', 'BP', 'Saudi Aramco', 'Shell'], 2,
        'Saudi Aramco ging 2019 an die Börse — bis dahin das größte IPO der Geschichte. Marktwert zeitweise über 2 Billionen Dollar.',
        ['Saudi Aramco', 'Öl']),

    # ================================================================
    # RECHT & KRIMINALITÄT (20)
    # ================================================================
    mc('q-recht-100', 'recht', 1,
        'Welches Alter markiert in Deutschland die Volljährigkeit?',
        ['16', '17', '18', '21'], 2,
        '§ 2 BGB: Volljährigkeit tritt mit Vollendung des 18. Lebensjahres ein. Volle Geschäfts-, Ehe- und Wahlfähigkeit.',
        ['Volljährigkeit', 'BGB']),
    mc('q-recht-101', 'recht', 2,
        'Welches Grundgesetz-Grundrecht steht ganz am Anfang und ist unantastbar?',
        [
            'Recht auf Leben',
            'Meinungsfreiheit',
            'Menschenwürde',
            'Gleichheit vor dem Gesetz',
        ], 2,
        'Artikel 1 GG: „Die Würde des Menschen ist unantastbar." Nicht änderbar durch Ewigkeitsklausel (Art. 79 III).',
        ['Grundgesetz', 'Menschenwürde']),
    mc('q-recht-102', 'recht', 2,
        'Wer war der berühmteste Bankräuber-Duo der US-Depression, das 1934 erschossen wurde?',
        [
            'Al Capone und Frank Nitti',
            'Bonnie und Clyde',
            'John Dillinger und Baby Face Nelson',
            'Machine Gun Kelly und Alvin Karpis',
        ], 1,
        'Bonnie Parker und Clyde Barrow — 21 und 25 Jahre alt bei ihrem Tod. Über 100 Filme, Bücher und Musicals inspiriert.',
        ['Bonnie und Clyde', 'True Crime']),
    mc('q-recht-103', 'recht', 3,
        'Welcher deutsche Serienmörder wurde als „Vampir von Düsseldorf" bekannt?',
        ['Fritz Haarmann', 'Peter Kürten', 'Bruno Lüdke', 'Jürgen Bartsch'], 1,
        'Peter Kürten (1883–1931): 9 Morde 1929 im Raum Düsseldorf. Fritz Langs Film „M" (1931) mit Peter Lorre ist von diesem Fall inspiriert.',
        ['Serienmörder', 'Kürten']),
    mc('q-recht-104', 'recht', 2,
        'Welches Wort steht in Deutschland für die höchste Strafe im Erwachsenenstrafrecht?',
        ['Todesstrafe', 'Lebenslange Freiheitsstrafe', 'Zuchthaus', 'Sicherungsverwahrung'], 1,
        'Todesstrafe wurde 1949 mit dem Grundgesetz abgeschafft. Lebenslang bedeutet mind. 15 Jahre bis Bewährung geprüft wird.',
        ['Strafe', 'Deutschland']),
    mc('q-recht-105', 'recht', 3,
        'Welches historische Rechtsdokument von 1215 begrenzte erstmals die Macht des englischen Königs?',
        ['Bill of Rights', 'Magna Carta', 'Petition of Right', 'Habeas Corpus Act'], 1,
        'Magna Carta Libertatum. King John unterzeichnete unter Druck der Barone bei Runnymede. Grundlage der englischen und später amerikanischen Verfassungstradition.',
        ['Magna Carta', 'Recht']),
    mc('q-recht-106', 'recht', 3,
        'Welches internationale Tribunal wurde nach dem 2. Weltkrieg in Nürnberg abgehalten?',
        [
            'Prozesse gegen Kriegsverbrecher der Zentralmächte',
            'Verurteilung der Hauptkriegsverbrecher des NS-Regimes',
            'Internationaler Strafgerichtshof (ICC)',
            'Menschenrechts-Konvention',
        ], 1,
        'Nürnberger Prozesse (1945–1946): 24 Hauptangeklagte des NS-Regimes. 12 Todesurteile, drei lebenslange Haft, sonstige Freiheitsstrafen und Freisprüche.',
        ['Nürnberger Prozesse', 'NS-Zeit']),
    mc('q-recht-107', 'recht', 3,
        'Welcher berühmte italienische Mafia-Boss wurde 1931 in Chicago wegen Steuerhinterziehung verurteilt?',
        ['Lucky Luciano', 'Al Capone', 'Meyer Lansky', 'John Gotti'], 1,
        'Al „Scarface" Capone. Trotz zahlreicher Morde konnte man ihn nur mit Steuerhinterziehung überführen — 11 Jahre Alcatraz.',
        ['Al Capone', 'Mafia']),
    mc('q-recht-108', 'recht', 3,
        'Welche Grundregel des angelsächsischen Strafprozesses schützt vor willkürlicher Verhaftung?',
        ['Habeas Corpus', 'Miranda Rights', 'Due Process', 'Double Jeopardy'], 0,
        'Habeas Corpus („du sollst den Körper haben"): Recht, unverzüglich vor einen Richter geführt zu werden. Seit dem 17. Jhd. in England kodifiziert.',
        ['Habeas Corpus']),
    mc('q-recht-109', 'recht', 3,
        'Wie heißt der weltweit bekannteste ungelöste Fall eines Serienmörders im London des 19. Jahrhunderts?',
        ['Zodiac Killer', 'Jack the Ripper', 'Green River Killer', 'BTK Killer'], 1,
        '1888 in Whitechapel: mindestens fünf brutale Morde an Prostituierten. Identität nie geklärt — bis heute Gegenstand von Spekulation.',
        ['Jack the Ripper', 'London']),
    mc('q-recht-110', 'recht', 2,
        'In welchem Gebäude entscheiden in Deutschland die höchsten Verfassungsrichter?',
        ['Bundestag Berlin', 'Bundesverfassungsgericht Karlsruhe', 'Kanzleramt Berlin', 'Bundesrat Berlin'], 1,
        'Bundesverfassungsgericht in Karlsruhe seit 1951. Zwei Senate mit je 8 Richterinnen und Richtern, gewählt zur Hälfte von Bundestag und Bundesrat.',
        ['BVerfG', 'Karlsruhe']),
    mc('q-recht-111', 'recht', 4,
        'Welches sind die drei klassischen Voraussetzungen einer Straftat im deutschen Strafrecht?',
        [
            'Vorsatz, Motiv, Zeugen',
            'Tatbestandsmäßigkeit, Rechtswidrigkeit, Schuld',
            'Absicht, Ausführung, Verheimlichung',
            'Person, Ort, Zeit',
        ], 1,
        'Klassische Deliktsprüfung: 1. Erfüllt die Tat den gesetzlichen Tatbestand? 2. Ist sie rechtswidrig? 3. Kann dem Täter Schuld nachgewiesen werden?',
        ['Strafrecht', 'Deutschland']),
    mc('q-recht-112', 'recht', 3,
        'Welcher amerikanische Rechtsfall etablierte 1966 die Pflicht der Polizei, Verdächtige über ihre Rechte zu belehren?',
        ['Roe v. Wade', 'Miranda v. Arizona', 'Brown v. Board of Education', 'Marbury v. Madison'], 1,
        '„You have the right to remain silent..." — die Miranda-Warnung. Ergänzt jedes US-Krimidrama.',
        ['Miranda Rights', 'USA']),
    mc('q-recht-113', 'recht', 3,
        'Welche Todesstrafen-Methode wurde in Frankreich zwischen der Revolution und 1977 offiziell praktiziert?',
        ['Erschießen', 'Elektrischer Stuhl', 'Guillotine', 'Vergiftung'], 2,
        'Guillotine, erstmals 1792 offiziell. Letzte Hinrichtung: 1977 (Hamida Djandoubi). Todesstrafe abgeschafft: 1981.',
        ['Guillotine', 'Frankreich']),
    mc('q-recht-114', 'recht', 2,
        'Wie heißt das umfangreichste deutsche Gesetzbuch für den Alltag von Bürgern (Kaufverträge, Miete, Erbrecht etc.)?',
        ['StGB', 'BGB', 'GG', 'HGB'], 1,
        'Bürgerliches Gesetzbuch, in Kraft seit 1900. Über 2 000 Paragraphen.',
        ['BGB']),
    mc('q-recht-115', 'recht', 4,
        'Welcher deutsche Rechtsphilosoph forderte 1748 die Trennung von Gesetzgebung, Rechtsprechung und Verwaltung?',
        ['Immanuel Kant', 'Charles de Montesquieu', 'Cesare Beccaria', 'Hugo Grotius'], 1,
        'Zur Klarstellung: Montesquieu war Franzose, nicht Deutscher. „Vom Geist der Gesetze" (1748) beeinflusste alle modernen Verfassungen.',
        ['Montesquieu']),
    mc('q-recht-116', 'recht', 4,
        'Welcher amerikanische Serienmörder wurde für 30 Morde an jungen Frauen 1979 hingerichtet?',
        ['Jeffrey Dahmer', 'John Wayne Gacy', 'Ted Bundy', 'Charles Manson'], 2,
        'Ted Bundy. Studierter Jurist, verteidigte sich selbst. Hingerichtet 1989 auf dem elektrischen Stuhl in Florida.',
        ['Ted Bundy', 'True Crime']),
    mc('q-recht-117', 'recht', 3,
        'Was ist ein „Alibi" in juristischer Bedeutung?',
        [
            'Ein Motiv für eine Straftat',
            'Ein Nachweis, dass jemand zur Tatzeit anderswo war',
            'Ein Zeugengutachten',
            'Eine falsche Aussage',
        ], 1,
        'Lat. „alibi" = anderswo. Wenn der Beschuldigte nachweisen kann, dass er nicht am Tatort sein konnte, entlastet ihn das.',
        ['Alibi']),
    mc('q-recht-118', 'recht', 2,
        'Wie heißt das oberste Gericht der Europäischen Union?',
        ['Europäischer Gerichtshof (EuGH)', 'EU-Verfassungsgericht', 'Europäischer Menschenrechtsgerichtshof', 'Internationaler Gerichtshof'], 0,
        'EuGH, Sitz Luxemburg. Klärt Auslegung des EU-Rechts, entscheidet über EU-Mitgliedstaats-Verstöße.',
        ['EuGH', 'EU-Recht']),
    mc('q-recht-119', 'recht', 3,
        'Welches Prinzip verbietet die zweifache Bestrafung wegen derselben Tat?',
        ['Habeas Corpus', 'Double Jeopardy / ne bis in idem', 'Presumption of Innocence', 'Rule of Law'], 1,
        'Verankert im deutschen GG Art. 103 III und den US-Verfassungszusätzen. Ein Freispruch beendet den Prozess final.',
        ['Ne bis in idem', 'Grundrecht']),

    # ================================================================
    # BILDUNG & UNIVERSITÄTEN (20)
    # ================================================================
    mc('q-bildung-100', 'bildung', 1,
        'Welche gilt als die älteste ununterbrochen bestehende Universität Europas?',
        ['Universität Paris', 'Universität Oxford', 'Universität Bologna', 'Universität Salamanca'], 2,
        'Universität Bologna, gegründet 1088. Deshalb heißt der EU-Hochschulreform-Prozess „Bologna-Prozess".',
        ['Bologna', 'Universität']),
    mc('q-bildung-101', 'bildung', 2,
        'Welche US-Universität war 1636 die erste im heutigen Bundesgebiet?',
        ['Yale', 'Princeton', 'Harvard', 'Columbia'], 2,
        'Harvard College, gegründet 1636 in Cambridge, Massachusetts. Yale kam 1701, Princeton 1746.',
        ['Harvard', 'USA']),
    mc('q-bildung-102', 'bildung', 2,
        'Welche deutsche Institution vergibt den akademischen Titel „Bachelor" bzw. „Master"?',
        ['Universitäten und Fachhochschulen', 'Nur Universitäten', 'Nur Fachhochschulen', 'Volkshochschulen'], 0,
        'Seit dem Bologna-Prozess (ab 1999) vergeben in Deutschland sowohl Universitäten als auch Fachhochschulen Bachelor/Master.',
        ['Bachelor', 'Bologna-Prozess']),
    mc('q-bildung-103', 'bildung', 2,
        'Welchen Nobelpreis kann man KEINEN gewinnen?',
        ['Literatur', 'Mathematik', 'Frieden', 'Wirtschaftswissenschaften'], 1,
        'Es gibt Nobelpreise für Physik, Chemie, Medizin, Literatur, Frieden — plus seit 1969 der Wirtschaftspreis der Schwedischen Reichsbank. Mathematik: die Fields-Medaille übernimmt die Rolle.',
        ['Nobelpreis', 'Mathematik']),
    mc('q-bildung-104', 'bildung', 3,
        'In welchem Fach wird die Fields-Medaille verliehen?',
        ['Physik', 'Chemie', 'Mathematik', 'Wirtschaft'], 2,
        'Alle 4 Jahre an bis zu vier Mathematiker unter 40 vom Internationalen Mathematischen Kongress.',
        ['Fields-Medaille', 'Mathematik']),
    mc('q-bildung-105', 'bildung', 3,
        'Welcher deutsche Universalgelehrte lehrte im 18. Jahrhundert als Bibliothekar am Hof zu Wolfenbüttel und schrieb Nathan der Weise?',
        ['Gottfried Wilhelm Leibniz', 'Johann Wolfgang von Goethe', 'Gotthold Ephraim Lessing', 'Immanuel Kant'], 2,
        'Lessing (1729–1781) war Aufklärer, Dramatiker, Bibliothekar in Wolfenbüttel. Sein Werk „Nathan der Weise" propagiert religiöse Toleranz.',
        ['Lessing', 'Aufklärung']),
    mc('q-bildung-106', 'bildung', 3,
        'Wie heißt die weltweit renommierte britische Universität, gegründet 1209?',
        ['Oxford', 'Cambridge', 'Edinburgh', 'St Andrews'], 1,
        'Cambridge gegründet als Abspaltung von Oxford (1209). Oxford selbst geht wahrscheinlich auf ~1096 zurück.',
        ['Cambridge', 'UK']),
    mc('q-bildung-107', 'bildung', 4,
        'Welcher deutsche Pädagoge prägte den Slogan „Nicht für die Schule, sondern für das Leben lernen wir"?',
        ['Wilhelm von Humboldt', 'Friedrich Fröbel', 'Adolph Diesterweg', 'Seneca (paraphrasiert)'], 3,
        'Original von Seneca („non vitae, sed scholae discimus" — er beklagte, dass wir für die Schule lernen). Wird oft umgekehrt zitiert.',
        ['Seneca', 'Pädagogik']),
    mc('q-bildung-108', 'bildung', 2,
        'Welches internationale Vergleichsstudien-Programm der OECD misst regelmäßig Schülerleistungen?',
        ['PISA', 'TIMSS', 'PIRLS', 'IGLU'], 0,
        'Programme for International Student Assessment (seit 2000, alle 3 Jahre). Vergleicht 15-Jährige in Lesen, Mathematik und Naturwissenschaften.',
        ['PISA', 'OECD']),
    mc('q-bildung-109', 'bildung', 3,
        'Wer war der antike griechische Philosoph, der die Akademie in Athen gründete?',
        ['Sokrates', 'Platon', 'Aristoteles', 'Zenon'], 1,
        'Platon (~427–347 v. Chr.). Die Akademie war Vorbild für spätere Universitäten. Aristoteles gründete später das Lyzeum als Konkurrenz.',
        ['Platon', 'Akademie']),
    mc('q-bildung-110', 'bildung', 3,
        'Wie heißt die Doktorarbeit der theologischen Fakultäten in Deutschland traditionell?',
        ['Habilitation', 'Dissertation', 'Diplomarbeit', 'Staatsexamen'], 1,
        'Dissertation. Die Habilitation ist die zweite akademische Prüfung nach der Promotion, notwendig für die Professur.',
        ['Dissertation', 'Promotion']),
    mc('q-bildung-111', 'bildung', 4,
        'Wer gründete 1810 die Berliner Universität, deren Konzept moderne Forschungsuniversitäten prägt?',
        ['Alexander von Humboldt', 'Wilhelm von Humboldt', 'Friedrich Schleiermacher', 'Johann Gottlieb Fichte'], 1,
        'Wilhelm (der Bruder Alexanders). Sein Ideal: „Einheit von Forschung und Lehre", Bildung als Selbstzweck. Heute Humboldt-Universität zu Berlin.',
        ['Humboldt', 'Universität']),
    mc('q-bildung-112', 'bildung', 2,
        'Welche Sprache war das lange Zeit dominierende Medium der europäischen Wissenschaft bis ins 18. Jahrhundert?',
        ['Latein', 'Griechisch', 'Deutsch', 'Französisch'], 0,
        'Latein: Newton schrieb noch die „Principia" auf Latein (1687). Erst ab dem 19. Jahrhundert lösten Nationalsprachen es ab.',
        ['Latein', 'Wissenschaft']),
    mc('q-bildung-113', 'bildung', 3,
        'Welcher britische Physiker verfasste 1687 die „Philosophiae Naturalis Principia Mathematica"?',
        ['James Clerk Maxwell', 'Isaac Newton', 'Michael Faraday', 'William Herschel'], 1,
        'Newton begründete die klassische Mechanik. Trägheit, Actio=Reactio, Gravitation. Grundlage der Physik für über 200 Jahre.',
        ['Newton', 'Principia']),
    mc('q-bildung-114', 'bildung', 2,
        'Wie viele Jahre dauert ein typisches Medizinstudium in Deutschland (bis zur Approbation)?',
        ['4', '5', '6', '8'], 2,
        '6 Jahre, unterteilt in Vorklinik (2), Klinik (3), Praktisches Jahr (1). Danach: Approbation und Assistenzarzt-Weiterbildung.',
        ['Medizinstudium', 'Deutschland']),
    mc('q-bildung-115', 'bildung', 3,
        'Wer erhielt 1903 als erste Frau den Nobelpreis in Physik?',
        ['Lise Meitner', 'Marie Curie', 'Rosalind Franklin', 'Emmy Noether'], 1,
        'Marie Curie 1903 (Physik) und 1911 (Chemie) — bis heute die einzige Person mit Nobelpreisen in zwei verschiedenen Naturwissenschaften.',
        ['Marie Curie', 'Nobelpreis']),
    mc('q-bildung-116', 'bildung', 4,
        'Welches internationale Ranglisten-System bewertet Universitäten weltweit u. a. nach Forschung und Reputation?',
        ['ARWU (Shanghai-Ranking)', 'Times Higher Education', 'QS World University Rankings', 'Alle drei'], 3,
        'Die drei bekanntesten globalen Rankings. Es gibt große methodische Unterschiede — deshalb variieren die Ergebnisse deutlich.',
        ['Ranking']),
    mc('q-bildung-117', 'bildung', 2,
        'Welche Institution vergibt in Deutschland traditionell den Doktortitel?',
        ['Bundesregierung', 'Universitäten', 'Landesregierungen', 'Handelskammern'], 1,
        'Nur Universitäten (und promotionsberechtigte Hochschulen) haben Promotionsrecht. Die Fachrichtungen (Dr. med., Dr. phil. etc.) unterscheiden sich in Anforderungen.',
        ['Doktor', 'Promotion']),
    mc('q-bildung-118', 'bildung', 3,
        'Welches wissenschaftliche Werk gilt als Standardgrammatik der deutschen Sprache?',
        ['Wahrig', 'Duden', 'Meyer', 'Brockhaus'], 1,
        'Duden: „Die deutsche Rechtschreibung" (seit 1880) plus mehrere Bände zu Grammatik, Fremdwörter etc.',
        ['Duden']),
    mc('q-bildung-119', 'bildung', 3,
        'Welches Konzept der frühkindlichen Bildung entwickelte die italienische Ärztin Maria Montessori Anfang des 20. Jahrhunderts?',
        ['Waldorfpädagogik', 'Montessori-Pädagogik', 'Reggio-Pädagogik', 'Fröbel-Pädagogik'], 1,
        '„Hilf mir, es selbst zu tun." Selbstständiges Lernen mit vorbereiteter Umgebung. Waldorf wurde von Rudolf Steiner geprägt.',
        ['Montessori', 'Pädagogik']),

    # ================================================================
    # GESUNDHEIT & FITNESS (20)
    # ================================================================
    mc('q-gesundheit-100', 'gesundheit', 1,
        'Wie viel Wasser wird täglich für einen Erwachsenen als Richtwert empfohlen?',
        ['0,5 Liter', '1,5 Liter', '3 Liter', '5 Liter'], 1,
        'Rund 1,5 Liter zusätzlich zur Nahrung. Mehr bei Sport, Hitze oder Krankheit. DGE-Empfehlung.',
        ['Wasser', 'Ernährung']),
    mc('q-gesundheit-101', 'gesundheit', 2,
        'Welche Übung trainiert primär die Brustmuskulatur?',
        ['Kniebeuge', 'Bankdrücken', 'Klimmzug', 'Kreuzheben'], 1,
        'Bankdrücken zielt auf den Musculus pectoralis major, sekundär Trizeps und vordere Schulter.',
        ['Krafttraining', 'Brust']),
    mc('q-gesundheit-102', 'gesundheit', 2,
        'Welche Distanz umfasst ein klassischer Marathon-Lauf?',
        ['21,1 km', '30 km', '42,195 km', '50 km'], 2,
        'Standardisiert seit 1921. Bezieht sich auf die Legende von Pheidippides, der von Marathon nach Athen lief.',
        ['Marathon', 'Laufen']),
    mc('q-gesundheit-103', 'gesundheit', 3,
        'Welche Sportart wird international auf 42,195 km Länge in Städten wie Berlin und Boston ausgetragen?',
        ['Radrennen', 'Marathon', 'Triathlon', 'Wettschwimmen'], 1,
        'Berlin Marathon (Weltrekord-Kurs), Boston Marathon (ältester jährlicher Marathon der Welt seit 1897).',
        ['Marathon', 'Berlin']),
    mc('q-gesundheit-104', 'gesundheit', 2,
        'Welche Vitaminmangel-Krankheit führt zu weichen Knochen (Rachitis bei Kindern, Osteomalazie bei Erwachsenen)?',
        ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin K'], 2,
        'Vitamin-D-Mangel. In Regionen mit wenig Sonne im Winter empfehlen Ärzte oft Supplementierung.',
        ['Vitamin D', 'Mangelerkrankung']),
    mc('q-gesundheit-105', 'gesundheit', 2,
        'Was bewirkt regelmäßiges Ausdauertraining hauptsächlich auf das Herz?',
        [
            'Herz wird kleiner',
            'Herzschlag wird schneller',
            'Herz wird kräftiger und schlägt langsamer in Ruhe',
            'Herz wird schwächer',
        ], 2,
        'Sportlerherzen sind größer und stärker. Ruhepuls sinkt oft auf 40–50 Schläge/min (untrainiert: 60–80).',
        ['Ausdauer', 'Sportlerherz']),
    mc('q-gesundheit-106', 'gesundheit', 3,
        'Welche Yogaform ist dynamisch und synchronisiert Atmung mit fließenden Bewegungen?',
        ['Hatha Yoga', 'Vinyasa Yoga', 'Yin Yoga', 'Kundalini Yoga'], 1,
        'Vinyasa („in Fluss bringen") stammt aus dem Ashtanga. Jede Bewegung ist mit Ein- oder Ausatmung gekoppelt.',
        ['Yoga', 'Vinyasa']),
    mc('q-gesundheit-107', 'gesundheit', 2,
        'Welches Nährstoffprofil zeichnet die klassische mediterrane Ernährung aus?',
        [
            'Viel Fleisch, wenig Gemüse',
            'Viel Fisch, Olivenöl, Gemüse, wenig rotes Fleisch',
            'Nur Rohkost',
            'Ausschließlich fettarm',
        ], 1,
        'Studien zeigen: senkt Herz-Kreislauf-Risiko. UNESCO-Kulturerbe seit 2010.',
        ['Mediterrane Diät']),
    mc('q-gesundheit-108', 'gesundheit', 3,
        'Welche Schlafphase gilt als wichtigste Erholungsphase mit tiefer Regeneration und Wachstumshormon-Ausschüttung?',
        ['REM-Schlaf', 'Leichtschlaf N1', 'Leichtschlaf N2', 'Tiefschlaf N3'], 3,
        'N3 (Non-REM 3, „Slow-Wave-Sleep"). Vor allem in der ersten Nachthälfte. Wachstumshormone werden hier ausgeschüttet.',
        ['Schlaf', 'Tiefschlaf']),
    mc('q-gesundheit-109', 'gesundheit', 2,
        'Wie viele Kalorien enthält 1 Gramm Fett (grob)?',
        ['4 kcal', '7 kcal', '9 kcal', '12 kcal'], 2,
        'Fett: 9 kcal/g. Kohlenhydrate und Eiweiß: 4 kcal/g. Alkohol: 7 kcal/g.',
        ['Kalorien', 'Ernährung']),
    mc('q-gesundheit-110', 'gesundheit', 3,
        'Welche Sportart hat die geringste Verletzungsrate und wird oft Senioren empfohlen?',
        ['Fußball', 'Squash', 'Schwimmen', 'Basketball'], 2,
        'Schwimmen: geringe Belastung der Gelenke durch Wasser. Nordic Walking ähnlich.',
        ['Schwimmen', 'Senioren']),
    mc('q-gesundheit-111', 'gesundheit', 3,
        'Was misst der Body-Mass-Index (BMI)?',
        [
            'Körperfett direkt',
            'Verhältnis von Gewicht zu Größe',
            'Muskelmasse',
            'Ausdauer',
        ], 1,
        'BMI = Gewicht (kg) / Größe (m)². Normalgewicht: 18,5–25. Problem: unterscheidet nicht zwischen Fett und Muskel.',
        ['BMI', 'Gewicht']),
    mc('q-gesundheit-112', 'gesundheit', 2,
        'Welches Vitamin wird auch „Ascorbinsäure" genannt und findet sich reichlich in Zitrusfrüchten?',
        ['Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D'], 2,
        'Vitamin C: wichtig für das Immunsystem, Kollagenbildung, Wundheilung. Ein Mangel führte historisch zu Skorbut bei Seefahrern.',
        ['Vitamin C', 'Ascorbinsäure']),
    mc('q-gesundheit-113', 'gesundheit', 3,
        'Welches Hormon reguliert primär den Stoffwechsel und wird in der Schilddrüse produziert?',
        ['Insulin', 'Cortisol', 'Thyroxin (T4)', 'Melatonin'], 2,
        'T4 und T3 aus der Schilddrüse. Über- oder Unterproduktion führt zu Hyper-/Hypothyreose. Zentrale Rolle bei Wachstum und Energieumsatz.',
        ['Schilddrüse', 'Thyroxin']),
    mc('q-gesundheit-114', 'gesundheit', 2,
        'Wie viele Kilometer läuft man ungefähr bei 10 000 Schritten (übliche Empfehlung)?',
        ['3 km', '5 km', '7 km', '10 km'], 2,
        'Ungefähr 7 Kilometer, je nach Schrittlänge. Die 10 000-Empfehlung stammt aus einer japanischen Marketing-Kampagne 1965 („Manpo-kei").',
        ['Schritte', 'Bewegung']),
    mc('q-gesundheit-115', 'gesundheit', 3,
        'Welche Meditationsform basiert auf Achtsamkeit im gegenwärtigen Moment und wird oft in klinischen Programmen (MBSR) eingesetzt?',
        ['Zazen', 'Transzendentale Meditation', 'Mindfulness / Achtsamkeit', 'Vipassana'], 2,
        'Mindfulness Based Stress Reduction wurde 1979 von Jon Kabat-Zinn entwickelt. Basiert lose auf Vipassana-Meditation.',
        ['Achtsamkeit', 'Meditation']),
    mc('q-gesundheit-116', 'gesundheit', 4,
        'Welches sportmedizinische Konzept beschreibt einen intensiven Wechsel von Belastung und kurzer Erholung?',
        ['HIIT (High-Intensity Interval Training)', 'LISS (Low-Intensity Steady State)', 'CrossFit', 'Isolationstraining'], 0,
        'HIIT: kurze Belastungen (30 s–2 min) mit hoher Intensität, kurze Pausen. Sehr effizient bei Zeitmangel — Studien zeigen ähnliche Vorteile wie längeres Ausdauertraining.',
        ['HIIT', 'Training']),
    mc('q-gesundheit-117', 'gesundheit', 2,
        'Welche Ernährung schließt alle tierischen Produkte aus, einschließlich Milch und Eier?',
        ['Vegetarisch', 'Vegan', 'Pescetarisch', 'Flexitarisch'], 1,
        'Vegetarier verzichten auf Fleisch, essen aber Milchprodukte/Eier (ovo-lacto). Veganer schließen alles Tierische aus.',
        ['Vegan', 'Ernährung']),
    mc('q-gesundheit-118', 'gesundheit', 3,
        'Welche typische Herzfrequenz sollte ein gesunder Erwachsener in Ruhe haben?',
        ['30–40 pro Minute', '60–80 pro Minute', '100–120 pro Minute', '150+ pro Minute'], 1,
        'Trainierte Ausdauersportler oft nur 40–50. Über 100 in Ruhe: Tachykardie, oft symptomatisch für Krankheit oder Stress.',
        ['Puls', 'Herz']),
    mc('q-gesundheit-119', 'gesundheit', 3,
        'Welcher Bewegungsstil geht auf einen chinesischen Kampfkunst-Klassiker zurück und wird oft langsam im Park geübt?',
        ['Kung Fu', 'Karate', 'Tai Chi', 'Aikido'], 2,
        'Tai Chi Chuan („Schattenboxen") ist ursprünglich eine Kampfkunst, wird heute vorwiegend als Gesundheitsübung mit langsamen fließenden Bewegungen ausgeübt.',
        ['Tai Chi']),

    # ================================================================
    # REISEN & URLAUB (20)
    # ================================================================
    mc('q-reisen-100', 'reisen', 1,
        'Welches ist mit über 8 800 m der höchste Berg der Erde und ein Ziel für Extremtouristen?',
        ['K2', 'Mount Everest', 'Kangchendzönga', 'Lhotse'], 1,
        'Mount Everest, 8 848,86 m, an der Grenze Nepal/Tibet. Erstbestieger: Edmund Hillary und Tenzing Norgay 1953.',
        ['Everest', 'Bergsteigen']),
    mc('q-reisen-101', 'reisen', 2,
        'Welches Land wird am meisten von internationalen Touristen besucht (Rang 1 weltweit über viele Jahre)?',
        ['USA', 'Frankreich', 'Spanien', 'Italien'], 1,
        'Frankreich ~90 Millionen Besucher/Jahr. Paris, Riviera, Loire-Schlösser als Zugmagneten. Spanien Nummer 2.',
        ['Tourismus', 'Frankreich']),
    mc('q-reisen-102', 'reisen', 2,
        'In welcher Stadt findet man den Eiffelturm?',
        ['London', 'Berlin', 'Paris', 'Rom'], 2,
        'Paris. Erbaut zur Weltausstellung 1889 (100 Jahre Französische Revolution). 324 Meter hoch mit Antenne. Baumeister: Gustave Eiffel.',
        ['Eiffelturm', 'Paris']),
    mc('q-reisen-103', 'reisen', 1,
        'Welche Insel im Mittelmeer ist die größte und gehört zu Italien?',
        ['Korsika', 'Sardinien', 'Sizilien', 'Malta'], 2,
        'Sizilien. 25 700 km². Sardinien liegt Platz 2 (Italien), Korsika (Frankreich) Platz 4. Zypern ist die drittgrößte.',
        ['Sizilien', 'Mittelmeer']),
    mc('q-reisen-104', 'reisen', 2,
        'Wie heißt die Route, die in Spanien viele Pilger nach Santiago de Compostela führt?',
        ['Via Dolorosa', 'Jakobsweg', 'Rossignol', 'Ruta 66'], 1,
        'Jakobsweg (Camino de Santiago). Grab des Apostels Jakobus des Älteren. Bekanntester Startpunkt: Saint-Jean-Pied-de-Port in Frankreich.',
        ['Jakobsweg', 'Pilgerreise']),
    mc('q-reisen-105', 'reisen', 3,
        'Welches Land besitzt die längste Nord-Süd-Ausdehnung eines Kontinentalstaates (fast 4 300 km)?',
        ['USA', 'Kanada', 'Brasilien', 'Chile'], 3,
        'Chile: 4 270 km lang, aber nur ~180 km breit im Durchschnitt.',
        ['Chile', 'Geografie']),
    mc('q-reisen-106', 'reisen', 3,
        'Welche berühmte Grand-Canyon-Formation liegt in welchem US-Bundesstaat?',
        ['Nevada', 'Utah', 'Arizona', 'Colorado'], 2,
        'Arizona. Der Grand Canyon des Colorado River, ~450 km lang und bis 1 800 m tief. UNESCO-Welterbe seit 1979.',
        ['Grand Canyon', 'Arizona']),
    mc('q-reisen-107', 'reisen', 2,
        'Wie heißt das größte lebende Bauwerk der Erde und ein beliebter Tauchspot vor Australien?',
        ['Ayers Rock', 'Great Barrier Reef', 'Uluru', 'Ningaloo Reef'], 1,
        'Great Barrier Reef, über 2 300 km entlang Queenslands. Sichtbar aus dem All. UNESCO-Welterbe.',
        ['Barrier Reef', 'Australien']),
    mc('q-reisen-108', 'reisen', 2,
        'Welche Weltstadt ist auf über 100 kleinen Inseln in einer Lagune erbaut und ist berühmt für ihre Kanäle und Gondeln?',
        ['Amsterdam', 'Sankt Petersburg', 'Venedig', 'Bangkok'], 2,
        'Venedig, Norditalien. Aufbau seit dem 5. Jahrhundert. 118 Inseln, verbunden durch 400 Brücken.',
        ['Venedig', 'Kanäle']),
    mc('q-reisen-109', 'reisen', 3,
        'Welche legendäre Wüstenstadt in Jordanien ist wegen ihrer aus dem Fels gehauenen Fassaden UNESCO-Welterbe?',
        ['Palmyra', 'Petra', 'Baalbek', 'Timgad'], 1,
        'Petra, Hauptstadt der Nabatäer. Berühmt durch das Schatzhaus („Khazneh"). Filmkulisse für Indiana Jones „Der letzte Kreuzzug".',
        ['Petra', 'Jordanien']),
    mc('q-reisen-110', 'reisen', 3,
        'Wie heißt der Sprung ins Meer/Sprungfelsen der jährlich am „Nervenkitzel-Tag" in Acapulco (Mexiko) stattfindet?',
        ['La Quebrada', 'Cliff Cape', 'Salto Angel', 'Bungee Diver'], 0,
        'La Quebrada seit den 1930ern. Klippenspringer stürzen aus 35–40 Metern in eine schmale Bucht — der Sprung muss mit der Welle exakt getimt sein.',
        ['La Quebrada', 'Klippenspringen']),
    mc('q-reisen-111', 'reisen', 2,
        'In welcher Stadt landet man am Flughafen JFK?',
        ['Los Angeles', 'New York', 'Chicago', 'Miami'], 1,
        'John F. Kennedy International Airport in Queens, New York. Meiste internationale Passagiere aller US-Airports.',
        ['JFK', 'New York']),
    mc('q-reisen-112', 'reisen', 3,
        'Welche europäische Hauptstadt liegt am Fluss Moldau und ist berühmt für Karlsbrücke und Astronomische Uhr?',
        ['Warschau', 'Prag', 'Wien', 'Budapest'], 1,
        'Prag, Tschechien. Die Astronomische Uhr am Altstädter Rathaus stammt aus 1410. Karlsbrücke ab 1357 unter Karl IV. erbaut.',
        ['Prag', 'Moldau']),
    mc('q-reisen-113', 'reisen', 3,
        'Welcher berühmte Wanderweg führt durch die kalifornischen Sierras und den Yosemite-Nationalpark?',
        ['Appalachian Trail', 'Pacific Crest Trail', 'John-Muir-Trail', 'Continental Divide'], 2,
        'John-Muir-Trail: 340 km, verläuft komplett in der Sierra Nevada. Der PCT ist länger (4 265 km) und geht von Mexiko nach Kanada.',
        ['Wandern', 'Kalifornien']),
    mc('q-reisen-114', 'reisen', 2,
        'Wie heißt das oberdeutsche Volksfest, das jährlich Millionen Besucher nach München zieht?',
        ['Oktoberfest', 'Cannstatter Wasen', 'Karneval', 'Frühlingsfest'], 0,
        'Oktoberfest auf der Theresienwiese seit 1810 (Hochzeit König Ludwigs I.). Rund 6 Millionen Besucher/Jahr.',
        ['Oktoberfest', 'München']),
    mc('q-reisen-115', 'reisen', 3,
        'Welcher gewaltige Wasserfall an der Grenze zwischen Sambia und Simbabwe ist einer der breitesten der Erde?',
        ['Niagarafälle', 'Iguazú-Wasserfälle', 'Victoriafälle', 'Angel Falls'], 2,
        'Victoriafälle am Sambesi: 1 708 m breit, 108 m Fallhöhe. Von David Livingstone 1855 zum ersten Mal von einem Europäer beschrieben.',
        ['Victoriafälle']),
    mc('q-reisen-116', 'reisen', 4,
        'Welche Route der ersten Weltumseglung fuhr Ferdinand Magellan 1519 an?',
        [
            'Um Afrika Richtung Osten',
            'Um Südamerika Richtung Westen',
            'Durch den Nord-West-Passage',
            'Durch den Suezkanal',
        ], 1,
        'Magellan fand die nach ihm benannte Meerenge zwischen Feuerland und dem Festland. Er selbst starb 1521 auf den Philippinen; nur ein Schiff der Flotte kehrte 1522 zurück.',
        ['Magellan', 'Weltumseglung']),
    mc('q-reisen-117', 'reisen', 2,
        'Welche Metropole ist Japans größte Stadt und beherbergt den größten Fischmarkt der Welt (Toyosu)?',
        ['Kyoto', 'Tokio', 'Osaka', 'Nagoya'], 1,
        'Tokio (früher Edo). Über 37 Mio. Menschen im Ballungsraum. Der Toyosu-Markt ersetzte 2018 den weltberühmten Tsukiji-Markt.',
        ['Tokio', 'Japan']),
    mc('q-reisen-118', 'reisen', 3,
        'In welcher afrikanischen Wüste wandern jährlich Zehntausende von Gnus auf ihrer „Great Migration"?',
        ['Sahara', 'Kalahari', 'Serengeti (Savanne)', 'Namib'], 2,
        'Serengeti ist eine Savanne, keine Wüste. Über 1,5 Millionen Gnus wandern jährlich im Rhythmus der Regenzeit zwischen Tansania und Kenia.',
        ['Serengeti', 'Wanderung']),
    mc('q-reisen-119', 'reisen', 2,
        'Welche Insel-Hauptstadt liegt in der Karibik und ist ein beliebter Kreuzfahrt-Zwischenstopp mit spanisch-kolonialer Altstadt?',
        ['Havanna', 'Kingston', 'Bridgetown', 'San Juan'], 3,
        'San Juan, Puerto Rico. „Old San Juan" ist UNESCO-Welterbe (Kolonialarchitektur seit 1521).',
        ['San Juan', 'Karibik']),

    # ================================================================
    # AUTOS & VERKEHR (20)
    # ================================================================
    mc('q-autos-100', 'autos', 1,
        'Welche deutsche Automarke gehört zum Konzern Volkswagen und stellt Premium-Fahrzeuge in Ingolstadt her?',
        ['BMW', 'Audi', 'Mercedes-Benz', 'Porsche (nur)'], 1,
        'Audi AG, Sitz Ingolstadt. Weiteres Werk in Neckarsulm. Teil des VW-Konzerns seit 1966.',
        ['Audi', 'Ingolstadt']),
    mc('q-autos-101', 'autos', 1,
        'Welches Land hat die weltweit meisten Autos pro Einwohner (rund 90 pro 100 Personen)?',
        ['USA', 'Deutschland', 'Luxemburg', 'Japan'], 2,
        'Luxemburg: ~90 Pkw pro 100 Einwohner. Auch USA hoch (~85). Deutschland ~58.',
        ['Motorisierung', 'Statistik']),
    mc('q-autos-102', 'autos', 2,
        'Wer gründete 1899 das Automobilunternehmen Fiat in Turin?',
        ['Giovanni Agnelli', 'Enzo Ferrari', 'Sergio Marchionne', 'Michele Alboreto'], 0,
        'Fabbrica Italiana Automobili Torino — F.I.A.T. Gemeinsam mit Investoren. Bis heute größter italienischer Autohersteller.',
        ['Fiat', 'Agnelli']),
    mc('q-autos-103', 'autos', 2,
        'Welche Automarke stellte das legendäre Modell „Käfer" her, das über 21 Millionen Mal gebaut wurde?',
        ['Opel', 'Volkswagen', 'Ford', 'BMW'], 1,
        'VW Käfer: Produktion 1938–2003. Bis 2003 das meistgebaute Fahrzeug der Welt, seither übertroffen vom VW Golf.',
        ['Käfer', 'VW']),
    mc('q-autos-104', 'autos', 3,
        'Welche italienische Sportwagen-Marke hat ein springendes Pferd („Cavallino Rampante") im Logo?',
        ['Lamborghini', 'Alfa Romeo', 'Maserati', 'Ferrari'], 3,
        'Ferrari, gegründet 1939 in Maranello. Das Pferd stammt vom Wappen des italienischen Piloten Francesco Baracca.',
        ['Ferrari', 'Sportwagen']),
    mc('q-autos-105', 'autos', 2,
        'Welche schwedische Marke ist bekannt für ihre Fokus auf Sicherheit und wurde 2010 von einem chinesischen Konzern übernommen?',
        ['Saab', 'Volvo', 'Koenigsegg', 'Scania'], 1,
        'Volvo, seit 2010 im Besitz von Geely (China). Volvo erfand 1959 den Dreipunkt-Sicherheitsgurt und gab das Patent frei.',
        ['Volvo', 'Geely']),
    mc('q-autos-106', 'autos', 3,
        'Wie hoch war 2023 die Höchstgeschwindigkeit eines serienmäßigen Elektroautos (~415 km/h)?',
        ['Tesla Model S Plaid', 'Porsche Taycan', 'Rimac Nevera', 'Lucid Air'], 2,
        'Rimac Nevera (Kroatien): 412 km/h Spitze, 1 914 PS. 100 km/h in 1,85 s.',
        ['Rimac', 'Elektroauto']),
    mc('q-autos-107', 'autos', 2,
        'Welche Automarke gehört zum Stellantis-Konzern und stellt Modelle wie 208, 3008 her?',
        ['Renault', 'Peugeot', 'Citroën', 'Volvo'], 1,
        'Peugeot ist Teil von Stellantis (seit 2021 aus Fusion PSA + FCA). Der Löwe im Logo geht auf 1858 zurück.',
        ['Peugeot', 'Stellantis']),
    mc('q-autos-108', 'autos', 3,
        'Welches Auto war der erste in Serie hergestellte Wagen mit Fließbandfertigung, ab 1908?',
        ['Ford Model T', 'Cadillac Type 51', 'Rolls-Royce Silver Ghost', 'Benz Patent-Motorwagen'], 0,
        'Ford Model T („Tin Lizzie"). Fließband ab 1913 in Highland Park, Michigan. Fertigungszeit sank von 12 h auf 90 Minuten.',
        ['Ford T', 'Fließband']),
    mc('q-autos-109', 'autos', 2,
        'Was bedeutet die Abkürzung „SUV"?',
        [
            'Sport Utility Vehicle',
            'Special Utility Version',
            'Super Urban Van',
            'Standard Utility Van',
        ], 0,
        'SUV: geländegängige Fahrzeuge mit hohem Aufbau. Populär geworden ab den 1990ern in den USA.',
        ['SUV', 'Fahrzeugklasse']),
    mc('q-autos-110', 'autos', 2,
        'Wer gründete 1903 die Ford Motor Company?',
        ['Henry Ford', 'Ransom Olds', 'Louis Chevrolet', 'Karl Benz'], 0,
        'Henry Ford in Detroit, Michigan. Revolutionierte 1913 mit dem Fließband die Automobilproduktion.',
        ['Ford', 'Detroit']),
    mc('q-autos-111', 'autos', 3,
        'Welches Land hat den weltweit größten Automarkt seit 2009 (nach Neuwagenverkäufen)?',
        ['USA', 'China', 'Japan', 'Deutschland'], 1,
        'China: ~28 Millionen verkaufte Neuwagen 2023. USA ~15,5 Mio. Deutschland ~2,8 Mio.',
        ['China', 'Automarkt']),
    mc('q-autos-112', 'autos', 3,
        'Welcher deutsche Ingenieur baute 1885 das erste Automobil mit Verbrennungsmotor?',
        ['Rudolf Diesel', 'Karl Benz', 'Nikolaus Otto', 'Wilhelm Maybach'], 1,
        'Karl Benz, Patent-Motorwagen Nr. 1, Mannheim. Am 3. Juli 1886 die erste öffentliche Fahrt.',
        ['Benz', 'Patent-Motorwagen']),
    mc('q-autos-113', 'autos', 2,
        'Welches ist derzeit das meistverkaufte Elektroauto-Modell der Welt?',
        ['Tesla Model 3', 'Tesla Model Y', 'BYD Song', 'Nissan Leaf'], 1,
        'Tesla Model Y: seit 2023 auch das meistverkaufte Auto überhaupt (nicht nur E-Auto). Rund 1,2 Millionen Einheiten 2023.',
        ['Tesla', 'Model Y']),
    mc('q-autos-114', 'autos', 3,
        'Wie heißt der berühmteste Motorsport-Wettbewerb, der auf einer 20 km langen Rennstrecke in der Eifel stattfindet?',
        ['24 Stunden von Le Mans', '24 Stunden vom Nürburgring', 'Daytona 500', 'Monaco Grand Prix'], 1,
        '24-Stunden-Rennen auf der Nürburgring-Nordschleife („Grüne Hölle"), jährlich seit 1970.',
        ['Nürburgring', '24h']),
    mc('q-autos-115', 'autos', 2,
        'Was verbraucht ein modernes Elektroauto typischerweise pro 100 km (Batterie-Energie)?',
        ['1–3 kWh', '6–8 kWh', '15–20 kWh', '40–50 kWh'], 2,
        'Typischer Wert 15–20 kWh/100 km. Tesla Model 3 SR+ ~14 kWh. Klein-SUV ~20 kWh. Vergleich Verbrenner: ~50 kWh/100 km energetisch.',
        ['Elektroauto', 'Verbrauch']),
    mc('q-autos-116', 'autos', 3,
        'Wer erfand 1892 den nach ihm benannten Motor, dessen Selbstzündung Diesel-Fahrzeuge antreibt?',
        ['Rudolf Diesel', 'Karl Benz', 'Nikolaus Otto', 'Gottlieb Daimler'], 0,
        'Rudolf Diesel, deutscher Ingenieur. Patent 1892. Robuster und effizienter als der Otto-Motor.',
        ['Diesel', 'Motor']),
    mc('q-autos-117', 'autos', 2,
        'Welche deutsche Autobahn ist die älteste als Autobahn geplante Strecke (Fertigstellung 1932)?',
        ['A5 Karlsruhe–Basel', 'A555 Köln–Bonn', 'A9 München–Berlin', 'A2 Ruhrgebiet–Berlin'], 1,
        'A555 zwischen Köln und Bonn, 20 km. Eröffnet 1932 als kreuzungsfreie Kraftwagen-Straße unter Konrad Adenauer als OB Köln.',
        ['Autobahn', 'A555']),
    mc('q-autos-118', 'autos', 3,
        'Welches ist das Nummernschild-Kürzel für Motorräder in Deutschland?',
        ['MR', 'MT', 'M-Kennzeichen (Zusatz)', 'Kein spezielles Kürzel'], 3,
        'Motorräder haben das gleiche System wie Autos, nur in kleinerer Nummernschild-Größe. Es gibt kein spezielles Kürzel.',
        ['Kennzeichen', 'Motorrad']),
    mc('q-autos-119', 'autos', 3,
        'Welcher chinesische Autohersteller überholte 2023 Tesla als weltweit größter Elektroauto-Produzent?',
        ['NIO', 'BYD', 'XPeng', 'Li Auto'], 1,
        'BYD („Build Your Dreams"): 3 Millionen verkaufte E-Autos/Hybride 2023. Warren Buffett ist ein bekannter Investor.',
        ['BYD', 'China', 'Elektroauto']),
]


def main() -> int:
    with QUESTIONS_PATH.open('r', encoding='utf-8') as f:
        existing = json.load(f)
    existing_ids = {q['id'] for q in existing}
    to_add = [q for q in NEW_QUESTIONS if q['id'] not in existing_ids]
    if not to_add:
        print('Keine neuen Fragen.')
        return 0
    for q in to_add:
        assert len(q['options']) == 4
        assert 0 <= q['correctIndex'] < 4
    merged = existing + to_add
    with QUESTIONS_PATH.open('w', encoding='utf-8') as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
        f.write('\n')
    from collections import Counter
    print(f'✓ {len(to_add)} neue Fragen ergänzt (jetzt {len(merged)} insgesamt).')
    for t, c in sorted(Counter(q['topic'] for q in to_add).items()):
        print(f'  + {t:<14} {c}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
