#!/usr/bin/env python3
"""Batch 4: umwelt, wetter, hobbys, handwerk (80 Fragen)."""
from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
QUESTIONS_PATH = ROOT / 'packages' / 'shared' / 'src' / 'data' / 'questions.json'
NOW = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
MC_MODES = ['category-duel', 'flash', 'player-spotlight', 'sprinter',
            'points-ladder', 'category-board', 'duel-1v1', 'elimination', 'experts']


def mc(qid, topic, difficulty, question, options, correct, gm, tags, category='allgemeinbildung'):
    return {'id': qid, 'type': 'multiple-choice', 'status': 'approved',
        'category': category, 'topic': topic, 'difficulty': difficulty,
        'question': question, 'options': options, 'correctIndex': correct,
        'gmNote': gm, 'tags': tags, 'compatibleModes': MC_MODES,
        'timeScope': 'timeless', 'aiGenerated': True,
        'createdAt': NOW, 'updatedAt': NOW}


NEW_QUESTIONS = []

# UMWELT & KLIMA (20)
NEW_QUESTIONS += [
    mc('q-umwelt-100', 'umwelt', 1,
        'Welches Gas gilt als Hauptursache des menschgemachten Klimawandels?',
        ['Sauerstoff', 'Methan', 'Kohlendioxid (CO2)', 'Stickstoff'], 2,
        'CO2 aus Verbrennung fossiler Brennstoffe. Methan ist pro Molekül stärker klimawirksam, aber CO2 ist wegen der Mengen der dominante Treiber.',
        ['CO2', 'Klimawandel']),
    mc('q-umwelt-101', 'umwelt', 2,
        'Welches Abkommen von 2015 verpflichtet Staaten zur Begrenzung der Erderwärmung auf möglichst 1,5 °C?',
        ['Kyoto-Protokoll', 'Pariser Klimaabkommen', 'Rio-Deklaration', 'Montreal-Protokoll'], 1,
        'Pariser Klimaabkommen (COP 21). 196 Staaten haben es unterzeichnet. Ziel: deutlich unter 2 °C, möglichst 1,5 °C gegenüber vorindustriellem Niveau.',
        ['Paris', 'Klimaabkommen']),
    mc('q-umwelt-102', 'umwelt', 2,
        'Welche erneuerbare Energiequelle nutzt die kinetische Energie fließender Luft?',
        ['Wasserkraft', 'Windkraft', 'Solarenergie', 'Geothermie'], 1,
        'Windenergie: 2023 in Deutschland ~26 % des Bruttostroms. Weltweit größter Onshore-Windpark: Gansu (China).',
        ['Windkraft', 'Erneuerbar']),
    mc('q-umwelt-103', 'umwelt', 2,
        'Welches Material aus Erdöl braucht Jahrhunderte, um in der Natur zu zerfallen?',
        ['Holz', 'Karton', 'Plastik', 'Textilien'], 2,
        'Plastik (v. a. PET, PE, PP): 100–1 000 Jahre. Meere enthalten schätzungsweise 150 Mio. Tonnen Kunststoffabfall.',
        ['Plastik', 'Abfall']),
    mc('q-umwelt-104', 'umwelt', 3,
        'Was ist die „Ozonschicht"?',
        [
            'CO2-Schicht in der Erdatmosphäre',
            'Schutzschicht in der Stratosphäre, filtert UV-Strahlung',
            'Wolken der Troposphäre',
            'Magnetfeld um die Erde',
        ], 1,
        'Ozon (O3) in ~15–35 km Höhe. Wurde in den 1980ern durch FCKW schwer geschädigt. Montreal-Protokoll 1987 hat die Emissionen eingeschränkt — die Schicht regeneriert sich.',
        ['Ozonschicht', 'Klimaschutz']),
    mc('q-umwelt-105', 'umwelt', 2,
        'Was ist der ökologische Fußabdruck?',
        [
            'Fläche, die ein Mensch/Land für seinen Konsum benötigt',
            'CO2-Ausstoß pro Kopf',
            'Anzahl gepflanzter Bäume',
            'Anzahl Recyclingtonnen',
        ], 0,
        'Konzept von 1994 von Mathis Wackernagel und William Rees. Deutscher Durchschnitt: ~5 gha (globale Hektar), bio-verträglich wären ~1,7 gha.',
        ['Fußabdruck', 'Nachhaltigkeit']),
    mc('q-umwelt-106', 'umwelt', 3,
        'Welche Substanzen sind hauptverantwortlich für das „Waldsterben" der 1980er in Mitteleuropa?',
        ['CO2', 'FCKW', 'Schwefeldioxid (SO2)', 'Methan'], 2,
        'SO2 aus Kohleverbrennung führte zu saurem Regen. Deutsche Waldschäden erreichten 1985 ihren Höhepunkt. Rauchgasentschwefelung ab den 1990ern.',
        ['Saurer Regen', 'SO2']),
    mc('q-umwelt-107', 'umwelt', 3,
        'Welches Land ist der weltweit größte CO2-Emittent (absolute Werte, Stand 2023)?',
        ['USA', 'China', 'Indien', 'Russland'], 1,
        'China: ~11 Milliarden Tonnen CO2/Jahr (~30 % weltweit). Pro Kopf allerdings viel niedriger als USA (~15 t vs. ~7 t).',
        ['China', 'CO2']),
    mc('q-umwelt-108', 'umwelt', 3,
        'Welches Gebirgsökosystem ist wegen des Klimawandels besonders bedroht (Gletscherrückzug)?',
        ['Sahara', 'Alpen', 'Amazonas', 'Ozeane'], 1,
        'Alpen: Gletscher haben seit 1900 die Hälfte ihres Volumens verloren. Extremrückgang seit 2000.',
        ['Alpen', 'Gletscher']),
    mc('q-umwelt-109', 'umwelt', 3,
        'Wer prägte 2018 die weltweite Klimaschutz-Schulstreik-Bewegung „Fridays for Future"?',
        ['Vanessa Nakate', 'Greta Thunberg', 'Al Gore', 'Luisa Neubauer'], 1,
        'Schülerin Greta Thunberg (geb. 2003, Schweden). Startete August 2018 einen Sitzstreik vor dem schwedischen Parlament. Auszeichnung Amnesty International 2019.',
        ['Fridays for Future', 'Thunberg']),
    mc('q-umwelt-110', 'umwelt', 2,
        'Welches Land hat 1971 den Umweltschutz erstmalig als Verfassungsziel verankert?',
        ['Deutschland', 'Schweiz', 'DDR', 'Schweden'], 1,
        'Die Schweiz führte das Umweltschutz-Kapitel 1971 in die Verfassung ein. Deutschland folgte 1994 mit Art. 20a GG.',
        ['Umweltschutz', 'Verfassung']),
    mc('q-umwelt-111', 'umwelt', 3,
        'Welche „Insel" aus Müll treibt im Pazifik und ist etwa dreimal so groß wie Frankreich?',
        ['Sargasso Sea', 'Great Pacific Garbage Patch', 'Atlantic Garbage Island', 'Indian Ocean Gyre'], 1,
        'Great Pacific Garbage Patch: ~1,6 Mio. km² Mikroplastik im Nordpazifischen Wirbel. Boyan Slats „The Ocean Cleanup" versucht Bereinigung.',
        ['Müll', 'Pazifik', 'Plastik']),
    mc('q-umwelt-112', 'umwelt', 3,
        'Welche Baumart gilt als CO2-Speicher-Champion und wird für Aufforstung besonders geschätzt?',
        ['Fichte', 'Eiche', 'Buche', 'Es kommt auf Alter und Standort an'], 3,
        'Alte Wälder speichern mehr CO2 als junge Aufforstungen. Buchen und Eichen sind langlebig; Fichten wachsen schneller, sind aber klimavulnerabler.',
        ['Aufforstung', 'CO2']),
    mc('q-umwelt-113', 'umwelt', 4,
        'Wie hoch wird der Meeresspiegel-Anstieg bis 2100 im Worst-Case-Klimaszenario der IPCC prognostiziert?',
        ['10 cm', '50 cm', '~1 m', '5 m'], 2,
        'Bis zu ~1 m in Worst-Case-Szenarien (RCP 8.5). Grund: Ozean-Wärmeausdehnung + schmelzendes Landeis Grönland/Antarktis.',
        ['Meeresspiegel', 'IPCC']),
    mc('q-umwelt-114', 'umwelt', 2,
        'Was ist „Recycling"?',
        [
            'Neue Rohstoffe kaufen',
            'Wiederverwendung von Materialien im Kreislauf',
            'Verbrennung von Müll',
            'Deponierung',
        ], 1,
        'Kreislaufwirtschaft. Deutschland ist Recycling-Weltmeister (60 %+ Rate). Größte Herausforderung: Plastik und Verbundstoffe.',
        ['Recycling', 'Kreislaufwirtschaft']),
    mc('q-umwelt-115', 'umwelt', 3,
        'Welches Übereinkommen von 1987 hat wirksam die Ozonschicht-Zerstörung gestoppt?',
        ['Kyoto', 'Montreal-Protokoll', 'Paris', 'Rio'], 1,
        'Montreal-Protokoll (16. September 1987): Verbot der FCKW. Von allen UN-Staaten ratifiziert — das erfolgreichste Umweltabkommen der Geschichte.',
        ['Montreal-Protokoll', 'Ozon']),
    mc('q-umwelt-116', 'umwelt', 2,
        'Welches Prinzip beschreibt, dass umweltschädliches Verhalten Kosten verursacht, die vom Verursacher zu tragen sind?',
        ['Vorsorgeprinzip', 'Verursacherprinzip', 'Vorurteilsprinzip', 'Gerechtigkeitsprinzip'], 1,
        'Verursacherprinzip: Grundlage vieler Umweltgesetze (CO2-Preis, Emissionshandel). In EU: verankert im Vertrag über die Arbeitsweise der Union.',
        ['Verursacherprinzip', 'Umweltrecht']),
    mc('q-umwelt-117', 'umwelt', 3,
        'In welchem Jahrzehnt begann die moderne Umweltbewegung mit Rachel Carsons Buch „Der stumme Frühling"?',
        ['1950er', '1960er', '1970er', '1980er'], 1,
        '„Silent Spring" erschien 1962. Prangerte die Auswirkungen von DDT auf die Vogelwelt an. Führte 1972 zum DDT-Verbot in den USA.',
        ['Silent Spring', 'Carson']),
    mc('q-umwelt-118', 'umwelt', 3,
        'Welche Energiequelle deckt in Deutschland aktuell den größten Anteil am Strommix (Stand 2023)?',
        ['Kernkraft', 'Erneuerbare Energien', 'Kohle', 'Erdgas'], 1,
        '2023 lieferten Erneuerbare erstmals mehr als 50 % der Bruttostromerzeugung. Wind, Solar, Biomasse führen — Kernkraft abgeschaltet April 2023.',
        ['Erneuerbare', 'Strommix']),
    mc('q-umwelt-119', 'umwelt', 4,
        'Welches Zusatzziel des Pariser Abkommens gilt für den EU-Green-Deal ab 2050?',
        [
            'Klimaneutralität',
            'CO2-Reduktion um 20 %',
            'Fleischverbot',
            'Auto-Verbot',
        ], 0,
        'Klimaneutralität 2050: Nettoemissionen null. Dazwischen: minus 55 % bis 2030 gegenüber 1990. EU-Klimagesetz 2021 rechtsverbindlich.',
        ['Green Deal', 'Klimaneutralität']),
]

# WETTER & NATURPHÄNOMENE (20)
NEW_QUESTIONS += [
    mc('q-wetter-100', 'wetter', 1,
        'Wie heißt ein Wirbelsturm im Nordwest-Pazifik (z. B. vor Japan/Philippinen)?',
        ['Hurrikan', 'Taifun', 'Zyklon', 'Tornado'], 1,
        'Alle drei bezeichnen dasselbe Wetterphänomen: Nordatlantik/Ostpazifik → Hurrikan. Nordwestpazifik → Taifun. Indischer Ozean → Zyklon.',
        ['Taifun', 'Sturm']),
    mc('q-wetter-101', 'wetter', 1,
        'Was misst ein Barometer?',
        ['Windgeschwindigkeit', 'Luftdruck', 'Temperatur', 'Luftfeuchtigkeit'], 1,
        'Luftdruck in hPa (Hektopascal) oder mm Hg. Normaldruck auf Meereshöhe: 1013 hPa. Fallender Druck → Wetterumschwung.',
        ['Barometer', 'Luftdruck']),
    mc('q-wetter-102', 'wetter', 2,
        'Welche Farben hat ein Regenbogen und in welcher Reihenfolge (außen nach innen)?',
        [
            'Rot, Orange, Gelb, Grün, Blau, Indigo, Violett',
            'Violett, Blau, Grün, Gelb, Orange, Rot',
            'Nur Rot, Gelb und Blau',
            'Alle Farben zufällig',
        ], 0,
        'Newton beschrieb sieben Farben, wobei Indigo umstritten ist. Merksatz: „ROY G BIV" (Red-Orange-Yellow-Green-Blue-Indigo-Violet).',
        ['Regenbogen', 'Optik']),
    mc('q-wetter-103', 'wetter', 2,
        'Wie hoch kann ein Blitz Temperaturen erreichen?',
        ['1 000 °C', '5 000 °C', '10 000 °C', '~30 000 °C'], 3,
        'Rund 30 000 °C — heißer als die Sonnenoberfläche (~5 500 °C). Ein Blitz liefert Millionen Volt und schlägt in 1 Millisekunde ein.',
        ['Blitz', 'Temperatur']),
    mc('q-wetter-104', 'wetter', 3,
        'Was ist ein Föhn (Wetterphänomen)?',
        [
            'Kalter Nordostwind aus Sibirien',
            'Warmer, trockener Wind aus dem Süden der Alpen',
            'Nebelwolke am Meer',
            'Aufsteigender Warmluftstrom in den Tropen',
        ], 1,
        'Föhn: adiabatisch aufgeheizte Luft, die von den Alpen abwärts ins Nordvorland strömt. Kann Kopfschmerzen und Konzentrationsstörungen auslösen.',
        ['Föhn', 'Alpen']),
    mc('q-wetter-105', 'wetter', 2,
        'Bei welchem Windstärke-Wert beginnt ein Orkan nach der Beaufort-Skala?',
        ['8', '10', '12', '14'], 2,
        'Beaufort-Skala 12: Orkan (> 118 km/h). Skala reicht regulär bis 12, wurde aber informell erweitert für Hurrikan-Winde.',
        ['Beaufort', 'Orkan']),
    mc('q-wetter-106', 'wetter', 3,
        'Welche Wolkenart erscheint als hohe, dünne Federn und deutet auf herannahendes schlechtes Wetter?',
        ['Kumulus', 'Zirrus', 'Stratus', 'Nimbus'], 1,
        'Zirrus (Federwolke): Eiskristalle in 6–13 km Höhe. Oft Anzeichen einer sich nähernden Warmfront.',
        ['Zirrus', 'Wolken']),
    mc('q-wetter-107', 'wetter', 2,
        'Wie heißt das Wetterphänomen, das Meeresströmungen im Pazifik alle paar Jahre umkehrt und global Wetter beeinflusst?',
        ['El Niño', 'Golfstrom', 'Monsun', 'Passat'], 0,
        'El Niño („Christkind" auf Spanisch, weil es meist um Weihnachten beginnt). Alle 2–7 Jahre. Bringt Dürren in Australien, Regen in Peru.',
        ['El Niño', 'Klima']),
    mc('q-wetter-108', 'wetter', 3,
        'Welches Land wird von der Sahara-Wüste größtenteils bedeckt?',
        ['Ägypten', 'Algerien', 'Marokko', 'Alle drei (und weitere)'], 3,
        'Sahara umfasst 11 Länder: Algerien, Tschad, Ägypten, Libyen, Mali, Mauretanien, Marokko, Niger, Westsahara, Sudan, Tunesien.',
        ['Sahara', 'Wüste']),
    mc('q-wetter-109', 'wetter', 2,
        'Was ist ein Tornado?',
        [
            'Wirbelsturm mit engem, rotierendem Luftschlauch am Boden',
            'Große Wolkenformation',
            'Wüstensturm',
            'Wasserfontäne',
        ], 0,
        'Tornado: rotierende Luftsäule zwischen Gewitterwolke und Erde. Windgeschwindigkeiten bis 500 km/h. Fujita-Skala EF0–EF5.',
        ['Tornado']),
    mc('q-wetter-110', 'wetter', 3,
        'Was ist das Phänomen „Nordlicht" (Aurora borealis)?',
        [
            'Reflexion von Schnee',
            'Elektrisch geladene Sonnenteilchen treffen auf Erdatmosphäre',
            'Vulkanische Ausbrüche',
            'Ionisiertes Meerwasser',
        ], 1,
        'Sonnenwind trifft auf Erdmagnetfeld, Teilchen regen Sauerstoff/Stickstoff-Moleküle an — dann leuchten sie. Grün: Sauerstoff in 100–300 km. Rot/Violett: seltener.',
        ['Aurora', 'Nordlicht']),
    mc('q-wetter-111', 'wetter', 3,
        'Wo auf der Erde wurden die höchsten Temperaturen (56,7 °C) gemessen?',
        ['Sahara', 'Death Valley (USA)', 'Wüste Gobi', 'Kalahari'], 1,
        'Death Valley, Kalifornien, 10. Juli 1913. Ein umstrittener Rekord. Andere sagen Kuwait 2016 (~54 °C) sei verlässlicher.',
        ['Death Valley', 'Rekord']),
    mc('q-wetter-112', 'wetter', 2,
        'Welche Zeit-Zone hat die Antarktis?',
        ['Nur eine', 'Mehrere je nach Station', 'UTC', 'Es gibt keine offizielle Zeitzone'], 1,
        'Am Pol laufen alle Zeitzonen zusammen — keine offizielle. Stationen nutzen die Zeitzone ihrer Herkunftsstaaten oder pragmatische Regelungen.',
        ['Antarktis', 'Zeitzone']),
    mc('q-wetter-113', 'wetter', 3,
        'Was ist der „Jahrhundertsturm" Kyrill von 2007?',
        ['Winterorkan über Europa', 'Sommer-Hitzewelle', 'Tsunami', 'Sandsturm'], 0,
        'Orkan Kyrill (18./19. Januar 2007): Böen bis 200 km/h. 47 Tote in Europa. Deutsche Bahn stellte für 24 h den Fernverkehr ein.',
        ['Kyrill', 'Sturm']),
    mc('q-wetter-114', 'wetter', 3,
        'Warum sieht der Himmel bei Tag blau aus?',
        [
            'Meer reflektiert blaues Licht',
            'Rayleigh-Streuung: kürzere Wellenlängen streuen stärker',
            'Ozonschicht ist blau',
            'Erdreflexion',
        ], 1,
        'Blaues Licht (kurze Wellenlänge) streut ~10× stärker als rotes. Bei Sonnenaufgang/-untergang legt Licht längeren Weg zurück, blaues Licht wird weggestreut, rotes bleibt.',
        ['Rayleigh', 'Himmel']),
    mc('q-wetter-115', 'wetter', 2,
        'Wie viel Prozent des Süßwassers der Erde sind in Gletschern und Polkappen gebunden?',
        ['20 %', '50 %', '~70 %', '95 %'], 2,
        'Rund 68 % Süßwasser in Gletschern/Polkappen, 30 % Grundwasser, nur 0,3 % in Oberflächen-Süßwasser (Seen, Flüsse).',
        ['Süßwasser', 'Gletscher']),
    mc('q-wetter-116', 'wetter', 2,
        'Welches Wolkenphänomen kennzeichnet Gewitterwolken?',
        ['Nimbostratus', 'Zirrostratus', 'Kumulonimbus (Amboss-Wolke)', 'Altocumulus'], 2,
        'Kumulonimbus: die klassischen Gewitterwolken, 10–15 km hoch, oft mit Ambossform am Gipfel. Können Hagel, Blitz, Starkregen enthalten.',
        ['Gewitter', 'Kumulonimbus']),
    mc('q-wetter-117', 'wetter', 3,
        'Was ist der „Monsun" in Südasien?',
        [
            'Wind mit saisonal wechselnder Richtung, bringt trockene und regenreiche Zeiten',
            'Trockener Wüstenwind',
            'Tsunami',
            'Ein tropischer Wirbelsturm',
        ], 0,
        'Sommer-Monsun in Indien (Juni–September): Regen bis 90 % des Jahresvolumens. Ohne Monsun keine Landwirtschaft. Wintermonsun: trocken aus Nordost.',
        ['Monsun', 'Indien']),
    mc('q-wetter-118', 'wetter', 4,
        'In welchem Jahr wurde die kälteste je gemessene Temperatur (−89,2 °C) erfasst?',
        ['1912 (Sibirien)', '1958 (Grönland)', '1983 (Antarktis)', '2004 (Alaska)'], 2,
        '21. Juli 1983 in Wostok-Station, Antarktis. Sowjetische Forschungsstation auf ~3 500 m Höhe.',
        ['Kälterekord', 'Antarktis']),
    mc('q-wetter-119', 'wetter', 3,
        'Was verursacht die Jahreszeiten (Frühling, Sommer, Herbst, Winter)?',
        [
            'Änderung der Sonnenentfernung',
            'Neigung der Erdachse (23,5°) zur Umlaufbahn',
            'Wechselnde Mondphasen',
            'Bewegung der Kontinente',
        ], 1,
        'Die 23,5° Neigung der Erdachse. In dem Halbjahr, in dem eine Hemisphäre zur Sonne geneigt ist, wird sie stärker beschienen → Sommer. Die andere gleichzeitig Winter.',
        ['Jahreszeiten', 'Erdachse']),
]

# HOBBYS (20)
NEW_QUESTIONS += [
    mc('q-hobbys-100', 'hobbys', 1,
        'Welches Brettspiel enthält 32 Figuren, ein 8×8-Brett und wurde in Indien erfunden?',
        ['Backgammon', 'Schach', 'Dame', 'Go'], 1,
        'Schach: ursprünglich Chaturanga (6. Jhd. Indien). Weltschachverband FIDE seit 1924. Aktueller Weltmeister: Ding Liren (Stand 2023).',
        ['Schach', 'Brettspiel']),
    mc('q-hobbys-101', 'hobbys', 1,
        'Wie viele Steine hat ein klassisches Domino-Spiel?',
        ['21', '24', '28', '36'], 2,
        'Standarddomino: 28 Steine (Doppel-Sechs). Erweiterte Varianten: Doppel-Neun (55), Doppel-Zwölf (91).',
        ['Domino']),
    mc('q-hobbys-102', 'hobbys', 2,
        'Wie viele Karten hat ein Standard-Pokerspiel-Deck (ohne Joker)?',
        ['48', '52', '54', '60'], 1,
        '52 Karten: 4 Farben × 13 Werte. Mit 2 Joker: 54.',
        ['Poker', 'Kartenspiel']),
    mc('q-hobbys-103', 'hobbys', 2,
        'Welches Spiel wird auf einem 19×19-Gitter mit schwarzen und weißen Steinen gespielt?',
        ['Schach', 'Go', 'Backgammon', 'Reversi'], 1,
        'Go (chinesisch: Weiqi): ~2 500 Jahre alt. 2016 gewann AlphaGo (DeepMind) gegen Weltmeister Lee Sedol — Meilenstein der KI.',
        ['Go', 'Brettspiel']),
    mc('q-hobbys-104', 'hobbys', 3,
        'Welches deutsche Brettspiel wurde 1995 „Spiel des Jahres" und ist ein Ressourcen-Management-Klassiker?',
        ['Die Siedler von Catan', 'Carcassonne', 'Zug um Zug', 'Agricola'], 0,
        'Catan (früher: „Die Siedler von Catan") von Klaus Teuber. Verkaufte sich weltweit über 40 Millionen Mal.',
        ['Catan', 'Teuber']),
    mc('q-hobbys-105', 'hobbys', 3,
        'Wie viele Teile hat das Standard-Puzzle-Rekord der Welt (Erwachsene)?',
        ['5 000', '10 000', '40 320', '54 000'], 3,
        'Das derzeit größte kommerziell erhältliche Puzzle „Wildlife" von Ravensburger hat 54 000 Teile — 8,64 × 2,04 Meter groß.',
        ['Puzzle', 'Ravensburger']),
    mc('q-hobbys-106', 'hobbys', 2,
        'Welches Kartenspiel „Uno" wurde 1971 in den USA erfunden?',
        ['Merle Robbins', 'Reiner Knizia', 'Klaus Teuber', 'Alex Randolph'], 0,
        'Merle Robbins, Friseur aus Ohio. Erfand das Spiel für seine Familie. Verkaufte 1992 die Rechte an Mattel für 50 Millionen Dollar.',
        ['Uno', 'Robbins']),
    mc('q-hobbys-107', 'hobbys', 3,
        'Welche Kunst des Papierfaltens stammt aus Japan?',
        ['Ikebana', 'Origami', 'Kirigami', 'Kintsugi'], 1,
        'Origami: ori (falten) + kami (Papier). Bekanntestes Motiv: der Papierkranich. Ikebana ist Blumenkunst.',
        ['Origami', 'Japan']),
    mc('q-hobbys-108', 'hobbys', 2,
        'Welcher legendäre Modell-Autobau-Hersteller stellt seit 1945 detailreiche Modell-Kits her (Formel 1, Panzer etc.)?',
        ['Faller', 'Revell', 'Tamiya', 'Roco'], 2,
        'Tamiya (Japan). Bekannt für Präzision und breite Palette: von 1:24 Autos über Militärmodelle bis Ferngesteuertes.',
        ['Tamiya', 'Modellbau']),
    mc('q-hobbys-109', 'hobbys', 3,
        'Was ist ein „Escape Room"?',
        [
            'Ein Meditations-Rückzug',
            'Ein Rätselspiel, bei dem eine Gruppe innerhalb 60 Minuten einen Raum verlassen muss',
            'Ein Fitness-Studio-Konzept',
            'Ein Kinderspielplatz',
        ], 1,
        'Escape Rooms: ~2007 in Japan entstanden. Weltweit über 50 000 Anlagen. Für Gruppen von 2–8 Personen.',
        ['Escape Room', 'Rätsel']),
    mc('q-hobbys-110', 'hobbys', 2,
        'Welche Kartenspiele stammen aus dem 15. Jhd. und werden zur Zukunftsdeutung genutzt?',
        ['Tarock', 'Tarot', 'Skat', 'Rommé'], 1,
        'Tarot: 78 Karten (22 Große Arkana, 56 Kleine Arkana). Ursprünglich italienisches Kartenspiel, später (18. Jhd.) für Kartomantie umgedeutet.',
        ['Tarot', 'Kartomantie']),
    mc('q-hobbys-111', 'hobbys', 3,
        'Welche Sammlung ist die begehrteste unter Sneaker-Sammlern (Größe/Editionen)?',
        ['Nike Air Force 1', 'Air Jordan Serie', 'Adidas Yeezy', 'Adidas Stan Smith'], 1,
        'Air Jordan 1 aus 1985: Michael Jordans erstes Signature-Modell bei Nike. Original-Paare erzielen sechsstellige Beträge.',
        ['Sneaker', 'Air Jordan']),
    mc('q-hobbys-112', 'hobbys', 3,
        'Welche Sammlung/Sport hat weltweit die meisten Fans (nach Fußball)?',
        ['Cricket', 'Basketball', 'Volleyball', 'Tennis'], 0,
        'Cricket: geschätzt ~2,5 Milliarden Fans. Vor allem in Indien, Pakistan, Bangladesch, England, Australien, Karibik.',
        ['Cricket', 'Fans']),
    mc('q-hobbys-113', 'hobbys', 4,
        'Welche Sammel-Trading-Card-Marke aus Japan wurde 1996 gestartet und ist bis heute ein Milliardengeschäft?',
        ['Yu-Gi-Oh!', 'Pokémon TCG', 'Magic: The Gathering', 'Digimon Card'], 1,
        'Pokémon Trading Card Game seit 1996. Seltene Karten (z. B. „Illustrator") erzielen sechsstellige Preise. MtG ist älter (1993, USA).',
        ['Pokémon', 'TCG']),
    mc('q-hobbys-114', 'hobbys', 2,
        'Welches Musikinstrument gehört traditionell zum Karnevalsspiel „Kubb" (Wikinger-Schach)?',
        ['Keins — das ist ein Wurfspiel', 'Trommel', 'Panflöte', 'Xylophon'], 0,
        'Kubb ist ein Rasen-Wurfspiel mit Holzklötzen. Ursprung: schwedische Insel Gotland. Weltmeisterschaft jährlich seit 1995 auf Gotland.',
        ['Kubb', 'Rasenspiel']),
    mc('q-hobbys-115', 'hobbys', 3,
        'Welche Sportart wurde 2020 offiziell als olympische Disziplin aufgenommen (Sommerspiele Tokio 2021)?',
        ['Golf', 'Rugby', 'Skateboard', 'Cricket'], 2,
        'Skateboard, Sportklettern und Surfen. Karate war einmalig dabei, Cricket kommt 2028 wieder.',
        ['Skateboard', 'Olympia']),
    mc('q-hobbys-116', 'hobbys', 2,
        'Welche Sammlerkategorie befasst sich mit Philatelie?',
        ['Münzen', 'Briefmarken', 'Bierdeckel', 'Weine'], 1,
        'Philatelie = Briefmarkenkunde. Numismatik = Münzen. Weinliebe = Önophilie. Bierdeckel = Tegestologie (weniger geläufig).',
        ['Philatelie', 'Briefmarken']),
    mc('q-hobbys-117', 'hobbys', 3,
        'Welches Handarbeits-Hobby erlebt seit den 2010ern ein Comeback als „Slow Craft"?',
        ['Häkeln', 'Stricken', 'Nähen', 'Alle drei'], 3,
        'Instagram und YouTube haben DIY-Handarbeit wiederbelebt. Marken wie We Are Knitters (Spanien) treffen den Zeitgeist.',
        ['Handarbeit', 'DIY']),
    mc('q-hobbys-118', 'hobbys', 2,
        'Wie heißt der Sport, bei dem man an einem einzelnen Seil klettert?',
        ['Klettern', 'Bouldering', 'Slackline', 'Ropes-Course'], 2,
        'Slackline: Balancieren auf einem gespannten breiten Band zwischen zwei Fixpunkten. Highline: Slackline in extremer Höhe.',
        ['Slackline']),
    mc('q-hobbys-119', 'hobbys', 3,
        'Welches asiatische Brettspiel für zwei ist strategisch dem Schach ähnlich, wird aber mit 20 Steinen pro Spieler auf 9×9-Feldern gespielt?',
        ['Xiangqi (chin. Schach)', 'Shogi (jap. Schach)', 'Janggi (kor. Schach)', 'Makruk (thai Schach)'], 1,
        'Shogi hat 20 Steine mit 8 Typen, gefangene Figuren dürfen wieder ins Spiel („Drop-Move"). Etwa 20 Millionen Spieler in Japan.',
        ['Shogi', 'Japan']),
]

# HANDWERK & DIY (20)
NEW_QUESTIONS += [
    mc('q-handwerk-100', 'handwerk', 1,
        'Welches Werkzeug wird zum Sägen verwendet?',
        ['Hammer', 'Säge', 'Feile', 'Zange'], 1,
        'Handsäge, Kettensäge, Kreissäge, Stichsäge — je nach Anwendung. Wichtig: passende Zähne für Holz/Metall/Kunststoff.',
        ['Säge']),
    mc('q-handwerk-101', 'handwerk', 1,
        'Wozu dient ein Meißel im Handwerk?',
        ['Zum Schleifen', 'Zum Meißeln (Trennen von Material)', 'Zum Kleben', 'Zum Löten'], 1,
        'Meißel: Stahl-Werkzeug zum abbrechen/lösen von Stein-, Metall- oder Holzmaterial. Klassisch mit Hammer geführt.',
        ['Meißel']),
    mc('q-handwerk-102', 'handwerk', 2,
        'Welches Metall wird zum Löten am häufigsten verwendet?',
        ['Reines Eisen', 'Zinn (oft mit Blei-Legierung)', 'Kupfer', 'Aluminium'], 1,
        'Weichlot (Sn-Pb): Schmelzpunkt ~180 °C. Wegen Toxizität in EU seit RoHS 2006 in Elektronik verboten — heute meist bleifreies Zinn-Silber-Kupfer-Lot.',
        ['Löten', 'Zinn']),
    mc('q-handwerk-103', 'handwerk', 3,
        'Welches Holz gilt als eines der härtesten und wird für Fußböden hoher Belastung genutzt?',
        ['Fichte', 'Kiefer', 'Eiche', 'Birke'], 2,
        'Eiche: Härte ~34 auf Janka-Skala. Massiv oder als Fertigparkett. Alternativ: Nussbaum, Buche.',
        ['Eiche', 'Holzbau']),
    mc('q-handwerk-104', 'handwerk', 2,
        'Welche Schraube passt zu einem Kreuzschlitzschraubenzieher?',
        ['Torx', 'Kreuzschlitz (Phillips oder Pozidriv)', 'Innensechskant', 'Schlitzschraube'], 1,
        'Kreuzschlitz (Phillips PH oder Pozidriv PZ) — die Klassiker in Möbelbau und Elektronik. Torx (Sternform) hat sich in Auto und Industrie durchgesetzt.',
        ['Schraube', 'Kreuzschlitz']),
    mc('q-handwerk-105', 'handwerk', 3,
        'Welche Kettensäge-Marke gilt als „Rolls-Royce" der Motorsägen und stammt aus Stuttgart?',
        ['Husqvarna', 'STIHL', 'Makita', 'Bosch'], 1,
        'STIHL (Waiblingen bei Stuttgart), seit 1926. Marktführer weltweit für Profi-Motorsägen. Erkennungszeichen: Orange.',
        ['STIHL', 'Kettensäge']),
    mc('q-handwerk-106', 'handwerk', 2,
        'Was ist ein „Fugendichtstoff" (Kartuschendichtmasse)?',
        [
            'Klebstoff',
            'Elastische Masse zum Abdichten von Fugen',
            'Grundierung',
            'Farbe',
        ], 1,
        'Silikon-, Acryl- oder Polyurethan-Basis. Silikon: sanitär (Bad/Küche), dauerelastisch, aber nicht überstreichbar. Acryl: überstreichbar, weniger flexibel.',
        ['Silikon', 'Fugen']),
    mc('q-handwerk-107', 'handwerk', 3,
        'Was bedeutet die Werkzeug-Abkürzung „PSA" im Arbeitsschutz?',
        [
            'Persönliche Schutz-Ausrüstung',
            'Professional Standard Assembly',
            'Power Saw Automation',
            'Public Service Announcement',
        ], 0,
        'PSA: Helm, Schutzbrille, Handschuhe, Sicherheitsschuhe, Gehörschutz. Vorschriftsmäßig auf Baustellen und im Handwerk.',
        ['PSA', 'Arbeitsschutz']),
    mc('q-handwerk-108', 'handwerk', 2,
        'Welche Wandfarbe ist besonders atmungsaktiv und daher für Innenräume beliebt?',
        ['Lack', 'Kalk-/Kalkkasein', 'Silikatfarbe', 'Alle drei atmungsaktiv'], 3,
        'Klassische Kalk-, Silikat- und Kaseinfarben. Dispersionsfarbe (die häufigste heute) ist weniger atmungsaktiv, dafür robuster.',
        ['Wandfarbe', 'Renovieren']),
    mc('q-handwerk-109', 'handwerk', 3,
        'Was ist eine „Nut-und-Feder"-Verbindung?',
        [
            'Elektroverkabelung',
            'Holzverbindung mit erhöhter Zapfen (Feder) und Vertiefung (Nut)',
            'Klebeverbindung',
            'Metallverbindung',
        ], 1,
        'Klassisch bei Dielen, Paneelen. Zwei Holzteile ineinander verbunden ohne Schrauben. Fest und optisch sauber.',
        ['Nut-Feder', 'Holzverbindung']),
    mc('q-handwerk-110', 'handwerk', 3,
        'Welche Marke ist Deutschlands bekanntester Baumarkt-Betreiber?',
        ['OBI', 'HORNBACH', 'Bauhaus', 'Alle drei zu den Top-4 in Deutschland'], 3,
        'Alle sind Top-Baumärkte. OBI und Hornbach führen mit je ~500 bzw. 170 Filialen. Bauhaus international sehr präsent, sitzt in Mannheim.',
        ['Baumarkt']),
    mc('q-handwerk-111', 'handwerk', 3,
        'Welche traditionelle japanische Holzverbindungs-Technik kommt gänzlich ohne Nägel und Schrauben aus?',
        ['Origami', 'Kumiki', 'Bento', 'Suminagashi'], 1,
        'Kumiki („Zusammenfügen"): kunstvolle Holzsteck-Verbindungen. Auch in traditionellen japanischen Tempeln verwendet.',
        ['Kumiki', 'Japan']),
    mc('q-handwerk-112', 'handwerk', 3,
        'Welcher Schleifgrad (Körnung) wird für den ersten groben Schliff von rohem Holz empfohlen?',
        ['P40–P80', 'P120–P180', 'P240–P360', 'P400+'], 0,
        'Grobe Körnung P40–P80 für starken Materialabtrag. Feinabschleifen mit P180–P240. Vor der Lackierung P320+.',
        ['Schleifen', 'Körnung']),
    mc('q-handwerk-113', 'handwerk', 2,
        'Welche Klebstoffart ist wasser- und temperaturbeständig, aushärtet chemisch und wird für Sportgeräte-Reparaturen empfohlen?',
        ['Weißleim', 'Sekundenkleber', 'Zwei-Komponenten-Epoxidharz', 'Heißkleber'], 2,
        '2K-Epoxid: Harz + Härter. Zug- und Scherfest, wasserfest. Verarbeitungszeit meist 5–60 Minuten.',
        ['Epoxid', 'Kleber']),
    mc('q-handwerk-114', 'handwerk', 2,
        'Was ist die Aufgabe der Wasserwaage?',
        [
            'Messen von Ebenheit und Vertikalität',
            'Wasserstand messen',
            'Feuchtigkeit prüfen',
            'Rohre entwässern',
        ], 0,
        'Luftblase in flüssigkeitsgefüllter Kammer zeigt Neigung. Sowohl horizontal (Waage) als auch vertikal (Lot). Digitale Varianten immer beliebter.',
        ['Wasserwaage']),
    mc('q-handwerk-115', 'handwerk', 3,
        'Welches Metall wird in Sanitärleitungen häufig durch Löten oder Pressen verbunden?',
        ['Aluminium', 'Kupfer', 'Blei', 'Zinn'], 1,
        'Kupferrohre: Standard für Trinkwasserleitungen. Korrosionsbeständig, formstabil, wärmeleitfähig.',
        ['Kupfer', 'Sanitär']),
    mc('q-handwerk-116', 'handwerk', 3,
        'Welche Bohrertype ist für Beton geeignet und hat eine Hartmetall-Spitze?',
        ['Holzbohrer', 'Metallbohrer (HSS)', 'Steinbohrer', 'Diamantbohrer'], 2,
        'Steinbohrer / Betonbohrer mit Hartmetall-Schneide. Beim Bohren in Beton immer Schlagbohren aktivieren.',
        ['Bohrer', 'Beton']),
    mc('q-handwerk-117', 'handwerk', 2,
        'Was macht eine Stichsäge besonders geeignet für Kurven-Schnitte in Holz?',
        [
            'Rotierende Klinge',
            'Auf-Ab-Bewegung eines schmalen Sägeblatts',
            'Wasserstrahl',
            'Laserschneiden',
        ], 1,
        'Schmales, austauschbares Sägeblatt bewegt sich hoch/runter. Kann engen Kurven folgen. Ideal für Formzuschnitte.',
        ['Stichsäge']),
    mc('q-handwerk-118', 'handwerk', 4,
        'Wer gilt als Erfinder des Akkuschraubers, der ab 1961 den Elektroschrauber für Heimwerker eroberte?',
        ['Robert Bosch', 'Bosch (Firma)', 'Black & Decker', 'Makita'], 2,
        'Black & Decker (USA) brachten den ersten weit verbreiteten Akkuschrauber („Cordless Drill", 1961). Vorher: nur mit Netzkabel.',
        ['Black & Decker', 'Akkuschrauber']),
    mc('q-handwerk-119', 'handwerk', 3,
        'Was ist eine „Rigips"-Platte im deutschen Bauhandwerk?',
        [
            'Isolierplatte',
            'Gipskartonplatte für Trockenbau',
            'Fußbodenbelag',
            'Fensterrahmen',
        ], 1,
        'Rigips ist die Markenbezeichnung von Saint-Gobain, ähnlich wie Tempo für Papiertaschentücher. Für Innenwände, abgehängte Decken.',
        ['Rigips', 'Trockenbau']),
]


def main() -> int:
    with QUESTIONS_PATH.open('r', encoding='utf-8') as f:
        existing = json.load(f)
    existing_ids = {q['id'] for q in existing}
    to_add = [q for q in NEW_QUESTIONS if q['id'] not in existing_ids]
    if not to_add:
        print('Keine neuen Fragen.')
        return 0
    for q in to_add:
        assert len(q['options']) == 4
        assert 0 <= q['correctIndex'] < 4
    merged = existing + to_add
    with QUESTIONS_PATH.open('w', encoding='utf-8') as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
        f.write('\n')
    from collections import Counter
    print(f'✓ {len(to_add)} neue Fragen ergänzt (jetzt {len(merged)} insgesamt).')
    for t, c in sorted(Counter(q['topic'] for q in to_add).items()):
        print(f'  + {t:<14} {c}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
