#!/usr/bin/env python3
"""Batch 3 — Teil 1: mode, wohnen, beauty, natur (4 × 20 = 80)."""
from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
QUESTIONS_PATH = ROOT / 'packages' / 'shared' / 'src' / 'data' / 'questions.json'
NOW = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
MC_MODES = ['category-duel', 'flash', 'player-spotlight', 'sprinter',
            'points-ladder', 'category-board', 'duel-1v1', 'elimination', 'experts']


def mc(qid, topic, difficulty, question, options, correct, gm, tags, category='allgemeinbildung'):
    return {'id': qid, 'type': 'multiple-choice', 'status': 'approved',
        'category': category, 'topic': topic, 'difficulty': difficulty,
        'question': question, 'options': options, 'correctIndex': correct,
        'gmNote': gm, 'tags': tags, 'compatibleModes': MC_MODES,
        'timeScope': 'timeless', 'aiGenerated': True,
        'createdAt': NOW, 'updatedAt': NOW}


NEW_QUESTIONS = []

# ================================================================
# MODE & STYLE (20)
# ================================================================
NEW_QUESTIONS += [
    mc('q-mode-100', 'mode', 1,
        'Welches Modehaus ist berühmt für die „Little Black Dress" und wurde von Gabrielle „Coco" Bonheur gegründet?',
        ['Dior', 'Chanel', 'Yves Saint Laurent', 'Prada'], 1,
        'Coco Chanel, Gründung 1910 in Paris. Ihr No 5-Parfum (1921) ist heute noch Ikone.',
        ['Chanel', 'Coco Chanel']),
    mc('q-mode-101', 'mode', 2,
        'Welcher deutsche Modedesigner leitete Chanel und Fendi bis zu seinem Tod 2019?',
        ['Wolfgang Joop', 'Karl Lagerfeld', 'Hugo Boss', 'Jil Sander'], 1,
        'Karl Lagerfeld, geboren 1933 in Hamburg. Ab 1983 Kreativdirektor bei Chanel. Erkennungszeichen: weißer Pferdeschwanz, schwarze Sonnenbrille.',
        ['Lagerfeld', 'Chanel']),
    mc('q-mode-102', 'mode', 2,
        'Welcher Modestil aus den 1920ern brach mit den langen Kleidern und feierte die weibliche Emanzipation?',
        ['Rokoko', 'Flapper', 'New Look', 'Grunge'], 1,
        'Flapper-Stil: kurze Kleider, Bubikopf, Cocktails, Charleston. Ausdruck der „Goldenen Zwanziger". Popularisierung durch Louise Brooks.',
        ['Flapper', '1920er']),
    mc('q-mode-103', 'mode', 3,
        'Welches Modehaus prägte 1947 den „New Look" mit Wespentaille und weit ausgestellten Röcken?',
        ['Balenciaga', 'Christian Dior', 'Chanel', 'Givenchy'], 1,
        'Diors erste Kollektion nach dem Krieg — extrem stoffreich, feminine Silhouette. Bruch mit der Kriegs-Sparsamkeit.',
        ['Dior', 'New Look']),
    mc('q-mode-104', 'mode', 2,
        'Aus welchem Material bestehen klassische Levi\'s-Jeans?',
        ['Baumwoll-Denim', 'Leinen', 'Polyester', 'Wolle'], 0,
        'Denim = Baumwoll-Köpergewebe. Levi Strauss patentierte 1873 mit Jacob Davis die Nietung an Belastungspunkten.',
        ['Jeans', 'Denim']),
    mc('q-mode-105', 'mode', 2,
        'In welcher Stadt findet zweimal jährlich die weltweit bedeutendste Modewoche statt?',
        ['London', 'Mailand', 'Paris', 'New York'], 2,
        'Paris Fashion Week (seit 1973). Die „Big Four": Paris, New York, Mailand, London. Paris hat die längste Tradition.',
        ['Paris', 'Fashion Week']),
    mc('q-mode-106', 'mode', 3,
        'Welche italienische Modemarke ist bekannt für Business-Anzüge und wurde 1975 von einem Mailänder gegründet?',
        ['Prada', 'Versace', 'Armani', 'Gucci'], 2,
        'Giorgio Armani, aus einem einfachen Warenhaus-Schaufenster-Dekorateur zum Modezaren. Bekannt für weiche, unstrukturierte Anzüge.',
        ['Armani', 'Mailand']),
    mc('q-mode-107', 'mode', 2,
        'Welche deutsche Modemarke sitzt in Metzingen (Baden-Württemberg) und ist bekannt für Herrenanzüge?',
        ['Wolfgang Joop', 'Hugo Boss', 'Escada', 'Marc O\'Polo'], 1,
        'Hugo Boss, 1924 gegründet als kleiner Bekleidungsbetrieb. Heute Weltkonzern mit ~1 000 Boutiquen.',
        ['Hugo Boss', 'Metzingen']),
    mc('q-mode-108', 'mode', 3,
        'Welches Modehaus ist berühmt für den „Bag: 2.55" — eine 1955 lancierte Handtasche mit Kettenriemen?',
        ['Louis Vuitton', 'Chanel', 'Hermès', 'Gucci'], 1,
        'Coco Chanel entwarf die 2.55 (nach dem Datum benannt: Februar 1955). Klassiker mit Steppmuster und goldener Kette.',
        ['Chanel', 'Handtasche']),
    mc('q-mode-109', 'mode', 3,
        'Welches Textil-Material stammt vom Seidenspinner-Raupen und war jahrhundertelang ein chinesisches Monopol?',
        ['Wolle', 'Baumwolle', 'Seide', 'Leinen'], 2,
        'Seide, im alten China ~3 000 v. Chr. entdeckt. Nach der berühmten Seidenstraße bekannt. Erst im 6. Jhd. Import der Raupen nach Byzanz.',
        ['Seide', 'China']),
    mc('q-mode-110', 'mode', 2,
        'Welcher britische Designer prägte in den 1970ern den Punk-Look mit Vivienne Westwood?',
        ['Alexander McQueen', 'John Galliano', 'Malcolm McLaren', 'Paul Smith'], 2,
        'Malcolm McLaren, Manager der Sex Pistols und Lebenspartner Westwoods. Zusammen betrieben sie den Laden „SEX" auf der Kings Road.',
        ['Punk', 'Westwood', 'McLaren']),
    mc('q-mode-111', 'mode', 3,
        'Welche High-End-Marke ist bekannt für die Birkin Bag, benannt nach einer britischen Schauspielerin?',
        ['Louis Vuitton', 'Chanel', 'Hermès', 'Prada'], 2,
        'Hermès Birkin, seit 1984. Benannt nach Jane Birkin. Preise ab ~10 000 Euro, exklusive Ledervarianten weit sechsstellig.',
        ['Birkin', 'Hermès']),
    mc('q-mode-112', 'mode', 2,
        'Welche Farbe war lange nur dem König oder Papst vorbehalten wegen der teuren Herstellung aus Purpurschnecken?',
        ['Blau', 'Rot', 'Purpur', 'Gold'], 2,
        'Purpur aus der Purpurschnecke: bis zu 10 000 Schnecken für 1 Gramm Farbstoff. Deshalb historisch nur für Adel und Klerus.',
        ['Purpur', 'Antike']),
    mc('q-mode-113', 'mode', 3,
        'Welche schwedische Fast-Fashion-Marke wurde 1947 gegründet und ist heute weltweit die drittgrößte?',
        ['Zara', 'H&M', 'C&A', 'Primark'], 1,
        'H&M (Hennes & Mauritz). Zara (Inditex) ist mittlerweile größer. Fast Fashion in Kritik wegen Umwelt und Arbeitsbedingungen.',
        ['H&M', 'Fast Fashion']),
    mc('q-mode-114', 'mode', 4,
        'Wie heißt das begehrteste Modeevent, das jährlich Anfang Mai in New York stattfindet und Prominente auf einer Treppe zeigt?',
        ['Fashion Week', 'Met Gala', 'CFDA Awards', 'Fashion Awards'], 1,
        'Met Gala als Fundraiser für das Costume Institute des Metropolitan Museum. Anna Wintour (Vogue) organisiert seit 1995. Motto wechselt jährlich.',
        ['Met Gala', 'Wintour']),
    mc('q-mode-115', 'mode', 3,
        'Welche 1953 gegründete französische Marke ist berühmt für ihre Polohemden mit Krokodil-Logo?',
        ['Lacoste', 'Ralph Lauren', 'Fred Perry', 'Tommy Hilfiger'], 0,
        'Lacoste, von Tennisspieler René Lacoste (Spitzname „Le Crocodile") 1933 gegründet. Erste Marke mit sichtbarem Logo auf Kleidung.',
        ['Lacoste', 'Polo']),
    mc('q-mode-116', 'mode', 2,
        'Welche schuhe-Marke betreibt seit 1972 einen Sneaker-Kult mit dem Modell „Air Force 1"?',
        ['Adidas', 'Nike', 'Puma', 'New Balance'], 1,
        'Nike Air Force 1 (1982) — das erste Basketball-Modell mit Air-Dämpfung. Nike wurde 1971 als Blue Ribbon Sports umbenannt.',
        ['Nike', 'Sneaker']),
    mc('q-mode-117', 'mode', 3,
        'Welche italienische Marke ist bekannt für Business-Anzüge und Krawatten und gehört zum Kering-Konzern?',
        ['Prada', 'Gucci', 'Bottega Veneta', 'Alle drei zu Kering'], 3,
        'Kering (früher PPR) besitzt Gucci, Bottega Veneta, Balenciaga, Saint Laurent u. a. Prada ist unabhängig.',
        ['Kering', 'Luxusmarken']),
    mc('q-mode-118', 'mode', 3,
        'Welche Erfindung des Franzosen René Lacoste 1933 revolutionierte den Tennis-Look?',
        ['Weiße Hosen', 'Polohemd', 'Sneaker', 'Stirnband'], 1,
        'Vorher trugen Tennisspieler lange Hemden mit Ärmeln. Lacoste erfand das kurzärmelige Polo mit Kragen — bequemer, luftiger.',
        ['Polo', 'Lacoste']),
    mc('q-mode-119', 'mode', 4,
        'Welche belgische Designer-Bewegung der 1980er prägten Modernismus mit Studio-Konzepten und Antwerpen-Zentrum?',
        ['Antwerp Six', 'Britisches Punk', 'Grunge', 'Streetwear'], 0,
        'Antwerp Six: Ann Demeulemeester, Dries Van Noten, Walter Van Beirendonck und weitere. Absolventen der Königlichen Akademie 1980/81.',
        ['Antwerp Six', 'Belgien']),
]

# ================================================================
# WOHNEN & EINRICHTUNG (20)
# ================================================================
NEW_QUESTIONS += [
    mc('q-wohnen-100', 'wohnen', 1,
        'Welches schwedische Möbelhaus wurde 1943 von einem 17-Jährigen gegründet?',
        ['Bolia', 'IKEA', 'HAY', 'Kinnarps'], 1,
        'Ingvar Kamprad (Initialen I. K. + Elmtaryd + Agunnaryd). Weltweit größter Möbelhändler mit über 450 Filialen.',
        ['IKEA', 'Kamprad']),
    mc('q-wohnen-101', 'wohnen', 2,
        'Welche Designbewegung aus dem Deutschland der 1920er verbindet Handwerk mit Kunst und industrieller Fertigung?',
        ['Jugendstil', 'Bauhaus', 'Art Deco', 'De Stijl'], 1,
        'Bauhaus, 1919 in Weimar von Walter Gropius gegründet, ab 1925 in Dessau. Prägte modernes Design nachhaltig — von Möbeln über Grafik bis Architektur.',
        ['Bauhaus']),
    mc('q-wohnen-102', 'wohnen', 3,
        'Welcher Möbelklassiker von Marcel Breuer ist ein Stahlrohr-Sessel mit Ledergurten?',
        ['Barcelona-Chair', 'Wassily-Chair', 'Eames Lounge', 'Panton Chair'], 1,
        'Wassily-Chair (1925), inspiriert von Fahrradlenkern. Nach dem Bauhaus-Lehrer Wassily Kandinsky.',
        ['Breuer', 'Wassily-Chair']),
    mc('q-wohnen-103', 'wohnen', 3,
        'Welcher Sessel aus 1956 wurde von einem amerikanischen Designerpaar entworfen und ist ein Klassiker der Moderne?',
        ['Eames Lounge Chair', 'Barcelona-Chair', 'Egg Chair', 'Ball Chair'], 0,
        'Charles und Ray Eames, produziert von Herman Miller. Mit gebogenem Sperrholz und schwarzem Leder.',
        ['Eames', 'Lounge Chair']),
    mc('q-wohnen-104', 'wohnen', 2,
        'Welche Farbmischung wird oft als „Skandi-Style" für Innenräume verwendet?',
        [
            'Bunte Kontraste',
            'Warme Erdtöne',
            'Weiß, Grau, Naturholz',
            'Barock-Bunt',
        ], 2,
        'Skandi-Style: helle, klare Räume, natürliche Materialien, Funktionalität. Ausdruck des „hygge"-Prinzips (dänisch: gemütlich, geborgen).',
        ['Skandi-Style', 'Hygge']),
    mc('q-wohnen-105', 'wohnen', 3,
        'Welcher dänische Designer entwarf den ikonischen „Egg Chair" 1958 für ein Hotel in Kopenhagen?',
        ['Poul Henningsen', 'Arne Jacobsen', 'Hans Wegner', 'Verner Panton'], 1,
        'Arne Jacobsen für das SAS Royal Hotel Kopenhagen (heute Radisson Collection Royal Hotel). Erhältlich noch heute bei Fritz Hansen.',
        ['Jacobsen', 'Egg Chair']),
    mc('q-wohnen-106', 'wohnen', 4,
        'Welcher japanische Aufbewahrungsansatz ist berühmt für die Frage „Sparkt es Freude aus?"?',
        ['Feng Shui', 'KonMari', 'Wabi-Sabi', 'Zen'], 1,
        'Marie Kondos KonMari-Methode: nur behalten, was Freude bereitet. Bestseller „The Life-Changing Magic of Tidying Up" (2011).',
        ['KonMari', 'Marie Kondo']),
    mc('q-wohnen-107', 'wohnen', 2,
        'Welche Beleuchtungsart wird meist als warmes und stimmungsvolles Deckenlicht verwendet?',
        [
            'Neonröhre',
            'LED mit Warmweiß (2 700 K)',
            'Tageslichtlampe (6 500 K)',
            'UV-Lampe',
        ], 1,
        'Warmweiß (2 700 K, gelblich) für Wohnräume. Neutralweiß (4 000 K) und Tageslichtweiß (6 500 K) eher für Büros/Küche.',
        ['Beleuchtung', 'LED']),
    mc('q-wohnen-108', 'wohnen', 3,
        'Welcher Holztyp wird traditionell für hochwertige Designer-Möbel und Parkett verwendet?',
        ['Fichte', 'Kiefer', 'Eiche', 'Pappel'], 2,
        'Eiche: hart, langlebig, edle Optik. Auch beliebt: Nussbaum, Kirsche, Ahorn.',
        ['Eiche', 'Möbelholz']),
    mc('q-wohnen-109', 'wohnen', 3,
        'Welches Farbkonzept nutzt drei Farben in ausgewogenem Verhältnis 60/30/10?',
        [
            '60-30-10-Regel',
            'Farbkreis',
            'Komplementärkontrast',
            'Analogfarben',
        ], 0,
        'Interior-Design-Regel: 60 % dominante Farbe (Wände), 30 % sekundär (Möbel), 10 % Akzent (Deko).',
        ['Farbkonzept', 'Interior']),
    mc('q-wohnen-110', 'wohnen', 2,
        'Welche Möbelmarke steht für DIY-Selbstmontage-Konzept mit Inbusschlüssel?',
        ['IKEA', 'BoConcept', 'Kartell', 'Rolf Benz'], 0,
        'Der IKEA-Inbusschlüssel ist Kult. Kein anderes Möbelhaus hat das Flatpack so systematisch verbreitet.',
        ['IKEA', 'DIY']),
    mc('q-wohnen-111', 'wohnen', 4,
        'Welcher Architekt/Designer prägte die Wortkombination „Form follows function"?',
        [
            'Louis Sullivan',
            'Frank Lloyd Wright',
            'Le Corbusier',
            'Mies van der Rohe',
        ], 0,
        'Louis Sullivan, 1896 in einem Essay zum Wolkenkratzer-Design. Prägend für die gesamte Moderne.',
        ['Sullivan', 'Modernismus']),
    mc('q-wohnen-112', 'wohnen', 3,
        'Wie heißt das kleine mediterrane Wohnkonzept mit Innenhof, Zimmern im Halbkreis und meist einem Brunnen?',
        ['Riad', 'Villa', 'Palazzo', 'Cortijo'], 0,
        'Riad: traditionelles marokkanisches Stadthaus mit Innenhof (Riyad = „Garten"). Beispiel: Marrakesch, Fes.',
        ['Riad', 'Marokko']),
    mc('q-wohnen-113', 'wohnen', 3,
        'Welche Materialkombination zeichnet den Loft-Stil aus?',
        [
            'Rustikale Holzbalken',
            'Sichtbeton, Ziegel, Metall',
            'Barock und Samt',
            'Nur Kunststoff',
        ], 1,
        'Loft-Stil entstand in umgebauten Fabriketagen (NYC SoHo 1960er). Sichtbeton, freigelegte Ziegel, hohe Decken, Metallrohre.',
        ['Loft', 'Industrial']),
    mc('q-wohnen-114', 'wohnen', 2,
        'Welcher Möbelstil aus dem 18. Jhd. Frankreichs zeichnete sich durch geschwungene Formen und vergoldete Verzierungen aus?',
        ['Barock', 'Rokoko', 'Klassizismus', 'Empire'], 1,
        'Rokoko (~1730–1770): verspielt, asymmetrisch. Nach Ludwig XV. auch „Louis-XV-Stil". Barock: schwerer, prunkvoller.',
        ['Rokoko', 'Möbel']),
    mc('q-wohnen-115', 'wohnen', 3,
        'Welche chinesische Lehre der Raum-Anordnung soll Energieflüsse harmonisieren?',
        ['Feng Shui', 'Kabbalah', 'Vastu', 'Zen'], 0,
        'Feng Shui („Wind und Wasser"). Regeln zur Ausrichtung von Möbeln, Türen, Betten. Auch in Architekten-Kreisen in Asien noch relevant.',
        ['Feng Shui', 'China']),
    mc('q-wohnen-116', 'wohnen', 2,
        'Welche Wohn-Ambiance-Idee stammt aus dem Dänischen und bedeutet „gemütliches Wohlgefühl"?',
        ['Hygge', 'Lagom', 'Ikigai', 'Feng Shui'], 0,
        'Hygge (sprich „Hu-gah"): Kerzen, warme Decken, Freunde. Der schwedische Verwandte ist „Lagom" (das richtige Maß).',
        ['Hygge', 'Dänemark']),
    mc('q-wohnen-117', 'wohnen', 3,
        'Welche englische Designer-Ikone gestaltete den Union-Jack-Sessel und die Mini-Cooper-Interieurs?',
        ['Terence Conran', 'Vivienne Westwood', 'Paul Smith', 'Ian Callum'], 2,
        'Paul Smith. Seine bunten Streifen und der klassische Union-Jack-Look sind ikonisch.',
        ['Paul Smith', 'UK']),
    mc('q-wohnen-118', 'wohnen', 4,
        'Welcher Möbelhersteller entstand in Deutschland und produziert seit 1928 hochwertige Polstermöbel?',
        ['Rolf Benz', 'de Sede', 'Vitra', 'Cassina'], 0,
        'Vitra ist Schweizer, produziert v.a. Design-Klassiker der Eames-Familie. Rolf Benz gehört zu den bekanntesten deutschen Polsterspezialisten.',
        ['Rolf Benz', 'Polstermöbel']),
    mc('q-wohnen-119', 'wohnen', 3,
        'Welche Fußboden-Verlegetechnik nimmt kleine Elemente in V-Muster an?',
        ['Diele', 'Fischgrät', 'Schiffsboden', 'Würfel'], 1,
        'Fischgrät-Parkett: seit dem 17. Jhd. Klassiker in Herrenhäusern. Populär in Wiederauflage seit den 2010ern.',
        ['Fischgrät', 'Parkett']),
]

# ================================================================
# BEAUTY & KOSMETIK (20)
# ================================================================
NEW_QUESTIONS += [
    mc('q-beauty-100', 'beauty', 1,
        'Welche Marke ist mit der Fitness-Ikone Christy Turlington-Werbung berühmt für „Because you\'re worth it"?',
        ['Nivea', 'L\'Oréal', 'Estée Lauder', 'Chanel Beauty'], 1,
        'L\'Oréal-Slogan seit 1971. Die berühmte Kampagne mit Turlington und dem Slogan „Weil ich es mir wert bin" prägte Beauty-Werbung weltweit.',
        ['L\'Oréal', 'Slogan']),
    mc('q-beauty-101', 'beauty', 1,
        'Welche typische Beauty-Behandlung nutzt heißen Wachs zum Entfernen unerwünschter Haare?',
        ['Sugaring', 'Waxing', 'Peeling', 'Threading'], 1,
        'Waxing zieht die Haare komplett aus (Wurzel). Sugaring nutzt Zucker als Alternative. Threading nutzt Fäden.',
        ['Waxing', 'Haarentfernung']),
    mc('q-beauty-102', 'beauty', 2,
        'Welche Wirkstoff-Klasse in Cremes gilt als Anti-Aging-Standard?',
        ['Salicylsäure', 'Retinoide (Vitamin A)', 'Vitamin C', 'AHA/BHA'], 1,
        'Retinoide (v. a. Retinol, Retinal) fördern Zellerneuerung, mildern Falten. Verschreibungspflichtig als Tretinoin.',
        ['Retinol', 'Anti-Aging']),
    mc('q-beauty-103', 'beauty', 2,
        'Was steht der Buchstabe „SPF" auf Sonnencreme-Verpackungen für?',
        [
            'Sun Protection Factor',
            'Skin Preservation Formula',
            'Special Purpose Filter',
            'Solar Photon Filter',
        ], 0,
        'SPF (dt. Lichtschutzfaktor, LSF): Faktor gibt an, wie viel länger als ohne Creme in die Sonne. SPF 30 blockiert ~97 % der UVB-Strahlung.',
        ['SPF', 'Sonnencreme']),
    mc('q-beauty-104', 'beauty', 2,
        'Welche Marke launchte 1996 den ikonischen roten Lippenstift „MAC Ruby Woo"?',
        ['Chanel', 'MAC Cosmetics', 'Dior', 'YSL'], 1,
        'MAC Ruby Woo: matter, blaustichig-roter Ton. Über die Jahre eine der meistverkauften Lippenstifte weltweit.',
        ['MAC', 'Lippenstift']),
    mc('q-beauty-105', 'beauty', 3,
        'Wer gründete die Kosmetikmarke Estée Lauder 1946?',
        ['Elizabeth Arden', 'Estée Lauder', 'Helena Rubinstein', 'Georges Payot'], 1,
        'Josephine Esther Mentzer (später Estée Lauder). Rivalität mit Elizabeth Arden und Helena Rubinstein prägte die frühe US-Kosmetikindustrie.',
        ['Estée Lauder', 'Kosmetik']),
    mc('q-beauty-106', 'beauty', 3,
        'Welche kosmetische Behandlung nutzt Bindegewebsverjüngung durch feine Nadelstiche?',
        ['Botox', 'Microneedling', 'Chemisches Peeling', 'Laser'], 1,
        'Microneedling (Dermaroller/Dermapen). Regt Kollagenbildung an. Mildert Narben, Falten, große Poren.',
        ['Microneedling', 'Skincare']),
    mc('q-beauty-107', 'beauty', 3,
        'Welcher Kosmetik-Trend aus Korea revolutionierte 2010er Hautpflege mit vielstufigen Routinen?',
        ['J-Beauty', 'K-Beauty', 'French Girl', 'Nordic Care'], 1,
        'K-Beauty (Korean Beauty): 7–10-Stufen-Routine mit Cleansing, Toner, Essence, Serum, Mask, Moisturizer, SPF. Trendsetter waren u. a. Innisfree, Missha.',
        ['K-Beauty', 'Korea']),
    mc('q-beauty-108', 'beauty', 2,
        'Welche Marke aus Frankreich wurde 2019 für ihre CC-Cream „Effaclar" bekannt?',
        ['Vichy', 'La Roche-Posay', 'Bioderma', 'Avène'], 1,
        'La Roche-Posay, Teil des L\'Oréal-Konzerns. Fokus: sensible und unreine Haut. Apotheken-Kosmetik.',
        ['La Roche-Posay', 'Apotheken-Kosmetik']),
    mc('q-beauty-109', 'beauty', 3,
        'Welches Botenstoff-Molekül wird in der ästhetischen Medizin zur Faltenglättung gespritzt?',
        ['Kollagen', 'Hyaluron', 'Botulinumtoxin (Botox)', 'Silikon'], 2,
        'Botulinumtoxin lähmt Muskeln lokal, dass Falten sich weniger stark ausprägen. Wirkt 3–6 Monate.',
        ['Botox', 'Botulinumtoxin']),
    mc('q-beauty-110', 'beauty', 2,
        'Welche Duftpyramide-Note verfliegt am schnellsten und wird als „Kopfnote" bezeichnet?',
        ['Zitrus', 'Rose', 'Sandelholz', 'Vanille'], 0,
        'Kopfnoten (leichte Zitrusdüfte) verfliegen in 15–30 Minuten. Herznoten (Blumen, Kräuter) halten Stunden. Basisnoten (Hölzer, Amber) bleiben tagelang.',
        ['Parfum', 'Duft']),
    mc('q-beauty-111', 'beauty', 3,
        'Welcher Iconic-Duft von Chanel ist seit 1921 im Verkauf?',
        ['Chanel No 5', 'Miss Dior', 'Shalimar', 'Chanel Coco'], 0,
        'Chanel No 5, entworfen von Ernest Beaux 1921. Marilyn Monroes berühmter Slogan: „Zum Schlafen? Fünf Tropfen von Chanel No 5."',
        ['Chanel No 5', 'Parfum']),
    mc('q-beauty-112', 'beauty', 3,
        'Welche Beauty-Marke gehört Rihanna und ist bekannt für inklusive Foundation-Vielfalt (40+ Farbtöne)?',
        ['Fenty Beauty', 'Kylie Cosmetics', 'Rare Beauty', 'Huda Beauty'], 0,
        'Fenty Beauty (2017): Robyn Rihanna Fenty. Ein Meilenstein für Diversität in der Foundation-Palette. Umsatz erstes Jahr: 500 Mio. USD.',
        ['Fenty', 'Rihanna']),
    mc('q-beauty-113', 'beauty', 3,
        'Welche Rasier-Marke gehört zu Procter & Gamble und dominiert seit den 1970ern den Markt?',
        ['Wilkinson', 'Gillette', 'Braun', 'BIC'], 1,
        'Gillette, gegründet 1901 von King C. Gillette. 2005 von P&G übernommen für 57 Mrd. USD.',
        ['Gillette', 'Rasur']),
    mc('q-beauty-114', 'beauty', 4,
        'Welches Anti-Aging-Wirkstoff-Prinzip von The Ordinary war 2016/17 der Auslöser für Discount-Skincare-Hype?',
        [
            'Hoch dosierte Wirkstoffe zu Rohstoffpreisen',
            'Bio-only Herstellung',
            'Handgeschmiedete Verpackung',
            'Prestige-Marketing',
        ], 0,
        'The Ordinary (Deciem, Kanada): Wirkstoffe „ohne Verpackungs-Overhead" — Niacinamide 10 % für 6 USD, Retinol Squalane etc. Deciem-CEO Brandon Truaxe starb tragisch 2019.',
        ['The Ordinary', 'Skincare']),
    mc('q-beauty-115', 'beauty', 2,
        'Welche natürliche Substanz aus Zuckerrohr wird oft als Peeling-Wirkstoff genutzt?',
        ['Salicylsäure', 'Glykolsäure', 'Retinsäure', 'Vitamin C'], 1,
        'Glykolsäure (AHA, α-Hydroxysäure). Kleinstes Molekül der Fruchtsäuren — dringt tief. Löst tote Hautzellen an der Oberfläche.',
        ['Glykolsäure', 'AHA']),
    mc('q-beauty-116', 'beauty', 3,
        'Welche Beauty-Ikone leitete Elizabeth Arden 1966 als „Königin der Kosmetik" und starb mit 84?',
        ['Elizabeth Arden (Florence Nightingale Graham)', 'Helena Rubinstein', 'Coco Chanel', 'Estée Lauder'], 0,
        'Florence Nightingale Graham (1878–1966), aka Elizabeth Arden. Kanadierin, aufgestiegen zu einer der reichsten Selfmade-Frauen der USA.',
        ['Elizabeth Arden']),
    mc('q-beauty-117', 'beauty', 2,
        'Welche Gesichts-Muskelentspannungs-Technik nutzt Steine oder Rollen zur Lymphdrainage?',
        ['Kryolipolyse', 'Gua Sha', 'Micro-Current', 'Hydrafacial'], 1,
        'Gua Sha (Guasha) aus der traditionellen chinesischen Medizin. Mit Jade- oder Rosenquarz-Stein. Fördert Durchblutung, reduziert Schwellungen.',
        ['Gua Sha', 'TCM']),
    mc('q-beauty-118', 'beauty', 3,
        'Welche Marke des Kylie Jenner-Universums wurde bereits 2016 zum Milliardenhit dank Lip Kits?',
        ['Kylie Cosmetics', 'KKW Beauty', 'Fenty Beauty', 'Rare Beauty'], 0,
        'Kylie Cosmetics: Startschuss Lip Kits 2015. Auf Instagram über 400 Mio. Follower-Reichweite half beim Direct-to-Consumer-Modell.',
        ['Kylie Cosmetics', 'Jenner']),
    mc('q-beauty-119', 'beauty', 4,
        'Welche Marke schuf 1978 den ersten Anti-Aging-Bestseller „Capture" mit Liposomen?',
        ['Dior', 'Chanel', 'Lancôme', 'Clinique'], 0,
        'Dior Capture 1978: erste Anti-Aging-Creme mit Liposomen-Technologie zur besseren Wirkstoffaufnahme. Ein Meilenstein der Beauty-Innovation.',
        ['Dior', 'Anti-Aging']),
]

# ================================================================
# NATUR & TIERE (20)
# ================================================================
NEW_QUESTIONS += [
    mc('q-natur-100', 'natur', 1,
        'Wie viele Beine hat ein Insekt?',
        ['4', '6', '8', '10'], 1,
        'Insekten (Klasse Insecta) haben immer 6 Beine, geteilt in Kopf-Brust-Hinterleib. Spinnen haben 8 (Klasse Arachnida).',
        ['Insekt', 'Beine']),
    mc('q-natur-101', 'natur', 1,
        'Welches ist das schnellste Landtier der Erde?',
        ['Löwe', 'Gepard', 'Wolf', 'Antilope'], 1,
        'Gepard (Acinonyx jubatus): 100–120 km/h auf kurzen Strecken. Kann diese Geschwindigkeit aber nur ~30 Sekunden halten.',
        ['Gepard', 'Rekord']),
    mc('q-natur-102', 'natur', 2,
        'Welches Meerestier hat drei Herzen und ist für seine Tarnfähigkeiten berühmt?',
        ['Delfin', 'Hai', 'Tintenfisch (Krake)', 'Wal'], 2,
        'Kraken (Octopoden) haben drei Herzen: eines für Körper-Kreislauf, zwei für Kiemen. Auch neun Gehirne (eins zentral, acht in den Armen).',
        ['Krake', 'Anatomie']),
    mc('q-natur-103', 'natur', 3,
        'Welches Säugetier legt Eier (statt lebende Junge zu gebären)?',
        ['Ameisenbär', 'Schnabeltier', 'Faultier', 'Wombat'], 1,
        'Schnabeltier und Ameisenigel — die Kloakentiere (Monotremata). Beide leben in Australien/Neuguinea. Junge schlüpfen aus Eiern, saugen dann Milch.',
        ['Schnabeltier', 'Monotremata']),
    mc('q-natur-104', 'natur', 2,
        'Wie heißt die längste Schlange der Welt?',
        ['Königskobra', 'Anakonda', 'Netzpython', 'Boa'], 2,
        'Netzpython (Python reticulatus) aus Südostasien: bis zu 10 Meter lang. Anakondas sind kürzer, aber schwerer (bis 200 kg).',
        ['Netzpython', 'Schlange']),
    mc('q-natur-105', 'natur', 2,
        'Welches Tier gilt als der einzige Vogel, der rückwärts fliegen kann?',
        ['Adler', 'Kolibri', 'Papagei', 'Falke'], 1,
        'Kolibris können durch ihre besondere Flügelmuskulatur rückwärts, seitwärts und in der Luft schweben — Herzschlag bis 1 200/min.',
        ['Kolibri', 'Rekord']),
    mc('q-natur-106', 'natur', 3,
        'Wie lange schläft ein Faultier im Durchschnitt pro Tag?',
        ['5–7 Stunden', '10–12 Stunden', '15–18 Stunden', '20–22 Stunden'], 2,
        'Faultiere (Bradypus) schlafen in freier Wildbahn ~9,6 h/Tag; in Zoos bis zu 15–18 h. Mythos „20 Stunden Schlaf" wurde durch Studien widerlegt.',
        ['Faultier', 'Schlaf']),
    mc('q-natur-107', 'natur', 3,
        'Welche Tierart ist die Umweltbotschafterin der WWF und Wappenlogo dieser Organisation?',
        ['Tiger', 'Panda', 'Eisbär', 'Delfin'], 1,
        'Großer Panda (Ailuropoda melanoleuca). WWF-Gründer Sir Peter Scott entwarf das Logo 1961, inspiriert von einem Panda-Baby im Londoner Zoo.',
        ['Panda', 'WWF']),
    mc('q-natur-108', 'natur', 3,
        'Welches Tier hält den Rekord für die längste Wanderung — bis zu 44 000 km pro Jahr?',
        ['Wal', 'Zugvogel Küstenseeschwalbe', 'Ren', 'Gnu'], 1,
        'Küstenseeschwalbe (Sterna paradisaea): pendelt zwischen Nord- und Südpolarkreis. Erlebt so mehr Tageslicht als jedes andere Tier.',
        ['Küstenseeschwalbe', 'Rekord']),
    mc('q-natur-109', 'natur', 2,
        'Welche der folgenden Katzenarten ist die kleinste Wildkatze der Welt?',
        ['Ozelot', 'Rostkatze', 'Serval', 'Karakal'], 1,
        'Rostkatze (Prionailurus rubiginosus), 35–50 cm, 1–1,6 kg. Lebt in Sri Lanka und Indien.',
        ['Rostkatze', 'Wildkatze']),
    mc('q-natur-110', 'natur', 3,
        'Was ist die kleinste Vogelart der Welt?',
        ['Zaunkönig', 'Kolibri (Bienenelfe)', 'Buchfink', 'Feuerkopf'], 1,
        'Bienenelfe (Mellisuga helenae): 5–6 cm, 1,6–2 g. Nur auf Kuba heimisch.',
        ['Bienenelfe', 'Rekord']),
    mc('q-natur-111', 'natur', 3,
        'Welches Landtier hat den höchsten Blutdruck?',
        ['Elefant', 'Giraffe', 'Nashorn', 'Nilpferd'], 1,
        'Giraffe: Herz muss Blut ~2 Meter nach oben zum Kopf pumpen. Blutdruck ~280/180 mmHg — doppelt so hoch wie beim Menschen.',
        ['Giraffe', 'Blutdruck']),
    mc('q-natur-112', 'natur', 2,
        'Wie heißt der Wald, der als „grüne Lunge der Erde" bezeichnet wird?',
        ['Boreal-Wald', 'Kongo-Regenwald', 'Amazonas-Regenwald', 'Sequoia-Wald'], 2,
        'Amazonas-Regenwald: ~5,5 Millionen km², produziert ~10 % des atmosphärischen Sauerstoffs. Größte Bedrohung: Abholzung, v. a. in Brasilien.',
        ['Amazonas', 'Regenwald']),
    mc('q-natur-113', 'natur', 3,
        'Welche Bienen-Aufgabe wird durch den „Schwänzeltanz" kommuniziert?',
        [
            'Warnung vor Raubtieren',
            'Anzeige einer Futterquelle',
            'Paarungsbereitschaft',
            'Umzug zum neuen Bienenstock',
        ], 1,
        'Karl von Frisch entschlüsselte den Schwänzeltanz (Nobelpreis 1973). Die Richtung des Tanzes zeigt den Winkel zur Sonne, die Länge die Entfernung.',
        ['Bienen', 'Schwänzeltanz']),
    mc('q-natur-114', 'natur', 3,
        'Welche Elefantenart ist die größte lebende Landtierart?',
        ['Asiatischer Elefant', 'Afrikanischer Buschelefant', 'Afrikanischer Waldelefant', 'Alle gleich groß'], 1,
        'Afrikanischer Buschelefant (Loxodonta africana): bis 6 Tonnen, 3,5 m Schulterhöhe. Asiaten kleiner, Waldelefanten am kleinsten.',
        ['Elefant', 'Buschelefant']),
    mc('q-natur-115', 'natur', 2,
        'Welche Farbe hat das Blut eines Hufeisenkrebses?',
        ['Rot', 'Grün', 'Blau', 'Weiß'], 2,
        'Hufeisenkrebse haben Kupfer-basiertes Hämocyanin statt Eisen-Hämoglobin. In der Pharma-Industrie zur Endotoxin-Detektion in Impfstoffen genutzt.',
        ['Hufeisenkrebs', 'Blut']),
    mc('q-natur-116', 'natur', 3,
        'Wie lange trägt eine Elefantenkuh ihr Junges?',
        ['9 Monate', '12 Monate', '18 Monate', '22 Monate'], 3,
        'Rund 22 Monate (~660 Tage) — die längste Tragzeit aller Landtiere. Neugeborene Kälber wiegen ~120 kg.',
        ['Elefant', 'Tragzeit']),
    mc('q-natur-117', 'natur', 3,
        'Welches Tier ist der einzige Reptilie mit vier Herzkammern (statt der üblichen drei)?',
        ['Chamäleon', 'Warane', 'Krokodil', 'Leguan'], 2,
        'Krokodile haben ein vierkammeriges Herz, ähnlich Vögeln und Säugetieren. Sie sind evolutionär näher mit Vögeln verwandt als mit anderen Reptilien.',
        ['Krokodil', 'Herz']),
    mc('q-natur-118', 'natur', 2,
        'Welches Landtier hat mit ~600 kg das schwerste Gehirn (in absoluten Zahlen)?',
        ['Elefant', 'Giraffe', 'Pottwal (nicht Landtier)', 'Blauwal'], 0,
        'Elefanten-Gehirn wiegt ~5 kg. Pottwal (Wal, nicht Landtier) hat mit ~8 kg das größte Gehirn überhaupt. Menschen-Gehirn: ~1,4 kg.',
        ['Elefant', 'Gehirn']),
    mc('q-natur-119', 'natur', 3,
        'Wie viele bekannte Käferarten gibt es weltweit?',
        ['~30 000', '~150 000', '~350 000', '~1 000 000'], 2,
        'Käfer (Coleoptera) machen fast 25 % aller beschriebenen Tierarten aus. Rund 350 000 Arten bekannt, geschätzt bis zu 1 Million existierend.',
        ['Käfer', 'Biodiversität']),
]


def main() -> int:
    with QUESTIONS_PATH.open('r', encoding='utf-8') as f:
        existing = json.load(f)
    existing_ids = {q['id'] for q in existing}
    to_add = [q for q in NEW_QUESTIONS if q['id'] not in existing_ids]
    if not to_add:
        print('Keine neuen Fragen.')
        return 0
    for q in to_add:
        assert len(q['options']) == 4
        assert 0 <= q['correctIndex'] < 4
    merged = existing + to_add
    with QUESTIONS_PATH.open('w', encoding='utf-8') as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
        f.write('\n')
    from collections import Counter
    print(f'✓ {len(to_add)} neue Fragen ergänzt (jetzt {len(merged)} insgesamt).')
    for t, c in sorted(Counter(q['topic'] for q in to_add).items()):
        print(f'  + {t:<14} {c}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
