#!/usr/bin/env python3
"""Batch 7: scifi, beziehungen, mystery, astrologie (80 Fragen)."""
from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
QUESTIONS_PATH = ROOT / 'packages' / 'shared' / 'src' / 'data' / 'questions.json'
NOW = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
MC_MODES = ['category-duel', 'flash', 'player-spotlight', 'sprinter',
            'points-ladder', 'category-board', 'duel-1v1', 'elimination', 'experts']


def mc(qid, topic, difficulty, question, options, correct, gm, tags, category='allgemeinbildung'):
    return {'id': qid, 'type': 'multiple-choice', 'status': 'approved',
        'category': category, 'topic': topic, 'difficulty': difficulty,
        'question': question, 'options': options, 'correctIndex': correct,
        'gmNote': gm, 'tags': tags, 'compatibleModes': MC_MODES,
        'timeScope': 'timeless', 'aiGenerated': True,
        'createdAt': NOW, 'updatedAt': NOW}


NEW_QUESTIONS = []

# SCI-FI & FANTASY (20)
NEW_QUESTIONS += [
    mc('q-scifi-100', 'scifi', 1,
        'In welcher Star-Wars-Sage schwingt Luke Skywalker sein Lichtschwert?',
        ['Star Trek', 'Star Wars', 'Battlestar Galactica', 'Dune'], 1,
        'Star Wars von George Lucas (1977). „Möge die Macht mit dir sein". Elf Kinofilme + Serien in Skywalker- und High-Republic-Ären.',
        ['Star Wars', 'Luke']),
    mc('q-scifi-101', 'scifi', 1,
        'Welcher Zauberer bringt Frodo Beutlin zum Kampf gegen Sauron?',
        ['Saruman', 'Gandalf', 'Radagast', 'Merlin'], 1,
        'Gandalf (der Graue, später der Weiße). Istari-Zauberer. Tolkiens „Herr der Ringe" (1954/55). Im Film: Ian McKellen.',
        ['Gandalf', 'Tolkien']),
    mc('q-scifi-102', 'scifi', 2,
        'Welcher Autor schrieb „Foundation" und die drei Robotergesetze?',
        ['Arthur C. Clarke', 'Isaac Asimov', 'Philip K. Dick', 'Ray Bradbury'], 1,
        'Isaac Asimov (1920–1992). Foundation-Zyklus (7 Bände). Berühmt für „I, Robot" und Roboterethik.',
        ['Asimov', 'Foundation']),
    mc('q-scifi-103', 'scifi', 2,
        'Welcher Sci-Fi-Klassiker von 1968 zeigt HAL 9000 als KI im Raumschiff?',
        ['Blade Runner', '2001: Odyssee im Weltraum', 'Solaris', 'Alien'], 1,
        '„2001: A Space Odyssey" von Stanley Kubrick, basiert auf Arthur C. Clarke. HAL: „I\'m sorry, Dave. I\'m afraid I can\'t do that."',
        ['Kubrick', 'HAL']),
    mc('q-scifi-104', 'scifi', 2,
        'Wer schrieb den Fantasy-Zyklus „Das Rad der Zeit" (14 Bände)?',
        ['George R. R. Martin', 'Robert Jordan', 'Brandon Sanderson', 'Terry Pratchett'], 1,
        'Robert Jordan (Pseudonym James Rigney). Nach seinem Tod 2007 vollendete Brandon Sanderson die letzten drei Bände.',
        ['Jordan', 'Rad der Zeit']),
    mc('q-scifi-105', 'scifi', 2,
        'Wer schrieb den Wüstenplaneten-Roman „Dune" (1965)?',
        ['Frank Herbert', 'Ursula K. Le Guin', 'Larry Niven', 'Kim Stanley Robinson'], 0,
        'Frank Herbert. 6 Dune-Romane. Sandwürmer, Melange (Spice), Fremen, Paul Atreides. Filme: Lynch 1984, Villeneuve 2021/2024.',
        ['Herbert', 'Dune']),
    mc('q-scifi-106', 'scifi', 3,
        'Wer schrieb den dystopischen Roman „Ich bin Legende", auf dem Vampir-Filme basieren?',
        ['Richard Matheson', 'Stephen King', 'H. G. Wells', 'John Wyndham'], 0,
        'Richard Matheson, 1954. Bereits dreimal verfilmt: „The Last Man on Earth" (1964), „The Omega Man" (1971), „I Am Legend" (2007) mit Will Smith.',
        ['Matheson', 'Vampir']),
    mc('q-scifi-107', 'scifi', 2,
        'Welche Sci-Fi-TV-Serie startete 1966 unter Gene Roddenberry mit dem Raumschiff Enterprise?',
        ['Battlestar Galactica', 'Star Trek', 'Doctor Who', 'The Twilight Zone'], 1,
        'Star Trek (Roddenberry). Kirk, Spock, McCoy. Franchise mit Filmen, Discovery, Picard, Strange New Worlds.',
        ['Star Trek', 'Enterprise']),
    mc('q-scifi-108', 'scifi', 3,
        'Welcher Philip-K.-Dick-Roman inspirierte den Film „Blade Runner"?',
        [
            'Ubik',
            'Do Androids Dream of Electric Sheep?',
            'A Scanner Darkly',
            'The Man in the High Castle',
        ], 1,
        '„Träumen Androiden von elektrischen Schafen?" (1968). Ridley Scott adaptierte 1982. Fortsetzung „Blade Runner 2049" (Villeneuve, 2017).',
        ['PKD', 'Blade Runner']),
    mc('q-scifi-109', 'scifi', 3,
        'Welches Sci-Fi-Universum umfasst „Cthulhu" und wurde von H. P. Lovecraft geschaffen?',
        ['Great Old Ones / Cthulhu-Mythos', 'Chronicles of Narnia', 'Mabinogion', 'Prydain'], 0,
        'Cthulhu-Mythos (Lovecraft, 1926). Uralte Wesen wie Cthulhu, Nyarlathotep, Azathoth. Prägte kosmischen Horror.',
        ['Cthulhu', 'Lovecraft']),
    mc('q-scifi-110', 'scifi', 2,
        'Wer schrieb „Game of Thrones" / „Das Lied von Eis und Feuer"?',
        ['Terry Brooks', 'George R. R. Martin', 'Joe Abercrombie', 'Robin Hobb'], 1,
        'George R. R. Martin (US, geb. 1948). 5 Bände seit 1996. HBO-Serie 2011–2019. Prequel: „House of the Dragon" (2022).',
        ['Martin', 'GoT']),
    mc('q-scifi-111', 'scifi', 3,
        'Welcher Autor schrieb „Neuromancer" (1984), Grundstein des Cyberpunk?',
        ['William Gibson', 'Bruce Sterling', 'Neal Stephenson', 'Rudy Rucker'], 0,
        'Gibson prägte „Cyberspace". Hugo, Nebula, PKD Award. Bezeichnend: Er tippte alles auf einer Hermes 2000 Schreibmaschine ohne Computer-Erfahrung.',
        ['Gibson', 'Cyberpunk']),
    mc('q-scifi-112', 'scifi', 2,
        'Welche Buchreihe von Suzanne Collins gab „Hunger Games" den Ursprung?',
        ['Divergent', 'Die Tribute von Panem (The Hunger Games)', 'Maze Runner', 'Legend'], 1,
        'Hunger Games (2008–2010). Katniss Everdeen. Dystopie mit Fernseh-Todesspielen. Prequel: „Ballad of Songbirds and Snakes" (2020).',
        ['Collins', 'Panem']),
    mc('q-scifi-113', 'scifi', 3,
        'Welcher Regisseur schuf „The Matrix" (1999) — mit den Wachowskis?',
        ['James Cameron', 'Wachowski Geschwister', 'Christopher Nolan', 'Ridley Scott'], 1,
        'Wachowskis (Lana & Lilly). Neo (Keanu Reeves) entdeckt die Matrix. „Red Pill vs. Blue Pill". Vier Filme.',
        ['Matrix', 'Wachowski']),
    mc('q-scifi-114', 'scifi', 2,
        'Wer schrieb „Frankenstein" (1818), oft als erster Sci-Fi-Roman genannt?',
        ['Bram Stoker', 'Mary Shelley', 'Edgar Allan Poe', 'Jules Verne'], 1,
        'Mary Shelley schrieb es mit 18. In der Villa Diodati (Genfer See) mit Byron & Percy Shelley. Untertitel: „The Modern Prometheus".',
        ['Shelley', 'Frankenstein']),
    mc('q-scifi-115', 'scifi', 3,
        'Wer schrieb „Die Reise zum Mittelpunkt der Erde" (1864)?',
        ['H. G. Wells', 'Jules Verne', 'Arthur Conan Doyle', 'Karl May'], 1,
        'Jules Verne (F, 1828–1905). Weitere: „20 000 Meilen unter dem Meer", „In 80 Tagen um die Welt". Zusammen mit Wells: Vater der Sci-Fi.',
        ['Verne', 'Mittelpunkt']),
    mc('q-scifi-116', 'scifi', 3,
        'Wer erschuf die „Discworld"-Serie (Scheibenwelt) mit Rincewind, Tod und Vetinari?',
        ['Douglas Adams', 'Terry Pratchett', 'Neil Gaiman', 'Piers Anthony'], 1,
        'Terry Pratchett (1948–2015). 41 Discworld-Romane (1983–2015). Fantasy-Satire. Zusammen mit Gaiman: „Good Omens".',
        ['Pratchett', 'Discworld']),
    mc('q-scifi-117', 'scifi', 2,
        'In welcher Sci-Fi-Reihe fliegen Han Solo & Chewbacca den Millennium Falcon?',
        ['Firefly', 'Star Wars', 'Star Trek', 'The Expanse'], 1,
        'Star Wars. Millennium Falcon: „schnellstes Frachtschiff der Galaxis". Kessel Run in „unter 12 Parsec".',
        ['Star Wars', 'Falcon']),
    mc('q-scifi-118', 'scifi', 4,
        'Wer schrieb „Per Anhalter durch die Galaxis" (1979)?',
        ['Douglas Adams', 'Robert Sheckley', 'John Scalzi', 'Terry Brooks'], 0,
        'Douglas Adams (1952–2001). 5 Bände (davon einige nach seinem Tod). „Die Antwort auf die Frage nach dem Leben, dem Universum und dem Rest ist 42".',
        ['Adams', 'Hitchhiker']),
    mc('q-scifi-119', 'scifi', 3,
        'Welche Buchreihe von C. S. Lewis handelt von Kindern, die durch einen Schrank in eine magische Welt gelangen?',
        ['Der Herr der Ringe', 'Die Chroniken von Narnia', 'Discworld', 'Erdsee'], 1,
        'Narnia (1950–1956). 7 Bände. „Der König von Narnia" (Aslan), „Prinz Kaspian", „Die Reise auf der Morgenröte". Lewis war Freund von Tolkien.',
        ['Lewis', 'Narnia']),
]

# BEZIEHUNGEN & LIEBE (20)
NEW_QUESTIONS += [
    mc('q-beziehungen-100', 'beziehungen', 1,
        'An welchem Datum wird der Valentinstag traditionell gefeiert?',
        ['1. Februar', '14. Februar', '1. März', '14. April'], 1,
        '14. Februar. Nach dem heiligen Valentin von Terni (3. Jh.). In den USA seit dem 19. Jh. großer Tag für Karten, Blumen, Schokolade.',
        ['Valentinstag', '14. Februar']),
    mc('q-beziehungen-101', 'beziehungen', 1,
        'Welches Symbol steht klassisch für die Liebe?',
        ['Herz', 'Stern', 'Blitz', 'Anker'], 0,
        'Herz. Ursprung des Symbols nicht sicher — evtl. Silphium-Samen (antikes Kontrazeptivum) oder stilisiertes anatomisches Herz.',
        ['Herz', 'Symbol']),
    mc('q-beziehungen-102', 'beziehungen', 2,
        'Wie nennt man die romantische Reise nach der Hochzeit?',
        ['Weekend', 'Flitterwochen (Honeymoon)', 'Sabbatical', 'Roadtrip'], 1,
        'Flitterwochen. Wortherkunft: „Honigmond" (Met-Woche nach der Hochzeit). Klassisch 1–3 Wochen an romantischen Zielen.',
        ['Flitterwochen', 'Honeymoon']),
    mc('q-beziehungen-103', 'beziehungen', 2,
        'Welche fünf „Love Languages" definierte Gary Chapman?',
        [
            'Words of Affirmation, Quality Time, Gifts, Acts of Service, Physical Touch',
            'Kommunikation, Empathie, Vertrauen, Nähe, Sex',
            'Attachment, Passion, Commitment, Communication, Loyalty',
            'Freundschaft, Familie, Beruf, Romantik, Selbstliebe',
        ], 0,
        'Chapmans „5 Love Languages" (1992). Konzept: Menschen empfinden Liebe unterschiedlich (Worte, Zeit, Geschenke, Dienste, Berührung).',
        ['Love Languages', 'Chapman']),
    mc('q-beziehungen-104', 'beziehungen', 3,
        'Welches Hormon wird als „Kuschelhormon" bezeichnet?',
        ['Adrenalin', 'Oxytocin', 'Testosteron', 'Melatonin'], 1,
        'Oxytocin — bei Umarmung, Sex, Geburt, Stillen ausgeschüttet. Stärkt Bindung. Auch als Bindungs- oder Vertrauenshormon bekannt.',
        ['Oxytocin', 'Bindung']),
    mc('q-beziehungen-105', 'beziehungen', 2,
        'Welchen Hochzeitstag feiert man nach 25 Jahren Ehe?',
        ['Bronze', 'Silber', 'Rubin', 'Gold'], 1,
        'Silberhochzeit. Goldhochzeit = 50 Jahre. Diamant = 60. Eisen = 6. Rubin = 40. Perle = 30.',
        ['Silberhochzeit', 'Ehe']),
    mc('q-beziehungen-106', 'beziehungen', 2,
        'Welchen Hochzeitstag feiert man nach 50 Jahren Ehe?',
        ['Silber', 'Rubin', 'Gold', 'Diamant'], 2,
        'Goldhochzeit. Diamant = 60 Jahre. Gnaden- (Kron-)Hochzeit = 70. Eiche = 80.',
        ['Goldhochzeit', 'Ehe']),
    mc('q-beziehungen-107', 'beziehungen', 3,
        'Wie viele Bindungstypen unterschied John Bowlby / Mary Ainsworth?',
        ['2', '3', '4', '5'], 2,
        '4: sicher, unsicher-vermeidend, unsicher-ambivalent, desorganisiert. Ainsworths „Fremde Situation" (1970er). Bowlby: Bindungstheorie.',
        ['Bindungstheorie', 'Ainsworth']),
    mc('q-beziehungen-108', 'beziehungen', 2,
        'Was bedeutet „Ghosting" im Dating?',
        [
            'Zu viel telefonieren',
            'Plötzlicher Kontaktabbruch ohne Erklärung',
            'Nachts Nachrichten schreiben',
            'Öffentliche Trennung',
        ], 1,
        'Ghosting: eine Person bricht Kontakt komplett ab. Häufig im Online-Dating. Rangiert psychologisch mit sozialer Ausgrenzung.',
        ['Ghosting', 'Dating']),
    mc('q-beziehungen-109', 'beziehungen', 3,
        'Welche drei Komponenten enthält Robert Sternbergs „Dreieckstheorie der Liebe"?',
        [
            'Intimität, Leidenschaft, Verpflichtung',
            'Freundschaft, Sex, Vertrauen',
            'Ehe, Kinder, Beruf',
            'Familie, Herkunft, Zukunft',
        ], 0,
        'Sternberg (1986). Sieben Kombinationen (z. B. „konsumierende Liebe" = alle drei). Klassiker der Beziehungspsychologie.',
        ['Sternberg', 'Liebe']),
    mc('q-beziehungen-110', 'beziehungen', 2,
        'Wie nennt man einen sehr kurzen Beziehungsanfang, in dem sich Paare stark ineinander verlieben?',
        ['Rebound', 'Honeymoon-Phase', 'Situationship', 'Silent Treatment'], 1,
        'Honeymoon-Phase. Neurochemisch: Dopamin, Adrenalin, Noradrenalin dominant. Dauert meist 6–24 Monate.',
        ['Honeymoon', 'Phase']),
    mc('q-beziehungen-111', 'beziehungen', 2,
        'Welche Farbe hat traditionell das Brautkleid in westlichen Kulturen?',
        ['Rot', 'Blau', 'Weiß', 'Grün'], 2,
        'Weiß. Königin Victoria 1840 (Heirat mit Albert) machte weißes Brautkleid populär. Symbolisierte damals Reichtum, nicht Reinheit.',
        ['Brautkleid', 'Victoria']),
    mc('q-beziehungen-112', 'beziehungen', 3,
        'Was ist „Situationship" im Dating?',
        [
            'Situation im Bewerbungsgespräch',
            'Nicht klar definierte, mehr als Freundschaft, weniger als Beziehung',
            'Fernbeziehung',
            'Trennung auf Zeit',
        ], 1,
        'Situationship — Beziehung ohne Label. In Umfragen 2022: 40 % der Millennials/Gen Z hatten schon eine. Häufig mit Kommunikationsproblemen verbunden.',
        ['Situationship', 'Dating']),
    mc('q-beziehungen-113', 'beziehungen', 2,
        'Welches Tier symbolisiert lebenslange Partnertreue?',
        ['Fuchs', 'Adler', 'Schwan', 'Wolf'], 2,
        'Schwan. Höckerschwäne bleiben meist ein Leben lang mit einem Partner zusammen. Auch Wölfe/Adler sind treu, aber Schwan ist das Symbol.',
        ['Schwan', 'Treue']),
    mc('q-beziehungen-114', 'beziehungen', 3,
        'Welche Studie (Gottman) fand die vier zerstörerischen Kommunikationsmuster in Paaren?',
        [
            'Kritik, Verteidigung, Verachtung, Mauern',
            'Zorn, Trauer, Angst, Freude',
            'Sex, Geld, Kinder, Familie',
            'Reden, Schweigen, Streiten, Ignorieren',
        ], 0,
        'John Gottman: „Die vier apokalyptischen Reiter" — Kritik (criticism), Verachtung (contempt, stärkster Prädiktor), Verteidigung, Mauern (stonewalling).',
        ['Gottman', 'Vier Reiter']),
    mc('q-beziehungen-115', 'beziehungen', 2,
        'Welche Bindungshormon wird beim Verliebtsein besonders ausgeschüttet?',
        ['Serotonin', 'Dopamin', 'Cortisol', 'Insulin'], 1,
        'Dopamin (Belohnungssystem). Zusammen mit Noradrenalin (Erregung) und niedrigem Serotonin (obsessives Denken).',
        ['Dopamin', 'Verliebtsein']),
    mc('q-beziehungen-116', 'beziehungen', 3,
        'Wie lange muss man in Deutschland getrennt leben, um einvernehmlich geschieden zu werden?',
        ['3 Monate', '6 Monate', '1 Jahr', '3 Jahre'], 2,
        '1 Trennungsjahr (§ 1566 BGB, einvernehmlich). Bei streitiger Scheidung: 3 Jahre. In Härtefällen früher.',
        ['Trennungsjahr', 'BGB']),
    mc('q-beziehungen-117', 'beziehungen', 2,
        'Was bezeichnet der Begriff „Polyamorie"?',
        [
            'Angst vor Bindung',
            'Einvernehmliche Mehrfachbeziehungen mit Wissen aller Partner',
            'Heimliches Fremdgehen',
            'Beziehung mit Altersunterschied',
        ], 1,
        'Polyamorie: mehrere gleichberechtigte, offene Beziehungen. Unterschied zu Polygamie (Ehe mit mehreren): rechtlich, meist religiös.',
        ['Polyamorie', 'Beziehung']),
    mc('q-beziehungen-118', 'beziehungen', 4,
        'In welchem Land ist Polygamie noch legal für Männer, meist bis zu 4 Ehefrauen?',
        ['Deutschland', 'Frankreich', 'Saudi-Arabien', 'Japan'], 2,
        'Saudi-Arabien (und weitere muslimische Länder). Im Islam max. 4 Ehefrauen, an Bedingungen (Gleichbehandlung) geknüpft. In DE, F, J illegal.',
        ['Polygamie', 'Recht']),
    mc('q-beziehungen-119', 'beziehungen', 2,
        'Wie viel darf ein Ehering laut alter Faustregel ungefähr kosten?',
        ['1 Monatsgehalt', '2 Monatsgehälter', '3 Monatsgehälter', '6 Monatsgehälter'], 2,
        '3 Monatsgehälter — De-Beers-Werbekampagne von 1947. Reine Marketingregel. Heute variabel; viele Paare geben weniger aus.',
        ['Ehering', 'De Beers']),
]

# MYSTERY & ÜBERNATÜRLICHES (20)
NEW_QUESTIONS += [
    mc('q-mystery-100', 'mystery', 1,
        'Welches Fabelwesen soll in einem schottischen See leben?',
        ['Yeti', 'Nessie (Loch-Ness-Monster)', 'Kraken', 'Chupacabra'], 1,
        'Loch Ness Monster („Nessie"), Schottland. Legende seit dem 6. Jh. (Adamnan über Columban). Berühmtes „Chirurgenfoto" (1934) war Fake.',
        ['Nessie', 'Schottland']),
    mc('q-mystery-101', 'mystery', 1,
        'Welches Wesen wird bei Vollmond aus einem Menschen — laut Mythos?',
        ['Vampir', 'Werwolf', 'Zombie', 'Golem'], 1,
        'Werwolf (Lykanthrop). Verwandlung bei Vollmond. Silber gilt als schwach machend. Prägend: „The Wolf Man" (1941).',
        ['Werwolf', 'Vollmond']),
    mc('q-mystery-102', 'mystery', 2,
        'Wo verschwinden angeblich Schiffe und Flugzeuge im Dreieck zwischen Miami, Bermuda und Puerto Rico?',
        ['Sargassosee', 'Bermudadreieck', 'Roaring Forties', 'Marianengraben'], 1,
        'Bermudadreieck. Beliebte Verschwörung seit den 1950ern. Wissenschaftlich: keine ungewöhnliche Häufung von Verlusten, Legende von V. Sanderson populär gemacht.',
        ['Bermuda', 'Dreieck']),
    mc('q-mystery-103', 'mystery', 2,
        'Welche schneeweiße Kreatur soll im Himalaya leben?',
        ['Bigfoot', 'Yeti', 'Mothman', 'Chupacabra'], 1,
        'Yeti („abscheulicher Schneemann"). Sherpa-Legenden. Nepal & Bhutan. DNA-Analysen fanden meist Bär- oder Ziegenhaare.',
        ['Yeti', 'Himalaya']),
    mc('q-mystery-104', 'mystery', 2,
        'Was ist der „Kraken" der nordischen Legende?',
        ['Meergott', 'Riesiger Tintenfisch/Wesen', 'Schiff', 'Sturm'], 1,
        'Kraken — riesiger Tintenfisch/Kalmar, der Schiffe versenkt. Norwegische Seefahrer-Mythen. Möglicherweise inspiriert vom Riesenkalmar (Architeuthis).',
        ['Kraken', 'Nordisch']),
    mc('q-mystery-105', 'mystery', 3,
        'Wo befindet sich die berüchtigte Area 51 mit UFO-Legenden?',
        ['Arizona', 'Nevada', 'New Mexico', 'Kalifornien'], 1,
        'Nevada, USA (bei Groom Lake). US-Militärstützpunkt. 2013 offiziell zugegeben. Fokus: geheime Flugzeugentwicklung (U-2, SR-71).',
        ['Area 51', 'Nevada']),
    mc('q-mystery-106', 'mystery', 2,
        'Wie heißt der berühmte 1947er UFO-Vorfall in New Mexico?',
        ['Rendlesham', 'Roswell', 'Kelly-Hopkinsville', 'Belgien-Welle'], 1,
        'Roswell Incident (Juli 1947). Absturz eines militärischen „Wetterballons" (Project Mogul). UFO-Kultstadt bis heute.',
        ['Roswell', 'UFO']),
    mc('q-mystery-107', 'mystery', 2,
        'Welche Trickfilm-Serie hat eine Truppe, die Geister und Monster entlarvt?',
        ['Ghostbusters', 'Scooby-Doo', 'X-Files', 'Supernatural'], 1,
        'Scooby-Doo (Hanna-Barbera, 1969). Mystery Inc.: Fred, Daphne, Velma, Shaggy und Scooby. Am Ende ist es meist Mr. Jones in der Maske.',
        ['Scooby-Doo', 'Mystery Inc']),
    mc('q-mystery-108', 'mystery', 3,
        'Wer schrieb „Dracula" (1897)?',
        ['Mary Shelley', 'Bram Stoker', 'Edgar Allan Poe', 'H. P. Lovecraft'], 1,
        'Bram Stoker (IR). Roman inspirierte Vlad III. Tepes (Rumänien). Erste Verfilmung: „Nosferatu" (Murnau, 1922).',
        ['Stoker', 'Dracula']),
    mc('q-mystery-109', 'mystery', 2,
        'Welches Zeichen zeichnet man in okkulten Ritualen mit 5 Zacken?',
        ['Kreuz', 'Pentagramm', 'Ankh', 'Om'], 1,
        'Pentagramm — 5-zackiger Stern. Symbol in Wicca, Antike, Christentum. Umgekehrt (Spitze unten) mit Satanismus assoziiert.',
        ['Pentagramm', 'Ritual']),
    mc('q-mystery-110', 'mystery', 3,
        'Welche keltischen Priester galten als Kenner von Naturmagie und Ritualen?',
        ['Wikinger', 'Druiden', 'Schamanen', 'Bonzen'], 1,
        'Druiden — Priester und Gelehrte der Kelten. Nach Cäsars „De bello Gallico". Zentralheiligtum vermutlich Anglesey (GB) oder Karnutenwald (F).',
        ['Druiden', 'Kelten']),
    mc('q-mystery-111', 'mystery', 2,
        'Wie nennt man einen Geist, der laut Aberglauben durch Poltern & Bewegen von Gegenständen auffällt?',
        ['Poltergeist', 'Sukkubus', 'Fetch', 'Doppelgänger'], 0,
        'Poltergeist (dt.). „Polter" + „Geist". Skeptiker führen viele Fälle auf Kinder/Jugendliche zurück (unbewusste Streiche, elektrostatische Effekte).',
        ['Poltergeist', 'Aberglaube']),
    mc('q-mystery-112', 'mystery', 3,
        'Welche altgriechische Stadt versank laut Platon im Meer?',
        ['Sparta', 'Atlantis', 'Troja', 'Delphi'], 1,
        'Atlantis (Platon, „Timaios" & „Kritias", ~360 v. Chr.). Fiktive Insel jenseits der Säulen des Herakles. Bis heute Basis für viele Theorien.',
        ['Atlantis', 'Platon']),
    mc('q-mystery-113', 'mystery', 3,
        'Was ist die „Nazca-Linie"?',
        [
            'Ausgetrocknetes Flussbett',
            'Riesenzeichnungen (Geoglyphen) in der Peru-Wüste',
            'Vulkangebirge',
            'Sternbild',
        ], 1,
        'Nazca-Geoglyphen (100 v. Chr. – 700 n. Chr.). Kolibri, Affe, Spinne, Astronaut. 300 km². UNESCO. Nur aus der Luft ganz erkennbar.',
        ['Nazca', 'Peru']),
    mc('q-mystery-114', 'mystery', 2,
        'Was ist ein „Doppelgänger" laut Mythos?',
        [
            'Zwillingsbruder',
            'Geisterhaftes Ebenbild eines lebenden Menschen',
            'Falscher Ausweis',
            'Schauspieler',
        ], 1,
        'Doppelgänger — schlechtes Omen in dt. Volksglauben. Poe („William Wilson"), Dostojewski („Der Doppelgänger"), Kafka.',
        ['Doppelgänger', 'Mythos']),
    mc('q-mystery-115', 'mystery', 3,
        'Welcher britische Steinkreis wird zur Sommersonnenwende von Druiden besucht?',
        ['Avebury', 'Stonehenge', 'Callanish', 'Ring of Brodgar'], 1,
        'Stonehenge (Salisbury Plain, ~2500 v. Chr.). UNESCO. Sonne geht zur Sommersonnenwende genau über dem Heel Stone auf.',
        ['Stonehenge', 'Sommersonnenwende']),
    mc('q-mystery-116', 'mystery', 2,
        'Was liest ein Wahrsager traditionell aus einer Kristallkugel?',
        ['Vergangenheit', 'Wetter', 'Zukunft', 'Sternzeichen'], 2,
        'Zukunft (Scrying). Wahrsagerei mit Kristall/Wasser. Berühmter Seher: Nostradamus (16. Jh.) — hunderte Vierzeiler.',
        ['Wahrsagerei', 'Kristall']),
    mc('q-mystery-117', 'mystery', 3,
        'Wer war Nostradamus?',
        [
            'Alchemist',
            'Französischer Apotheker & Wahrsager (1503–1566)',
            'Astronom',
            'Papst',
        ], 1,
        'Michel de Notre-Dame. „Les Prophéties" (1555) — 942 Vierzeiler. Katharina von Medici zog ihn zu Rate.',
        ['Nostradamus', 'Prophezeiung']),
    mc('q-mystery-118', 'mystery', 4,
        'Was ist ein „Mothman"?',
        [
            'Insekten-Riese',
            'Kryptid mit roten Augen, seit 1966 in Point Pleasant (USA) gesichtet',
            'Comicheld',
            'Fabelmensch aus Japan',
        ], 1,
        'Mothman — Point Pleasant, West Virginia (1966–67). Kryptid mit roten Augen, geflügelt. Assoziert mit Silver-Bridge-Einsturz (1967).',
        ['Mothman', 'Point Pleasant']),
    mc('q-mystery-119', 'mystery', 2,
        'Was zeigt eine „Kristallkugel"?',
        [
            'Fußballspiele',
            'Zukunftsvisionen (in der Wahrsagerei)',
            'Elektrische Felder',
            'Wetterdaten',
        ], 1,
        'Kristallkugel: Werkzeug der Scrying-Praktik. Oft aus Beryll oder Glas. Bekannt aus Filmen und Zirkus-Wahrsagerinnen.',
        ['Kristallkugel', 'Zukunft']),
]

# ASTROLOGIE & STERNZEICHEN (20)
NEW_QUESTIONS += [
    mc('q-astrologie-100', 'astrologie', 1,
        'Wie viele Sternzeichen (Tierkreiszeichen) gibt es in der westlichen Astrologie?',
        ['10', '12', '13', '14'], 1,
        '12: Widder, Stier, Zwillinge, Krebs, Löwe, Jungfrau, Waage, Skorpion, Schütze, Steinbock, Wassermann, Fische. IAU zählt astronomisch 13 (mit Schlangenträger).',
        ['Sternzeichen', 'Zwölf']),
    mc('q-astrologie-101', 'astrologie', 1,
        'Welches Sternzeichen hat Geburtsdatum um den 21. März bis 19. April?',
        ['Fische', 'Widder', 'Stier', 'Krebs'], 1,
        'Widder (Aries). Feuerzeichen. Regent: Mars. Erstes Zeichen im Tierkreis.',
        ['Widder', 'Aries']),
    mc('q-astrologie-102', 'astrologie', 2,
        'Welche vier Elemente werden Sternzeichen zugeordnet?',
        [
            'Feuer, Erde, Luft, Wasser',
            'Nord, Süd, Ost, West',
            'Sommer, Herbst, Winter, Frühling',
            'Sonne, Mond, Sterne, Meer',
        ], 0,
        'Feuer (Widder, Löwe, Schütze), Erde (Stier, Jungfrau, Steinbock), Luft (Zwillinge, Waage, Wassermann), Wasser (Krebs, Skorpion, Fische).',
        ['Elemente', 'Astrologie']),
    mc('q-astrologie-103', 'astrologie', 2,
        'Welcher Planet regiert das Sternzeichen Löwe?',
        ['Mars', 'Sonne', 'Mond', 'Merkur'], 1,
        'Sonne — Löwe (23. Juli – 22. August). Feuerzeichen, fix. Assoziation: Stolz, Kreativität, Führung.',
        ['Löwe', 'Sonne']),
    mc('q-astrologie-104', 'astrologie', 2,
        'Welches Sternzeichen wird durch einen Skorpion mit gebogenem Schwanz dargestellt?',
        ['Krebs', 'Skorpion', 'Steinbock', 'Fische'], 1,
        'Skorpion (Scorpio, 23. Oktober – 21. November). Wasserzeichen, fix. Regenten: Pluto/Mars.',
        ['Skorpion', 'Scorpio']),
    mc('q-astrologie-105', 'astrologie', 3,
        'Was ist der „Aszendent" in der Astrologie?',
        [
            'Höchster Punkt einer Bahn',
            'Sternzeichen am östlichen Horizont zur Geburt',
            'Mondphase am Geburtstag',
            'Kalendarisches Jahreszeichen',
        ], 1,
        'Aszendent (AC) — genau das Zeichen, das zur Geburt am östlichen Horizont aufsteigt. Ändert sich alle ~2 Stunden. Prägt „Außenwirkung".',
        ['Aszendent', 'AC']),
    mc('q-astrologie-106', 'astrologie', 2,
        'Welches Sternzeichen wird durch die Zwillinge Castor und Pollux repräsentiert?',
        ['Waage', 'Zwillinge', 'Schütze', 'Wassermann'], 1,
        'Zwillinge (Gemini, 21. Mai – 20. Juni). Luftzeichen. Regent: Merkur. Nach griech. Zwillingen Kastor & Polydeukes.',
        ['Zwillinge', 'Gemini']),
    mc('q-astrologie-107', 'astrologie', 2,
        'Welches Symbol steht für das Sternzeichen Waage?',
        ['Bogen', 'Waage/Balken', 'Fisch', 'Krug'], 1,
        'Waage (Libra, 23. September – 22. Oktober). Einzige „nicht-tierische" Zeichen. Luft, kardinal. Regent: Venus.',
        ['Waage', 'Libra']),
    mc('q-astrologie-108', 'astrologie', 3,
        'Welches Sternzeichen ist das letzte im Tierkreis?',
        ['Wassermann', 'Fische', 'Widder', 'Steinbock'], 1,
        'Fische (Pisces, 19. Februar – 20. März). Wasserzeichen, veränderlich. Regent: Neptun (klassisch: Jupiter).',
        ['Fische', 'Pisces']),
    mc('q-astrologie-109', 'astrologie', 2,
        'Welches chinesische Tierkreiszeichen 2024?',
        ['Tiger', 'Kaninchen', 'Drache', 'Schlange'], 2,
        '2024 = Jahr des Drachen (Holz-Drache). Chinesischer Zyklus: 12 Tiere × 5 Elemente = 60 Jahre. 2023 Kaninchen, 2025 Schlange.',
        ['Chinesisch', 'Drache']),
    mc('q-astrologie-110', 'astrologie', 3,
        'Wie nennt man in der Astrologie die Rückkehr eines Planeten zur Geburtsposition (~alle 12 Jahre bei Jupiter)?',
        ['Retrograde', 'Aspekt', 'Wiederkehr / Return', 'Nova'], 2,
        'Planetary Return: „Saturn Return" (~29 Jahre) und „Jupiter Return" (~12 Jahre) sind populäre Konzepte. Deuten oft als Lebensphasen.',
        ['Saturn Return', 'Return']),
    mc('q-astrologie-111', 'astrologie', 2,
        'Welches Sternzeichen ist bekannt für sein Symbol „Wassermann" mit Krug?',
        ['Wassermann', 'Krebs', 'Fische', 'Skorpion'], 0,
        'Wassermann (Aquarius, 20. Januar – 18. Februar). Luftzeichen, fix. Regent: Uranus (klassisch: Saturn). Symbol: Wasserträger mit Krug.',
        ['Wassermann', 'Aquarius']),
    mc('q-astrologie-112', 'astrologie', 3,
        'Was bedeutet „Merkur rückläufig" in der Popkultur der Astrologie?',
        [
            'Merkur bewegt sich schneller',
            'Optische Rückwärtsbewegung — Chaos in Kommunikation & Technik befürchtet',
            'Merkur verschwindet',
            'Merkur explodiert',
        ], 1,
        'Merkur retrograd — ~3× pro Jahr, jeweils ~3 Wochen. Astronomisch: perspektivischer Effekt. Astrologisch: Warnung für Reisen, Verträge, Kommunikation.',
        ['Retrograde', 'Merkur']),
    mc('q-astrologie-113', 'astrologie', 2,
        'Welches Sternzeichen wird oft als „geheimnisvoll" und „leidenschaftlich" beschrieben?',
        ['Steinbock', 'Skorpion', 'Widder', 'Stier'], 1,
        'Skorpion — Mystik, Tiefe, Intensität. Astrologische Stereotype (Traits sind natürlich nicht wissenschaftlich belegt).',
        ['Skorpion', 'Traits']),
    mc('q-astrologie-114', 'astrologie', 3,
        'Wie viele „Häuser" umfasst ein astrologisches Geburtshoroskop?',
        ['4', '10', '12', '24'], 2,
        '12 Häuser. Jedes steht für Lebensbereich (1. Selbst, 7. Partnerschaft, 10. Karriere, 12. Verborgenes). Kombination mit Zeichen & Planeten.',
        ['Häuser', 'Horoskop']),
    mc('q-astrologie-115', 'astrologie', 2,
        'Welches Sternzeichen hat den Steinbock als Symboltier?',
        ['Skorpion', 'Steinbock', 'Widder', 'Stier'], 1,
        'Steinbock (Capricornus, 22. Dezember – 19. Januar). Erdzeichen, kardinal. Regent: Saturn. Symbol: Steinbock mit Fisch-Schwanz (aus Mythos).',
        ['Steinbock', 'Capricorn']),
    mc('q-astrologie-116', 'astrologie', 3,
        'Welcher Astrologe schrieb „Der Kosmos und die Seele"? (Berühmter deutscher Astrologe des 20. Jh.?)',
        [
            'Reinhold Ebertin',
            'Louise Huber',
            'Wolfgang Döbereiner',
            'Alle drei sind bekannte deutsche Astrologen',
        ], 3,
        'Alle drei sind reale Namen der dt. Astrologie-Szene. Ebertin: „Kombination der Gestirneinflüsse". Huber-Astrologie (CH). Döbereiner (Münchner Rhythmenlehre).',
        ['Astrologen', 'Deutsch']),
    mc('q-astrologie-117', 'astrologie', 2,
        'Was ist ein „Doppel-Sternzeichen" im Alltag genannt?',
        [
            'Sonnenzeichen + Aszendent',
            'Zwillinge',
            'Vollmond',
            'Konjunktion',
        ], 0,
        'Populär: „Ich bin Löwe mit Aszendent Waage". Sonne = Kern, Aszendent = Außenwirkung. Für tiefes Profil auch Mond wichtig.',
        ['Aszendent', 'Sonne']),
    mc('q-astrologie-118', 'astrologie', 4,
        'Welche 13. Konstellation liegt auf der Ekliptik, wird aber traditionell nicht als Sternzeichen geführt?',
        ['Kleiner Wagen', 'Schlangenträger (Ophiuchus)', 'Orion', 'Kassiopeia'], 1,
        'Ophiuchus (Schlangenträger). Sonne durchläuft ihn ~30. Nov. – 17. Dez. Von der IAU 1930 offiziell zu den 88 Sternbildern gezählt.',
        ['Ophiuchus', 'Schlangenträger']),
    mc('q-astrologie-119', 'astrologie', 2,
        'Welches Sternzeichen wird oft mit dem Symbol des Stiers verbunden und regiert von der Venus?',
        ['Stier', 'Widder', 'Löwe', 'Skorpion'], 0,
        'Stier (Taurus, 20. April – 20. Mai). Erdzeichen, fix. Regent: Venus. Traits: sinnlich, ausdauernd, stur.',
        ['Stier', 'Taurus']),
]


def main() -> int:
    with QUESTIONS_PATH.open('r', encoding='utf-8') as f:
        existing = json.load(f)
    existing_ids = {q['id'] for q in existing}
    to_add = [q for q in NEW_QUESTIONS if q['id'] not in existing_ids]
    if not to_add:
        print('Keine neuen Fragen.')
        return 0
    for q in to_add:
        assert len(q['options']) == 4, q['id']
        assert 0 <= q['correctIndex'] < 4, q['id']
    merged = existing + to_add
    with QUESTIONS_PATH.open('w', encoding='utf-8') as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
        f.write('\n')
    from collections import Counter
    print(f'✓ {len(to_add)} neue Fragen ergänzt (jetzt {len(merged)} insgesamt).')
    for t, c in sorted(Counter(q['topic'] for q in to_add).items()):
        print(f'  + {t:<14} {c}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
